### ISSUE TITLE
Control+C to cancel a query support

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/snowflake-connector-net#1]
Before forgetting this (like me for golang), I'm filing an issue here for reminder.

**Comment by howryu** [comment]
Ctrl-C signal should be tracked by application, not by .net driver itself. In #22, async query execution is supported, which can take a cancellation token as argument. Application should catch ctrl-c signal and fire cancellation token source to cancel the query.

**Comment by smtakeda** [comment]
Ok. having async support, what code change will be required for the existing test example?
https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data.Tests/SFDbCommandIT.cs#L152
