### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by rjpaddock** [snowflakedb/snowflake-connector-net#101]
I downloaded this repository and trying to build it generates an error from Visual Studio as well as the msbuild on the command line.

This is the error

	Could not copy the file "parameters.json" because it was not found.	

Any hints on how to fix this ?

Also do you accept pull requests ? I have a few items I might be able to help with

**Comment by manigandham** [comment]
It's in the readme: 
> Before running tests, create a parameters.json file under Snowflake.Data.Tests\ directory. In this file, specify username, password and account info that tests will run against. Here is a sample parameters.json file

It's only used for the tests though, you can skip building and running them.

**Comment by manigandham** [comment]
Yes you need a real account to run the tests.

**Comment by rjpaddock** [comment]
I'm slowly getting how to set this up...

Another question ... Where do I set this up in the snowflake UI or SQL Command ? "SNOWFLAKE_TEST_ACCOUNT": "TESTACCOUNT", 

I created the db, warehouse, role and schema. This one is eluding me

**Comment by rjpaddock** [comment]
OK got all my config issues sorted!
Yet another pesky question...

I'm getting a lot of failures now like the following:

Cannot perform CREATE TABLE. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.

Did I miss a step ?

**Comment by ikudjoi** [comment]
If I recall right the tests assume that the database is created already. So ensure that you have specified a database in parameters.json (key SNOWFLAKE_TEST_DATABASE) and that it's created and accessible by the user you use in the tests.

There is also an open issue related to the unit tests of the connector project. I have addressed them in my PR but it hasn't been accepted yet.
https://github.com/snowflakedb/snowflake-connector-net/issues/77

Running tests will not work at all if you are not using the default host at AWS zone us-west-1.

**Comment by howryu** [comment]
I will merge #78
