### ISSUE TITLE
strongly name .NET driver artifacts

### ISSUE THREAD

**Issue by NeilP-global** [snowflakedb/snowflake-connector-net#102]
The net46 version of the DLL currently on nuget (1.0.6) is not strongly named. 

Is it possible to update/provide a dll that is strongly named? This would allow the dll to be registered on the machine, allowing it to be used with processes such as SSIS.

Please see:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/156a01c3-565e-4d8d-83d9-50ae712972b0/failure-adding-assembly-to-the-cache-attempt-to-install-an-assembly-without-a-strong-name?forum=netfxsetup

**Comment by howryu** [comment]
@NeilP-global Just to clarify, so a strong named dll means that we need to sign the package with private key and distribute the public key? 
Is this the correct reference? https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies

**Comment by NeilP-global** [comment]
@howryu I believe so. Some environments require signed DLLs.

**Comment by DeltaGit** [comment]
Hi, are there any updates regarding this?

We're trying out the latest version from NuGet (2.0.3) and we're basically unable to use it in our environment because the dll doesn't have a strong name.

Are there any plans on strong-naming the assembly?

**Comment by DeltaGit** [comment]
Any news on this?

**Comment by RichardSchulte** [comment]
Yes I'm also very interested having it signed 
I was able to GAC it. by doing the following http://www.geekzilla.co.uk/ViewCE64BEF3-51A6-4F1C-90C9-6A76B015C9FB.htm

I also would like to use it with SSIS
Has anyone got it to work with SSIS? - I can get Snowflake.Net to be an option in SSIS connection list but error on connection properties  "Failed to load the the registered .Net Framework Data Provider"

**Comment by sfc-gh-pverma** [comment]
@sfc-gh-triage-snowpark-ecosystem-dl  Customer is using .NET driver and are trying to use Snowflake.Data to access snowflake data and getting below error
 
`Could not load file or assembly 'Snowflake.Data, Version=2.1.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)`

Can you please suggest what needs to be done here to unblock customer?

**Comment by frankschmitt** [comment]
Is there any progress regarding this? We want to use the Snowflake driver with TIBCO Spotfire, but we need a strongly named Assembly for this.

**Comment by sfc-gh-dszmolka** [comment]
there is progress yes, but a timeline estimation is something which i'm unable to attach at this point of time. Will keep this thread updated.

**Comment by frankschmitt** [comment]
@sfc-gh-dszmolka That's good news, thanks for the quick response & the effort you're putting into this.

**Comment by sfc-gh-dszmolka** [comment]
PR open at https://github.com/snowflakedb/snowflake-connector-net/pull/956

**Comment by sfc-gh-dszmolka** [comment]
PR merged and will be available with the next driver release which will probably happen towards the end of June 2024. We expecting a major version change.

**Comment by sfc-gh-dszmolka** [comment]
Will update this thread once more information is known about the next upcoming major release of the .NET driver which will carry this fix.

**Comment by sfc-gh-dszmolka** [comment]
after such a long wait, support for strongly naming the artifacts is now released with Snowflake .NET driver version v4.0.0 in July 2024 and moving forward.
Thank you everyone for bearing with us !
