### ISSUE TITLE
SNOW-1657238: SnowflakeDbCommand.ExecuteNonQueryAsync returns incorrect count; only includes from first row when loading from Stage

### ISSUE THREAD

**Issue by brtubb-patagonia** [snowflakedb/snowflake-connector-net#1023]
1. What version of .NET driver are you using?
Reproduced on 4.1.0 and 4.0.0.
   
2. What operating system and processor architecture are you using?
Windows 11 on Microsoft Dev Box in Azure (reports Intel Xeon Platinum 8370C)
Also seeing issue in Azure App Service Plan (I1V2 tier. Not sure what that runs on)
   
3. What version of .NET framework are you using?
.Net 8.0
   
4. What did you do?
Repro steps (all running in a console app) -

 - Put >1 file in blob storage folder (stage source)
 - Create temp table in Snowflake
 - Load into temp table using COPY INTO from the stage folder (using ExecuteNonQueryAsync)
 - Retrieve record count from ExecuteNonQueryAsync return value
 - Note the incorrect record count

5. What did you expect to see?
I'm expecting to see the number of rows loaded to the table from stage. Instead it's returning only the number of records from the first file loaded.

![image](https://github.com/user-attachments/assets/cce2a737-b997-43e9-9fd7-6fb737988d14) 

The record count returned is only for the first record and doesn't properly aggregate the results.

![image](https://github.com/user-attachments/assets/3777bb2e-fe99-47da-9b54-dd1e899920c9)

Debugging the code a bit, it looks like there is an issue reading the resultset returned. It doesn't think there is more than one result.
![image](https://github.com/user-attachments/assets/c0226b52-42d8-401d-b61f-339085c33b2d)

When digging into the ResultSetUtil.CalculateUpdateCount, which looks to handle the nuances of record counts for various operations, it is aware of both rows, as evident in the private _currentChunk variable.
![image](https://github.com/user-attachments/assets/35ea98cf-781c-4521-94f3-a7240f78c98e)

6. Can you set logging to DEBUG and collect the logs?

Debug logs attached.
[snowflake_dotnet4.log](https://github.com/user-attachments/files/16934021/snowflake_dotnet4.log)

7. What is your Snowflake account identifier, if any? (Optional)

**Comment by sfc-gh-dszmolka** [comment]
hi and thanks for raising this issue with us, especially for providing so much details on it! we'll take a look.

**Comment by sfc-gh-dszmolka** [comment]
PR in review: https://github.com/snowflakedb/snowflake-connector-net/pull/1044

**Comment by sfc-gh-dszmolka** [comment]
fix is merged and will be part of the next driver release

**Comment by sfc-gh-dszmolka** [comment]
released with Snowflake .NET driver v4.2.0 in October 2024 release cycle
