### ISSUE TITLE
SNOW-1663445: How to reduce number of login/session requests? 

### ISSUE THREAD

**Issue by myshon** [snowflakedb/snowflake-connector-net#1025]
# It's question about General Usage, not Feature request. 

## What is the current behavior?
I use snowflake connector in Asp.Net WebAPI service in low-traffic environment (12k GET queries within a week. Peak 200 requests per hour). 

See metrics: 
![image](https://github.com/user-attachments/assets/fbc0a62b-b6f3-4a93-8a27-0907ae8bf1b8)

I see that apart from `query-request` provider  executes additional heavy requests  `login-request` and `session` under the hood. 

Is it possible to reduce number of these requests somehow? 
Is there any variable in connection string that I can manipulate number of sessions/login (now I use default connection string settings and login via password) 

 The connection class is used more-less this way - is it correct? 
```csharp
        await using var conn = await _connectionProvider.GetConnection();
        await conn.OpenAsync();
        await using var cmd = CreateCommand(conn, databaseName);
        await using var reader = await cmd.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            yield return ReadData(reader);
        }

        await conn.CloseAsync();
```

## What is the desired behavior?

I would like 
1) reduce number of additional heavy requests  `login-request` and `session`
2) optimise and adjust warehouse configuration to have lower latency on `query-request` 

## Configuration
1. Default connection string settings (login password, min connection pool = 2, max connection pool = 10).
2. Warehouse "x-small" with multi-cluster disabled 
3. Standard Tables are used
4. Traffic 12k GET queries within a week. Peak 200 requests per hour.

**Comment by myshon** [comment]
@sfc-gh-dszmolka Thanks for very comprehensive answer! 
I know that login-request is required :) I accept that it takes a few seconds. The point was to reduce number of login requests (which is almost 10% of all API calls) in order reduce total latency. 

I will be investigating [CLIENT_SESSION_KEEP_ALIVE](https://github.com/snowflakedb/snowflake-connector-net/blob/master/doc/Connecting.md?rgh-link-date=2024-09-18T07%3A21%3A20Z) and `insecuremode=true`

**Comment by myshon** [comment]
First, I checked parameter  [CLIENT_SESSION_KEEP_ALIVE](https://github.com/snowflakedb/snowflake-connector-net/blob/master/doc/Connecting.md?rgh-link-date=2024-09-18T07%3A21%3A20Z)=true. 

![image](https://github.com/user-attachments/assets/0f984e31-525b-4055-b2e0-9c5c91df4fbb)


Still I had 
- login requests high average latency ~5seconds
- query latency P90 ~3seconds
- number of all login requests about still about 10-20% comparing to query requests
- additional heartbeat requests

 

Second, I added INSECUREMODE=true (for testing purpose). 

![image](https://github.com/user-attachments/assets/b4bac4a7-3564-4cf0-8240-efc7072e4ba2)

Then suddenly latency dropped! 
- login requests P90  to ~200ms
- query latency P90 to ~100ms


It looks that we have an issue with cert validation.

**Comment by sfc-gh-dszmolka** [comment]
indeed if the average latency of login-request drops so drastically by not changing anything just turning certificate validation off, then indeed the focus of the investigation should be this aread.
Did you have a chance perhaps to look at [Validating certificates](https://github.com/snowflakedb/snowflake-connector-net/blob/master/doc/CertficateValidation.md) here and see if all of the CRL endpoints are reachable from the same host/network where you run the .NET driver ?

It's a very frequent issue that these endpoints are blocked on a particular network, operating on port 80. (although absolutely no customer or useful data is transmitted on the wire unencrypted, everything is already public information like the CRL itself. Could you please make sure they are reachable? Perhaps not, and driver spends the most of the time waiting for the response. Most optimal would be of course if it would be possible to write a small application which can use the same .NET driver on the same host, downloading the CRLs from within the C# app. 

Another (although very rare) possibility is that CRL endpoints are reachable, CRL can be downloaded, but driver has issues parsing the content e.g. to a bad openssl installation on the host. 

I also saw you created 00848448 with Snowflake Support, so I would like to ask whether you prefer continuing working with us in a more private and regulated environment (Support case) , or here ? My colleague already requested the DEBUG level logs from you, which usually best shared privately and not the world :) without sanitizing it, of course. Having the verbose logs usually provides very useful information but if you could do the aforementioned connectivity tests, that should be also helpful.

**Comment by myshon** [comment]
Before I received your answer, I had created support ticket 00848448 to to get a faster answer 😄 

Honestly, I prefer Github due to interface and usability. However I would like to avoid putting all logs in public here. 

I added endpoint in order to check cert reachability. Here is the result: 
```

[
  {
    "url": "http://crl.pki.goog/gsr1/gsr1.crl",
    "status": "OK"
  },
  {
    "url": "http://crl3.digicert.com/DigiCertGlobalG2TLSRSASHA2562020CA1-1.crl",
    "status": "OK"
  },
  {
    "url": "http://crl3.digicert.com/DigiCertGlobalRootG2.crl",
    "status": "OK"
  }
]
```

**Comment by sfc-gh-dszmolka** [comment]
thank you for checking. All 3 endpoints you listed here, seem to be reachable on HTTP. 
It's fully understandable you'd prefer not to share logs here - please share them with my colleague so we could look further. The area of focus should still remain the CRL checking procedure in my opinion, given that significant performance improvement could be achieved just by turning CRL checking off and changing nothing else. 

I'm now closing down this issue to keep the efforts in one thread, which will be the support case (due to the sensitiveness of data needed, the logs).
