### ISSUE TITLE
DateTime is parsed wrong when querying from time or timestamp column with precision less than nanoseconds (9)

### ISSUE THREAD

**Issue by ikudjoi** [snowflakedb/snowflake-connector-net#103]
### Issue description
When querying DateTime or DateTimeOffset from Snowflake database columns, whose type is time or timestamp with precision less than 9, the result DateTime is parsed wrong, only seconds are parsed right. 

### Example code
I will push pull request tomorrow European time.

### Configuration
*Driver version:* 1.0.6
*Dotnet framework and version:* .net standard 2.0
*Server version:* E.g. 3.12.0
*Client OS:* Windows 10

**Comment by ikudjoi** [comment]
You could close this after accepting my PR but I'm about to file another date parsing related bug in a moment.

**Comment by howryu** [comment]
Close the issue since I have merged it in #110
