### ISSUE TITLE
SNOW-1735958: Snowflake TIME column is returned as .Net DateTime and not .Net TimeOnly

### ISSUE THREAD

**Issue by LeivErik** [snowflakedb/snowflake-connector-net#1040]
So I have a table 
```
create TESTTABLE1 (
	GUID VARCHAR(50) NOT NULL,	
	DATE_ONLY DATE,
	TIME_ONLY TIME(9),
	primary key (GUID)
);
```

I am reading from this table returning a DataReader:

```
using  var conn = new SnowflakeDbConnection(connectionString);
await conn.OpenAsync(cancellationToken);
using var cmd = con.CreateCommand();   
cmd.CommandText = "select GUID, DATE_ONLY, TIME_ONLY from TESTTABLE1
using var dataReader = await cmd.ExecuteReaderAsync(cancellationToken);
```

The datareader returns the TIME_ONLY column as DateTime.

I would expect it as .net TimeOnly.

So if I insert read data to a  new table, insert fails w/e.g. error:
`Error: Time '1970-01-01T01:59:11.4040000+01:00' is not recognized SqlState: 22007, VendorCode: 100108, QueryId: 01b7ae5b-0000-bcba-0000-811900033022`

Additional Information:
- Snowflake.Data 4.1.0 package
- .Net 8
- Win.10

**Comment by sfc-gh-dszmolka** [comment]
hi, and thanks for raising this. This is sorta expected, please see [the documentation](https://github.com/snowflakedb/snowflake-connector-net/blob/master/doc/QueryingData.md#run-a-query-and-read-data) about `TIME` Snowflake-type returned as `System.DateTime`. I'll check further.

**Comment by sfc-gh-dstempniak** [comment]
`TimeOnly` was introduced in .NET 6. It is not available in .NET Framework or .NET Standard 2.0.

**Comment by sfc-gh-dszmolka** [comment]
i'm going to close this as it's the expected and documented behaviour, but if you require further help please do comment and i can reopen
