### ISSUE TITLE
Connection Issue,Fails to open the connection

### ISSUE THREAD

**Issue by JhonPaul1234** [snowflakedb/snowflake-connector-net#11]
Have you tried yourself trying to add this snowflake connector with Nuget or by adding library in your project .......?

The Unit tests are working fine with my credentials as well,But in the api or in the web project it fails when tried to open the connection 

Any alternate ways to connect this ,we are about to develop a project with the snowflake db,but got stuck with the first step

**Comment by howryu** [comment]
@JhonPaul1234 Do you mean web application ? To be honest, I did not try it out. I will investigate why asap. BTW, can you provide me with your visual studio version and .net framework version?

**Comment by JhonPaul1234** [comment]
I'm using visual studio 2015 and 4.6 .Net framework

Can you resolve it asap....

**Comment by howryu** [comment]
Yeah btw someone reported same as you did. So I will definitely resolve it asap.

**Comment by JhonPaul1234** [comment]
Thanks for that buddy, we actually signed a project with this, it would be helpful if you fix it

**Comment by howryu** [comment]
@JhonPaul1234  Can you try again? I just released Snowflake.Data 0.3.0 https://www.nuget.org/packages/Snowflake.Data/ 
This supports the .net core 2.0. It might resolve your problem.

**Comment by howryu** [comment]
Closed since no response.
