### ISSUE TITLE
1.0.7.0 view displays unspecified currency symbol '¤' instead of '$'

### ISSUE THREAD

**Issue by e8-ZhixinYang** [snowflakedb/snowflake-connector-net#119]
1.0.7.0 view displays unspecified currency symbol '¤' instead of '$'

**Comment by howryu** [comment]
Can you give a little more detail? Does this happened in 1.0.6? Do you have a simple reproduceable case?

**Comment by ZhixinY** [comment]
Yes, it also happened at 1.0.6.0.
When I replace the DLL from version 1.0.1.0 to version 1.0.6.0 in the system, the CultureInfo(System.Threading.Thread.CurrentThread.CurrentCulture) in the system will be set to NULL after each SQL run.

**Comment by rhatmonkey** [comment]
We just ran into a similar problem.  We're using sales.ToString("{0:C0}"); in our views which was working fine until we added this snowflake adapter (we were using CData's but switched to this one), now our $ are showing ¤.  We managed to fix it with setting the culture to the uiculture in the view but we shouldn't have to do this.

**Comment by ZhixinY** [comment]
Similarly, we have written the FormatCurrency method ourselves.
`public static string FormatCurrency(object Value, int NumDigitsAfterDecimal, bool UseParensForNegativeNumbers, bool GroupDigits)
        {
            if (Value == null)
            {
                return "";
            }

            string ReturnValue = Value.ToString();

            if (IsNumeric(ReturnValue))
            {
                string currencyFormatString = "'$'n;";

                if (UseParensForNegativeNumbers)
                {
                    currencyFormatString += "('$'n)";
                }
                else
                {
                    currencyFormatString += "-'$'n";
                }

                string NumberFormatString;
                if (GroupDigits)
                {
                    NumberFormatString = "#,##0";
                }
                else
                {
                    NumberFormatString = "0";
                }

                if (NumDigitsAfterDecimal == -1)
                {
                    NumDigitsAfterDecimal = 2;
                }
                if (NumDigitsAfterDecimal > 0)
                {
                    NumberFormatString = NumberFormatString + "." + new string('0', NumDigitsAfterDecimal);
                }
                currencyFormatString = currencyFormatString.Replace("n", NumberFormatString);

                ReturnValue = decimal.Parse(ReturnValue).ToString(currencyFormatString);
            }

            return ReturnValue;
        }`

**Comment by ZhixinY** [comment]
Similarly, we have written the FormatCurrency method ourselves.
`public static string FormatCurrency(object Value, int NumDigitsAfterDecimal, bool UseParensForNegativeNumbers, bool GroupDigits)
        {
            if (Value == null)
            {
                return "";
            }

            string ReturnValue = Value.ToString();

            if (IsNumeric(ReturnValue))
            {
                string currencyFormatString = "'$'n;";

                if (UseParensForNegativeNumbers)
                {
                    currencyFormatString += "('$'n)";
                }
                else
                {
                    currencyFormatString += "-'$'n";
                }

                string NumberFormatString;
                if (GroupDigits)
                {
                    NumberFormatString = "#,##0";
                }
                else
                {
                    NumberFormatString = "0";
                }

                if (NumDigitsAfterDecimal == -1)
                {
                    NumDigitsAfterDecimal = 2;
                }
                if (NumDigitsAfterDecimal > 0)
                {
                    NumberFormatString = NumberFormatString + "." + new string('0', NumDigitsAfterDecimal);
                }
                currencyFormatString = currencyFormatString.Replace("n", NumberFormatString);

                ReturnValue = decimal.Parse(ReturnValue).ToString(currencyFormatString);
            }

            return ReturnValue;
        }`

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
