### ISSUE TITLE
SQL Parameterize Query binding

### ISSUE THREAD

**Issue by rpatterson32** [snowflakedb/snowflake-connector-net#127]
### Issue description
Tried binding parameter to do string interpolation in dynamic query e.g. "Select * from Table where id = @id". However, when I ran the code it returned a not implemented exception.

### Example code
using (IDbConnection conn = new SnowflakeDbConnection())
{
    conn.ConnectionString = connectionString;
    conn.Open();

    IDbCommand cmd = conn.CreateCommand();
    cmd.CommandText = "select * from t where id = (?)";  
    IDataReader reader = cmd.ExecuteReader();

    var p1 = cmd.CreateParameter();
    p1.ParameterName = "1";
    p1.Value = 10;
    p1.DbType = DbType.Int32;
    cmd.Parameters.Add(p1);
                
    while(reader.Read())
    {
        Console.WriteLine(reader.GetString(0));
    }
    
    conn.Close();
}

### Error log
Not implemented exception

### Configuration
*Driver version:*
1.0.4

*Dotnet framework and version:* E.g. .net framework 4.5.2 or .net standard 2.0
.net core 2.2

*Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```
Version 3.23.1
*Client OS:* E.g. Debian 8.1 (Jessie), Windows 10
Windows 10

**Comment by rpatterson32** [comment]
If it is in fact not supported at this time can you give me a date of when you plan to release this update?

**Comment by manigandham** [comment]
You're adding the parameter after already executing the query.

Move the `cmd.ExecuteReader()` statement.

**Comment by rpatterson32** [comment]
I thought I tried that but will try it again and let you know. Thanks for your speedy reply

**Comment by rpatterson32** [comment]
Just for clarity it should be the below correct: 

IDbCommand cmd = conn.CreateCommand();
cmd.CommandText = "select * from t where id = (?)";  

var p1 = cmd.CreateParameter();
p1.ParameterName = "1";
p1.Value = 10;
p1.DbType = DbType.Int32;
cmd.Parameters.Add(p1);


IDataReader reader = cmd.ExecuteReader();            
while(reader.Read())
{
    Console.WriteLine(reader.GetString(0));
}

conn.Close();

**Comment by rpatterson32** [comment]
Tried it, it gave me the exception "The method or operation is not implemented." when I stepped into the reader,Read()

**Comment by rpatterson32** [comment]
More details on the exception: error CS1503: Argument 1: cannot convert from 'System.Data.IDataReader' to 'System.Collections.IEnumerable'

**Comment by manigandham** [comment]
That code should work fine. Are you using the latest driver version?

You should add a full sample project here so the error can be reproduced.

**Comment by rpatterson32** [comment]
Sorry bro, I got it to work thanks. The data I was testing with was removed from the db so there were no rows coming back and it through the not implemented error. Testing with values with data and it works perfect :) Thanks!
