### ISSUE TITLE
Support for connection pooling

### ISSUE THREAD

**Issue by extremeandy** [snowflakedb/snowflake-connector-net#149]
### Issue description
In my project, we have a need to ensure instant availability of open Snowflake connections:
1. We want to make sure that when someone hits our APIs, we already have an open connection ready to go.
2. We want to re-use connections that are already open and make them available for re-use for a certain amount of time.

I've written a `ConnectionPool` to provide this functionality. It actively maintains a minimum set of open connections, and if the minimum is exceeded, will hold on to open connections for a time before letting them go if they're unused.

Would there be any interest in making this functionality part of this project? If so, please let me know and I will raise a PR. Otherwise, I may create a separate Nuget package.

**Comment by ChTimTsubasa** [comment]
We are interested in having connection pooling, even though its side effect is not clear to us.

**Comment by extremeandy** [comment]
I've got a repo up for a resource pool that can be used in conjunction with Snowflake. There's example code on how to create a connection pool for Snowflake.

https://github.com/extremeandy/AsyncResourcePool

**Comment by sfc-gh-dszmolka** [comment]
thank you for submitting this issue and apologies for the long wait. the driver supports connection pooling for a while now since the issue submission (#455 ) so marking this one as closed.
