### ISSUE TITLE
CS0006: Metadata file 'Snowflake.Data' could not be found when used in Azure Functions v1

### ISSUE THREAD

**Issue by borysl** [snowflakedb/snowflake-connector-net#151]
### Issue description
I am creating Azure Functions v1 by using csx script and Snowflake
Expected that after
```
> dotnet add package Snowflake.Data
```
I can use the assembly Snowflake
Actual: the package is successfully installed: info : Die PackageReference für das Paket "Snowflake.Data", Version 1.0.12, wurde in der Datei ... aktualisiert
but in the run time the following error is received:
```
run.csx(7,1): error CS0006: Metadata file 'Snowflake.Data' could not be found
```
### Example code
```cs
#r "Snowflake.Data"
```

### Error log
```
run.csx(7,1): error CS0006: Metadata file 'Snowflake.Data' could not be found
```

### Configuration
*Driver version: 1.0.12*

*Dotnet framework and version:* .net core 2.2

*Server version:* 3.30.2
*Client OS:* Windows 10

**Comment by Janatbek** [comment]
https://ninocrudele.com/error-cs0006-metadata-file-dll-could-not-be-found
you might already found an answer but this might be helpful.

**Comment by ChTimTsubasa** [comment]
@borysl  Does @Janatbek 's suggestion fix your issue?

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
