### ISSUE TITLE
Please update Newtonsoft and Log4Net dependancies

### ISSUE THREAD

**Issue by VantageKR** [snowflakedb/snowflake-connector-net#152]
Please update to latest Newtonsoft and Log4Net. Thanks! ### Issue description
Tell us what should happen and what happens instead

### Example code
```cs
If possible, please enter some example code here to reproduce the issue.
```

### Error log
```
If you have an error log, please paste it here.
```
There is an example in READMD.md file showing you how to enable logging.

### Configuration
*Driver version:*

*Dotnet framework and version:* E.g. .net framework 4.5.2 or .net standard 2.0

*Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```

*Client OS:* E.g. Debian 8.1 (Jessie), Windows 10

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
