### ISSUE TITLE
IDataReader.Read() does not terminate

### ISSUE THREAD

**Issue by VantageKR** [snowflakedb/snowflake-connector-net#153]
### Issue description
When calling IDataReader's Read() method, when everything has been read, should return false.
This was the behaviour up until the recent package update - now it does not terminate and blocks on the .Read() call.

                 

### Example code
```csharp
IDataReader reader = cmd.ExecuteReader();
                DataTable data = new DataTable();
                data.Load(reader);  // does not terminate
```

or...

```csharp
IDataReader reader = cmd.ExecuteReader();
                DataTable data = new DataTable();
                //data.Load(reader);
                    DataTable schemaTable = reader.GetSchemaTable();
                    foreach (DataRow row in schemaTable.Rows)
                    {
                        string colName = row.Field<string>("ColumnName");
                        Type t = row.Field<Type>("DataType");
                        data.Columns.Add(colName, t);
                    }
                    while (reader.Read())
                    {
                        var newRow = data.Rows.Add();
                        foreach (DataColumn col in data.Columns)
                        {
                            newRow[col.ColumnName] = reader[col.ColumnName];
                        }
                    }                
```
### Error log
No actual errors, but the log terminates with this:
```
 INFO 32 Snowflake.Data.Core.SFResultSetMetaData - Found colun name IDENTITY_CYCLE under index 40

 INFO 32 Snowflake.Data.Core.SFResultSetMetaData - Found colun name COMMENT under index 41

 INFO 32 Snowflake.Data.Core.SFResultSet - Get next chunk from chunk downloader

 INFO 23 Snowflake.Data.Core.SFBlockingChunkDownloaderV3 - NextChunkToConsume: 0, NextChunkToDownload: 1


```

### Configuration
*Driver version:*
Version:  1.0.12
*Dotnet framework and version:* E.g. .net framework 4.5.2 or .net standard 2.0
.Net 4.6.2
*Server version:* E.g. 1.90.1
3.32.1 

*Client OS:* E.g. Debian 8.1 (Jessie), Windows 10
Windows 10

**Comment by VantageKR** [comment]
This problem is not present in version 1.0.5 but this seems like a very old version compared to the latest?
What is the risk of running version 1.0.5 and not the latest stable please?
What changed from version 1.0.5 that might have an effect on this usage pattern, involving DataTable, DataRow and DataReader?

**Comment by ChTimTsubasa** [comment]
@VantageKR Can you try to Set the SFConfiguration.ChunkDownloaderVersion to 1 and see if there is still this error?

**Comment by stephen-jessiman** [comment]
I just ran into this today. It is blocking at the following line in SFResultSet.cs:Next().
```
IResultChunk nextChunk = Task.Run(async() => await _chunkDownloader.GetNextChunkAsync()).Result;
```

I can confirm that setting ChunkDownloaderVersion to 1 fixed the issue for me.

**Comment by VantageKR** [comment]
@stephen-jessiman, please can you share how to set the ChunkDownloader to version 1, and some context code where this should be done. On which class instance is this setting? My solution up until now was to downgrade the Nuget package to a version that probably use version 1, but this is not great since there are many versions after the one I'm using. Thanks!

**Comment by stegus64** [comment]
To select the old ChunkDownloader you can use the following code in the startup of your application:

`            Snowflake.Data.Configuration.SFConfiguration.Instance().ChunkDownloaderVersion = 1;
`

If it is an asp.net application you can for example add this to Application_Start() in Global.asax

I can confirm that using SFBlockingChunkDownloaderV3 from an asp.net application causes a deadlock in SFResultSet.cs:Next() when trying to read more than one chunk. It seems to work fine with ChunkDownloaderVersion = 1.

**Comment by VantageKR** [comment]
Thanks much @stegus64. For the moment I cannot find the right place to put it in due to the particular framework I'm using, but I assume it would be fine to wrap it in a method call that establishes the connection? I.e. probably no harm in setting it each time a connection will be made? Thanks again.

**Comment by stephen-jessiman** [comment]
@VantageKR Yes, should be harmless to set it each time you will connect.

**Comment by stegus64** [comment]
I have spent some time trying to understand this problem. 

This is another instance of an async deadlock, much like #140 

To avoid these kinds of deadlocks any await in a library that can be called from a synchronous method must always use ConfigureAwait(false)

The immediate cause of this deadlock is the following code from HttpUtil.cs:73

`                        response = await base.SendAsync(requestMessage, childCts == null ? 
                            cancellationToken : childCts.Token);
`

A corrected code should look like this:

`                        response = await base.SendAsync(requestMessage, childCts == null ? 
                            cancellationToken : childCts.Token).ConfigureAwait(false);
`

This code gets called from SFBlockingChunkDownloaderV3.DownloadChunkAsync which is called from the syncronous constructor SFBlockingChunkDownloaderV3()

It is very difficult to find out exactly where a call to ConfigureAwait(false) is misssing, so I recommend that you add ConfigureAwait(false) to all sites that use await.

This is recommended in this article: https://devblogs.microsoft.com/pfxteam/should-i-expose-synchronous-wrappers-for-asynchronous-methods/

> In the case of async/await, this typically means making sure that any awaits inside of the asynchronous implementation you’re calling are using ConfigureAwait(false) on all await points; this will prevent the await from trying to marshal back to the current SynchronizationContext. As a library implementer, it’s a best practice to always use ConfigureAwait(false) on all of your awaits, unless you have a specific reason not to; this is good not only to help avoid these kinds of deadlock problems, but also for performance, as it avoids unnecessary marshaling costs. 

To make it easier to find these kinds of problems during testing you might want to add unit tests that use a constrained synchronization context.

You could for example use DedicatedThreadSynchronisationContext from https://stackoverflow.com/questions/40343572/simulate-async-deadlock-in-a-console-application

With this class you could add a unit test like this to SFDbCommandIT:

`        [Test]
        public void TestSimpleLargeResultSetCtx()
        {
            var ctx = new DedicatedThreadSynchronisationContext();
            ctx.Send(_ => TestSimpleLargeResultSet(), null);
        }
`

TestSimpleLargeResultSetCtx will deadlock just like in the original issue.

After adding ConfigureAwait(false) to all await points, it will work fine.

It might be a good idea to make sure that all sync entry points to the library are called from similar unit tests.
