### ISSUE TITLE
ALTER SESSION SET CLIENT_PREFETCH_THREADS = 1 does not work

### ISSUE THREAD

**Issue by stegus64** [snowflakedb/snowflake-connector-net#162]
### Issue description
When using ALTER SESSION SET CLIENT_PREFETCH_THREADS = 1 you get a runtime error in SFBlockingChunkDownloaderV3

### Example code
```cs
        [Test]
        public void ReadWithOneThread()
        {
            using (IDbConnection conn = new SnowflakeDbConnection())
            {
                conn.ConnectionString = ConnectionString;
                conn.Open();

                IDbCommand cmd = conn.CreateCommand();
                cmd.CommandText = "ALTER SESSION SET CLIENT_PREFETCH_THREADS = 1;";
                cmd.ExecuteNonQuery();

                cmd.CommandText = "select seq4(), uniform(1, 10, 42) from table(generator(rowcount => 1000000)) v";

                IDataReader reader = cmd.ExecuteReader();

                int rowcount = 0;
                while (reader.Read())
                {
                    rowcount++;
                }

                conn.Close();
            }
        }
```

Setting PREFETCH_THREADS to 1 can be important to minimize memory usage of the driver.

### Configuration
*Client version:* 1.0.13

*Dotnet framework and version:* .net standard 2.0

*Server version:* 3.38.1

*Client OS:* Windows 10

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
