### ISSUE TITLE
Bind Parameter Code Example includes DataReader

### ISSUE THREAD

**Issue by timkracht** [snowflakedb/snowflake-connector-net#171]
### Issue description
Readme file appears to have incorrect code in Bind Parameter example 
https://github.com/snowflakedb/snowflake-connector-net#bind-parameter

### Example code
```cs
IDataReader reader = cmd.ExecuteReader();
```

### Error log
```
If you have an error log, please paste it here.
```
There is an example in READMD.md file showing you how to enable logging.

### Configuration
*Driver version:*

*Dotnet framework and version:* E.g. .net framework 4.5.2 or .net standard 2.0

*Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```

*Client OS:* E.g. Debian 8.1 (Jessie), Windows 10

**Comment by ChTimTsubasa** [comment]
Thank you for reporting this issue. The fix is checked in.
