### ISSUE TITLE
Support for the `Application` property in Connection Strings

### ISSUE THREAD

**Issue by pielegacy** [snowflakedb/snowflake-connector-net#179]
### Issue description

In the JDBC documentation for the Snowflake client, there is reference to a partner application name that can be provided when connecting to Snowflake:

![image](https://user-images.githubusercontent.com/7465061/68268693-5ee9a700-00ab-11ea-9884-d6da6cd4bf19.png)

I don't believe that in the .NET Driver this logic is implemented, only as I can't find any reference to it in the source code.

Is this feature coming to the .NET Client at any point? Only as we would like to support this in our integration with the product.

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
