### ISSUE TITLE
NullReferenceError with DbCommand created before opening Connection 

### ISSUE THREAD

**Issue by ThijsKoot** [snowflakedb/snowflake-connector-net#180]
### Issue description
When a DbCommand is created from a connection before the connection has been opened a first time, executing the DbCommand results in a NullReferenceException. This is because the SnowflakeDbCommand-constructor assigns the value of the sfSession-property of SnowflakeDbConnection to itself. The problem here is that sfSession is set when opening the connection, meaning that DbCommand assigns a null value if the connection has never been opened. I'm creating a pull request with a fix for this. 

### Example code
```cs
using (var conn = new SnowflakeDbConnection { ConnectionString = connstr })
{
	var cmd = conn.CreateCommand();
	cmd.CommandText = "select current_version()";
	
	conn.Open();
	
	var result = cmd.ExecuteScalar();
	
	conn.Close();
}
```

### Error log
Not required, problem is in the connector itself.

### Configuration
*Driver version:* 1.1.0

*Dotnet framework and version:* .net standard 2.0

**Comment by ChTimTsubasa** [comment]
Thank you for reporting this issue and submitting a PR.
