### ISSUE TITLE
Get the Query ID after making async call

### ISSUE THREAD

**Issue by onema** [snowflakedb/snowflake-connector-net#182]
### Issue description
This is more a question than an issue:

I'm planning to submit a long-running query, and I would like to retrieve the results later on using the query ID. 

Is it possible to make a query with the connector and immediately get the query ID?

This is similar to [this community question](https://support.snowflake.net/s/question/0D50Z00007DBOk9SAH/asynchronous-requests?t=1576708101837)

### Example code
```cs
using(var conn = new SnowflakeDbConnection()) {
    conn.ConnectionString = connectionStringBuilder.ConnectionString;
    conn.Open();
    var cmd = conn.CreateCommand();
    cmd.CommandText = "select * from foo";
    var task = cmd.ExecuteNonQueryAsync();
    // var queryId = some how get the query id?
    conn.Close();
}
```

### Error log
NA

### Configuration
*Driver version:* Snowflake.Data 1.1.0

*Dotnet framework and version:* .net Core 2.1

*Server version:* 3.55.2

*Client OS:* Mac OS 10.15.2

**Comment by ChTimTsubasa** [comment]
This is not supported by .NET natively as .NET's async API is just hiding the request submission from API user. The driver itself does not generate the id and does not know the query id until it receive the response.
