### ISSUE TITLE
Feature request - Support for Key-Pair authentication

### ISSUE THREAD

**Issue by imathiesonpwx** [snowflakedb/snowflake-connector-net#183]
### Issue description
Connector doesn't currently support key-pair authentication which would be a preferred access pattern, similar to the Python Connector.

Would be great to have similar functionality in the .NET driver.

**Comment by salviri** [comment]
any updates on this one?

**Comment by imathiesonpwx** [comment]
wondering if there were any updates on this? I'm assuming the Jira label is a positive sign :)

**Comment by skubo-afl** [comment]
Please share any updates. This would be a very valuable feature for me as well.

**Comment by dazinator** [comment]
We've used the java connector for this reason. The .net connector could really use this.

**Comment by sfc-gh-dszmolka** [comment]
thank you for submitting this issue and apologies for the long period without response. the recent versions of the connector already support keypair authentication for a while now (#263 ) so marking this one as closed.
