### ISSUE TITLE
Bind variable ? not set.

### ISSUE THREAD

**Issue by sandeepkumarkhatri** [snowflakedb/snowflake-connector-net#184]
### Issue description

I am trying to insert different records using single insert and parameter value set to SnowflakeDbParameterCollection and then trying this

INSERT INTO "PUBLIC"."STES"
(
   "Fname","Lname"
)
VALUES 
(
   ?,?
)

but i am getting error "Bind variable ? not set."

### Error log

Snowflake.Data.Client.SnowflakeDbException

Stacktrace:    at Snowflake.Data.Core.SFStatement.BuildResultSet(QueryExecResponse response, CancellationToken cancellationToken)
   at Snowflake.Data.Core.SFStatement.Execute(Int32 timeout, String sql, Dictionary`2 bindings, Boolean describeOnly)
   at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteInternal(Boolean describeOnly)
   at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteNonQuery()

*Dotnet framework and version:* .net core 3.0

*Server version:4.2.2
```

*Client OS:* Windows 10

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
