### ISSUE TITLE
SNOW-146011: Task was Cancel

### ISSUE THREAD

**Issue by sanjeevsinh** [snowflakedb/snowflake-connector-net#193]
Hi,

My Query from snowflake returns more than 2 lakh records, While reading the records, Its downloading few records and after that it is throwing Task was canceled error message.

However, When I am trying to debug it, Sometimes its running fine and sometimes its giving error.

is there any fix for this issue?

Thanks & Regards
Sanjeev Sinha

**Comment by ZhixinY** [comment]
I also encountered the same error.

When the Snowflake connection idle time exceeds 120s, you should reacquire it.

I did not find the parameter to set the idle time.

**Comment by difei-z** [comment]
Hi Sanjeev,

Do you see what error code and message were on the cancelled task?

My guess is that the task hit the default 1 hour timeout. This timeout can be extended to up to 24 hours by setting USER_TASK_TIMEOUT_MS on the task or schema or higher levels.

**Comment by difei-z** [comment]
Hi ZhixinY,

Did you encounter a connection timeout issue inside a TASK? I don’t think that should ever occur so please confirm..

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
