### ISSUE TITLE
Dispose should rollback transaction if not committed

### ISSUE THREAD

**Issue by howryu** [snowflakedb/snowflake-connector-net#20]
The SnowflakeDbTransaction does not properly Rollback a transaction upon dispose, I'm not sure where the official guidelines for extending DbTransaction are but the expected behavior is that the protected virtual Dispose method is overridden to Rollback the transaction upon Dispose if the transaction was not committed.

**Comment by ikudjoi** [comment]
Have you any plans on this and #64? I think that calling dispose should roll back open transactions and at least close connection.
