### ISSUE TITLE
SNOW-164194: Connect to Snowflake using .NET driver

### ISSUE THREAD

**Issue by SarekaAvinash** [snowflakedb/snowflake-connector-net#210]
### Issue description
As per the official documentation [LINK](https://github.com/snowflakedb/snowflake-connector-net)
it was stating that we can connect to SnowFlake using VisualStudion2017 only and no other version of VisualStudio won't support it. But I created a .NET Core API using V.S 2019 and tried to connect to Snowflake and succeeded in fetching data. 

My question is like, SnowFlake drivers will support for VS2017, VS2019?

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
