### ISSUE TITLE
SNOW-164216: Allow Snowflake connection parameters like CaBundleFile

### ISSUE THREAD

**Issue by jjjain** [snowflakedb/snowflake-connector-net#211]
### Issue description
The current .net connector version doesn't have a way to specify a CaBundleFile. Can it be added?

https://docs.snowflake.com/en/user-guide/odbc-parameters.html#configuration-parameters

### Example code

If you pass CaBundleFile in connection string, we get a warning 

{ string connectionString = "scheme=https;host=snowflakecomputing.com;port=443;account=XXX.us-east-1;role=XXX;db=;schema=XX;warehouse=XXX;user=XXX;password=XXX!"; conn.ConnectionString = connectionString; conn.Open();

### Error log
logs:  2020-06-01 14:55:21,743 [1] WARN Snowflake.Data.Core.SFSessionProperties - Property CABUNDLEFILE not found ignored. System.ArgumentException: Requested value 'CABUNDLEFILE' was not found. at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult) at Snowflake.Data.Core.SFSessionProperties.parseConnectionString(String connectionString, SecureString password) 2020-06-01 14:55:22,851 [8] WARN Snowflake.Data.Core.HttpUtil+RetryHandler - Error occurred during request, retrying... System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure. at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult) at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
There is an example in READMD.md file showing you how to enable logging.

### Configuration
*Driver version:*
<package id="Snowflake.Data" version="1.1.2" targetFramework="net46" /> 

*Dotnet framework and version:* E.g. .net framework 4.5.2 or .net standard 2.0

*Server version:4.18.0
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```

*Client OS:*  Windows 7

**Comment by sfc-gh-hchaturvedi** [comment]
Hey @jjjain for .NET driver we don’t provide a CABundle File parameter as the driver extracts the certificates from the underlying OS (Windows). For the same reason we don't package the CABundle with the driver either.
