### ISSUE TITLE
SNOW-165479: Blocking thread on retry handler

### ISSUE THREAD

**Issue by pcchannz** [snowflakedb/snowflake-connector-net#213]
https://github.com/snowflakedb/snowflake-connector-net/blob/3adccf292e8e582a9c56cbbfb039fba7a826807c/Snowflake.Data/Core/HttpUtil.cs#L207

Replace with asynchronous wait:
await Task.Delay(backOffInSec * 1000);

I observed that during heavy load, the waiting time on retry handler could add up.

Prior updating the line, 35% of my application threads were spent on synchronous sleep.
![image](https://user-images.githubusercontent.com/40587526/83988607-d829df00-a997-11ea-8970-e786cf70a426.png)

After updating the line, it was around 8.5%
![image](https://user-images.githubusercontent.com/40587526/83988659-027b9c80-a998-11ea-94ab-768d6d6b7f7c.png)

Thank you!

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
