### ISSUE TITLE
SNOW-165746: Add support for CloseAsync

### ISSUE THREAD

**Issue by pcchannz** [snowflakedb/snowflake-connector-net#215]
**Issue:**

Blocking thread on dbconnection close during heavy load could add up. By implementing closeasync on top of propose change https://github.com/snowflakedb/snowflake-connector-net/issues/213, I could reduce 8% of my application blocking thread down to 0.84. 

![image](https://user-images.githubusercontent.com/40587526/84095977-d2de9a00-aa54-11ea-9b61-0129b465498d.png)

**Proposal by adding CloseAsync support**

https://github.com/snowflakedb/snowflake-connector-net/blob/3adccf292e8e582a9c56cbbfb039fba7a826807c/Snowflake.Data/Client/SnowflakeDbConnection.cs#L88

public async Task CloseAsync(CancellationToken cancellationToken)
{

            logger.Debug("Close Connection Async.");

            if (_connectionState != ConnectionState.Closed && SfSession != null)
            {
                await SfSession.closeAsync(cancellationToken);
                _connectionState = ConnectionState.Closed;
            }

            _connectionState = ConnectionState.Closed;
}

https://github.com/snowflakedb/snowflake-connector-net/blob/3adccf292e8e582a9c56cbbfb039fba7a826807c/Snowflake.Data/Core/SFSession.cs#L150

internal async Task closeAsync(CancellationToken cancellationToken)
        {

            var queryParams = new Dictionary<string, string>();
            queryParams[RestParams.SF_QUERY_SESSION_DELETE] = "true";
            queryParams[RestParams.SF_QUERY_REQUEST_ID] = Guid.NewGuid().ToString();
            queryParams[RestParams.SF_QUERY_REQUEST_GUID] = Guid.NewGuid().ToString();

            SFRestRequest closeSessionRequest = new SFRestRequest
            {
                Url = BuildUri(RestPath.SF_SESSION_PATH, queryParams),
                authorizationToken = string.Format(SF_AUTHORIZATION_SNOWFLAKE_FMT, sessionToken)
            };

            var response = await restRequester.PostAsync<CloseResponse>(closeSessionRequest, cancellationToken);
            if (!response.success)
            {
                logger.Debug($"Failed to delete session, error ignored. Code: {response.code} Message: {response.message}");
            }
        }

**Comment by sfc-gh-kterada** [comment]
@pcchannz, #337 is merged and is available in our .NET 2.x.x Connectors starting with v[2.0.4](https://github.com/snowflakedb/snowflake-connector-net/releases/tag/v2.0.4).
