### ISSUE TITLE
SNOW-168795: Multiple select statement in one api call for .net driver

### ISSUE THREAD

**Issue by dsilejbdebt** [snowflakedb/snowflake-connector-net#217]
### Issue description
currently it is not supported i believe, however will there be any support in recent times

### Configuration
*Driver version:* snowflake.data 1.1.2

**Comment by sfc-gh-dszmolka** [comment]
thank you for raising this issue and apologies for the lack of responses. during the time passed, it is already implemented (with #464 ) and should be available with recent driver versions. closing this item.
