### ISSUE TITLE
Snowflake driver changes current culture to Invariant

### ISSUE THREAD

**Issue by BillSytin** [snowflakedb/snowflake-connector-net#219]
### Issue description
Snowflake driver changes current culture to Invariant.
Applications often depend on the current thread culture, and it could be harmful and unexpected.

### Example code
https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data/Core/SFDataConverter.cs
```cs
internal SFDataConverter()
        {
            Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
        }
```

**Comment by clegendre** [comment]
What about the status of this issue and the respective PR ?
This is blocking us for deploying our application.

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
