### ISSUE TITLE
SNOW-172987: Consider changing the result set behavior of COPY and MULTI_INSERT statement types

### ISSUE THREAD

**Issue by wildgordo** [snowflakedb/snowflake-connector-net#221]
### Issue description
Newer versions of the driver include special handling in ResultSetUtil.CalculateUpdateCount for MULTI_INSERT and COPY statements that call ResultSet.Next() to read information about the results. These internal calls to Next() increment the row counter past the first record, which prevents the client from accessing the first row of results using standard techniques. This is a breaking change from earlier versions of the driver, which did not advance the result set before returning it to the caller. If the driver needs to grab the first row of results, consider decrementing the count back before the previous row (e.g. -1) 

### Example code
```cs
using (var cnn = new SnowflakeDbConnection())
{
    cnn.ConnectionString = "myconnectioninfo";
    cnn.Open();

    using (var cmd = new SnowflakeDbCommand(cnn))
    {
        cmd.CommandText = "COPY INTO mytable FROM @mystage/myfile.csv FILE_FORMAT = (TYPE = CSV)";

        using (var rdr = cmd.ExecuteReader())
        {
            while (rdr.Read())
            {
                // Will never get here
            }
        }
    }
}
```

### Error log
```
If you have an error log, please paste it here.
```
There is an example in READMD.md file showing you how to enable logging.

### Configuration
*Driver version:*
v1.1.2
*Dotnet framework and version:* E.g. .net framework 4.5.2 or .net standard 2.0
4.6.1
*Server version:* E.g. 1.90.1
4.22.3
*Client OS:* E.g. Debian 8.1 (Jessie), Windows 10
Windows 10

**Comment by akrock** [comment]
@wildgordo I actually noticed the same thing when I last updated the copy of the driver that we use...

I patched this in my copy but had not gotten around to creating a PR for this or some of the other enhancements I made...

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
