### ISSUE TITLE
SNOW-179128: SnowflakeDbConnection Serializable

### ISSUE THREAD

**Issue by agianakas** [snowflakedb/snowflake-connector-net#225]
### Issue description
Deep clone an object error.
Please add SerializableAttribute to the SnowflakeDbConnection class.

### Example code
https://docs.microsoft.com/en-us/dotnet/api/system.serializableattribute?redirectedfrom=MSDN&view=netcore-3.1

### Error log
```
If you have an error log, please paste it here.
```
There is an example in READMD.md file showing you how to enable logging.

### Configuration
*Driver version:*

*Dotnet framework and version:* E.g. .net framework 4.5.2 or .net standard 2.0

*Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```

*Client OS:* E.g. Debian 8.1 (Jessie), Windows 10

**Comment by akrock** [comment]
@agianakas Why would you need to have a `SnowflakeDbConnection` be serializable?

Looking at the `SqlConnection` provided by `System.Data.SqlClient` it does not have a `[Serializable]` attribute (as I would expect).

**Comment by agianakas** [comment]
you are right.  I'm sorry.  I wanted to deep clone, but even the underlying object does not support.  The reason is to be able to open a new instance of an object (without needed new connection, because it would start with the same connection.  The user can then change if needed.  But saving the time of second connect by using the original cloned.  And should the user change the original instance it would not change the second.).  I ended up just wrapping the uses of the connection to then create the second if it is nothing.
