### ISSUE TITLE
SNOW-188325: No way to get QueryId

### ISSUE THREAD

**Issue by acosta32** [snowflakedb/snowflake-connector-net#230]
How to get QueryId after executing a query?

I can see it's on the source code but not returned anywhere.

**Comment by fixer-m** [comment]
@acosta32 Just run `select last_query_id();`. Documentation: https://docs.snowflake.com/en/sql-reference/functions/last_query_id.html

**Comment by acosta32** [comment]
That is one more roundtrip to database.
 Ended up forking and returning the queryid to the caller.

**Comment by fixer-m** [comment]
@acosta32,
> That is one more roundtrip to database. 

Yes. If you care about roundtrips I can suggest you to try [my own SF client library](https://github.com/fixer-m/snowflake-db-net-client). 
It re-uses SF session which reduces roundtrips to SF by 2-3 times. 
And it has an option to return `QueryId`.

**Comment by sfc-gh-kterada** [comment]
@acosta32, the latest version of the .NET connector (v2.0.8) now exposes a GetQueryID method via SnowflakeDbDataReader (see PR #381 for details).
