### ISSUE TITLE
SNOW-189192: Use serilog instead of log4net

### ISSUE THREAD

**Issue by moravas** [snowflakedb/snowflake-connector-net#231]
Hi,

I would like to use serilog for logging instead of log4net in my project that also depends on snowflake-connector-net too. Is it possible to inject it? Maybe, is there an example code? Thank you

**Comment by RyanGrange** [comment]
If the Microsoft.Extensions.Logging interfaces were used there's plugins for both serilog and log4net and the implementer would be able to decide which logging mechanism they want to use.

**Comment by dazinator** [comment]
+1 Microsoft.Extensions.Logging is the way to go.

**Comment by dazinator** [comment]
Just checking - has this been done? Looking at the project readme it still says log4net is used: https://github.com/snowflakedb/snowflake-connector-net#logging

**Comment by agilenut** [comment]
Yes. Please use Microsoft.Extensions.Logging so that you are consistent with all other modern .net libs and provide the flexibility for the consumer to choose their logging implementation of choice.

**Comment by sfc-gh-dszmolka** [comment]
looks duplicate of #204
