### ISSUE TITLE
SNOW-197712: Why are we setting global settings inside each httpclient creation?  

### ISSUE THREAD

**Issue by mhunting** [snowflakedb/snowflake-connector-net#233]
https://github.com/snowflakedb/snowflake-connector-net/blob/21f2d01a2add057ed5d19130d9a485b7289f5ff8/Snowflake.Data/Core/HttpUtil.cs#L43

I believe this is a global setting and affects more than just your library behavior.
https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.defaultconnectionlimit?view=netcore-3.1

**Comment by shawnjones253** [comment]
same with the other `ServicePointManager` stuff https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data/Core/HttpUtil.cs#L59

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
