### ISSUE TITLE
SNOW-198221: AllowDBNull Property not being set properly when using FillSchema.

### ISSUE THREAD

**Issue by WATYF** [snowflakedb/snowflake-connector-net#234]
### Issue description
When I run SnowflakeDbDataAdapter.FillSchema on a DataTable, it does not properly set the AllowDBNull property of each DataColumn in the DataTable. Many columns that are setup to allow NULLs in the database still have an AllowDBNull value of False after running FillSchema. This wasn't happening on the previous database that I ran this same code against (Hadoop using ADO.NET Odbc objects). This issue is inconsistent. Some fields have their AllowDBNull property set properly, but others do not. I'm not sure what causes it to sometimes work. Most of the fields that do work are FLOAT fields which are being SUMed in the SQL query.

EDIT: I discovered that this is due to a particular Function in my SQL statement (IFNULL). For some reason, using this Function on a field causes its Null? info to be lost. For example, running FillSchema on the following statement will properly set the AllowDBNull Property of the Item DataColumn in the DataTable to True:

SELECT item_number AS Item FROM inventory

But running FillSchema on this statement will set the AllowDBNull Property of the Item DataColumn to False.

SELECT IFNULL(item_number,'') AS Item FROM inventory

Incidentally, other Functions do not cause this same issue. This statement also properly sets the AllowDBNull Property:

SELECT TRIM(item_number) AS Item FROM inventory

### Example code
```cs
            Using cmd As SnowflakeDbCommand = connection.CreateCommand
                cmd.CommandText = strSQL
                daDH = New SnowflakeDbDataAdapter(cmd)
                Using dt As New DataTable
                    daDH.FillSchema(dt, SchemaType.Source)
                End Using
            End Using
```

### Configuration
```
*Driver version: 1.1.2.0

*Dotnet framework and version: .net framework 4.6

*Server version: 4.31.2

*Client OS: Windows 10
```

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
