### ISSUE TITLE
SNOW-219900: Potentially dangerous ROLLBACK statement for transaction destructor

### ISSUE THREAD

**Issue by EvaldasSakinis** [snowflakedb/snowflake-connector-net#252]
### Issue description
We encountered an issue while using the transaction from this .Net driver. We accidentally missed a ``using`` statement when we created a transaction which led us to this specific code within the ``SnowflakeDbTransaction`` class. It seems that the destructor method of this class will always call a ROLLBACK statement regardless if there are any uncommitted changes of not, which poses several issues:

- If the transaction is handled correctly it will inevitably still do a roundtrip to the database with an unnecessary, which is a performance overhead.

- The dangerous part is that this rollback will run on the GC context which means that if any error occurs, it will bypass any error handling in the application and throw an unhandled global exception. We encountered this when the transaction would get destroyed in the background without using the ``using`` statement, but this might as well be an unfortunate timing of a network issue which will cause the application to shut down without any error handling.

### Example code
```cs
        public override void Rollback()
        {
            logger.Debug("Rollback transaction.");
            using (IDbCommand command = connection.CreateCommand())
            {
                command.CommandText = "ROLLBACK";
                command.ExecuteNonQuery();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposed)
                return;

            // Rollback the uncommitted transaction when the connection is open
            if (connection != null && connection.IsOpen())
            {
                // When there is no uncommitted transaction, Snowflake would just ignore the rollback request;
                this.Rollback();
            }
            disposed = true;

            base.Dispose(disposing);
        }

        ~SnowflakeDbTransaction()
        {
            Dispose(false);
        }
```

### Error log
In our case, the error we got was: "Session no longer exists", which was caused when the connection was closed after the check within the dispose method and right before the rollback statement was executed.

### Configuration
*Driver version:1.1.3*

*Dotnet framework and version:netcoreapp3.1*

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
