### ISSUE TITLE
SNOW-227038: ID of the executed query is not available in the client

### ISSUE THREAD

**Issue by klisa** [snowflakedb/snowflake-connector-net#253]
### Issue description
It would be very helpful to provide access to the ID of the executed query, for logging and diagnostic purposes.

At the time when an SQL query result is about to be returned to the client, in ```SFStatement.BuildResultSet()```, query ID is available through the ```QueryExecResponse``` instance passed as an argument to that method. ```QueryExecResponse``` has the ```data``` property of type ```QueryExecResponseData``` which, in turn, holds the query ID in its ```queryId``` property.

Unfortunately, even though the ```QueryExecResponseData``` instance gets passed further to build ```SFResultSet``` result, inside the created ```SFResultSet``` instance the query ID itself is not persisted anywhere (other parts of ```QueryExecResponseData``` are).

```SFResultSetMetaData``` could be a potential place to store it (```SFBaseResultSet.sfResultSetMetaData```).

Thanks,
Vladimir

**Comment by fixer-m** [comment]
@klisa
Hi! I can suggest you a couple of options here: 
1. Right after your query run `SELECT LAST_QUERY_ID();`. Read [documentation about it](https://docs.snowflake.com/en/sql-reference/functions/last_query_id.html).
2. Use my [REST API client for Snowflake](https://github.com/fixer-m/snowflake-db-net-client) instead. It has `QueryRawResponseAsync()` method which exposes all Snowflake query information, including Query ID.

**Comment by sfc-gh-kterada** [comment]
@klisa, have you reviewed the suggestions provided by @fixer-m above? If so, do you still see a functional gap in the current version of the connector for your use case(s)? If so, could you please provide those details.

**Comment by klisa** [comment]
> @klisa, have you reviewed the suggestions provided by @fixer-m above? If so, do you still see a functional gap in the current version of the connector for your use case(s)? If so, could you please provide those details.

I've moved away from my project since, but calling LAST_QUERY_ID() would probably do the job, albeit at the (unnecessary) cost of an extra call. It would still be preferable to have that information available in the first call, especially because it is already available inside the connector.

@fixer-m's client is definitely an interesting project, especially because it wraps naturally the underlying (and weirdly unofficial) Snowflake REST API. 

Unfortunately, in my project Snowflake is just one of several data sources that are all accessed in a uniform way through IDb* interfaces from System.Data namespace, so a REST API access is out of the picture.

**Comment by sfc-gh-kterada** [comment]
@fkreis, thank you for submitting PR #381. It has been merged and is now available as part of the v2.0.8 GA .NET connector.

**Comment by fkreis** [comment]
That's great, thank you for the update! 😀
I will update to the new version and try it soon.
