### ISSUE TITLE
SNOW-231960: SnowflakeDbDataReader currently does not support GetBytes()

### ISSUE THREAD

**Issue by frankpistorius** [snowflakedb/snowflake-connector-net#254]
### Issue description
Currently, the SnowflakeDbDataReader does not support GetBytes(). 

*Dotnet framework and version:* E.g. .net framework 4.5.2 or .net standard 2.0
,net Framework 4.7.2

**Comment by JustJaw** [comment]
I run into this same issue when I call GetStream()

System.NotImplementedException: The method or operation is not implemented.
   at Snowflake.Data.Client.SnowflakeDbDataReader.GetBytes(Int32 ordinal, Int64 dataOffset, Byte[] buffer, Int32 bufferOffset, Int32 length)
   at System.Data.Common.DbDataReader.GetStream(Int32 ordinal)

**Comment by JustJaw** [comment]
Would something on the snowflake database end that needs to be implemented in order for GetStream() or GetBytes() to work?

**Comment by sfc-gh-abhatnagar** [comment]
Fixed as part of v2.0.1 release
