### ISSUE TITLE
SNOW-239618: Unable to insert or update datetime with null values

### ISSUE THREAD

**Issue by asdhammu** [snowflakedb/snowflake-connector-net#256]
### Issue description
Unable to insert null value for DateTime datatype

### Example code
```cs
var cmd = (SnowflakeDbCommand)conn.CreateCommand();
cmd.CommandText = @" UPDATE TIME_TABLE SET                                
                               last_date_time = ?";
cmd.Parameters.AddRange(new[]
            {                
                 new SnowflakeDbParameter {DbType = DbType.DateTime, Value = val1, ParameterName = "1"},                                
            });
await cmd.ExecuteNonQueryAsync().ConfigureAwait(false);
```

### Error log
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Snowflake.Data
  StackTrace:
   at Snowflake.Data.Client.SnowflakeDbCommand.convertToBindList(List`1 parameters) in Snowflake.Data\Client\SnowflakeDbCommand.cs:line 236

### Configuration
*Driver version:* 1.1.3
*Dotnet framework and version:* netcoreapp3.1

*Client OS:* Windows 10

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
