### ISSUE TITLE
SNOW-268563: Clarification on self-publishing a Snowflake.Data.Unofficial

### ISSUE THREAD

**Issue by rdagumampan** [snowflakedb/snowflake-connector-net#262]
Hi Snowflake Team,

Recently, I have been building an open source schema migration tool that supports Snowflake. Here, I have used this Snowflake.Data connector. The master build failed when I had to use in a self-contained application so I had to make customization (full attributions in all changed and new files included in compliance of Apache v2 license). 

My question is, can I self-publish this as Snowflake.Data.Unofficial? My intent is to make this temporary package while I wait for Snowflake.Data master package becomes fully compatible in .NET Core self-contained app.

Appreciate your advise and you can fine my use case here.
https://www.linkedin.com/pulse/snowflake-dw-schema-versioning-yuniql-first-preview-dagumampan

Br, Rodel

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
