### ISSUE TITLE
SNOW-299620: Snowflake.Data v1.2.0 uses log4net v2.0.11 which throws exception when logging on Non-Windows platforms

### ISSUE THREAD

**Issue by W0GER** [snowflakedb/snowflake-connector-net#279]
We have been using Snowflake.Data v1.1.0 in AWS (Linux-based) with great results, using .NET Core 2.1. 

We upgraded to Snowflake.Data v1.2.0, which includes an update to reference log4net 2.0.11. This caused our logging via log4net quit working; we discovered that log4net v2.0.11  throws an exception when executing on non-windows platforms.

See log4net bug: https://github.com/apache/logging-log4net/pull/69 

Resolution is to update Snowflake.Data to include log4net 2.0.12 which includes a fix for the root problem. 

Long term it would be good to implement https://github.com/snowflakedb/snowflake-connector-net/issues/204 and delegate logging to the hosting application.

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
