### ISSUE TITLE
Support authentication with Okta SSO

### ISSUE THREAD

**Issue by jsnplank** [snowflakedb/snowflake-connector-net#28]
This is the connection string I'm using: "scheme=https;host=snagajob.snowflakecomputing.com;port=443;account=snagajob;user=MYEMAIL@snagajob.com;password=MYPASSWORD;authenticator=https://snagajob.okta.com";

I know the authenticator key may not be currently supported by the .NET driver but it's what we use in different projects that utilize the JDBC driver.  

The error I'm getting when trying to connect is: "Incorrect username or password was specified"

I'm using the same username and password account I use for Okta and I login to the Snowflake web ui through Okta

**Comment by howryu** [comment]
Right. This is not currently supported by .net driver. I will change the issue name and mark this as a feature.

**Comment by howryu** [comment]
I talked this with our PM and we think we can target this at the end of May. Currently I have other projects in my pipeline.

**Comment by celenaf** [comment]
Similar to Okta SSO, will there be support for ADFS coming soon?

**Comment by RobertBest63** [comment]
So does anybody know if this got resolved?  Trying it now with the authenticator token and still getting the error.

**Comment by howryu** [comment]
@RobertBest63 This is scheduled to be done on Q1 of 2019.

**Comment by vinaykumar80** [comment]
@howryu @hkapre : Are we on track to have this feature integrated by end of Q1 0f 2019?

**Comment by abelykh0** [comment]
What about Q2 0f 2019? Any chance?

**Comment by ChTimTsubasa** [comment]
I will be working on this

**Comment by hkapre** [comment]
End of July is the current target.

Targets are always tentative and we may need to push this out for a variety
of reasons. We are trying to pull this in earlier than July but July is a
safer bet for now.

Harsha
