### ISSUE TITLE
SNOW-304019: Code Snippet in readme.md related to Bind Parameter has incorrect syntax

### ISSUE THREAD

**Issue by nickQuant** [snowflakedb/snowflake-connector-net#282]
### Issue description
The line below is wrong:
`cmd.CommandText = "insert into t values (?),(?),(?)";`

The correct syntax is:
`cmd.CommandText = "insert into t values (?,?,?)";`

**Comment by SimbaGithub** [comment]
This line is correct. It is inserting 3 rows in table t.
More details about what the example shows has been added to the documentation.

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
