### ISSUE TITLE
SNOW-308953: SnowflakeDbTransaction transactions - SnowflakeDbConnection type instead of System.Data.Common.DbConnection?

### ISSUE THREAD

**Issue by gojimmypi** [snowflakedb/snowflake-connector-net#284]
### Issue description

I'm working on converting an old friend to Snowflake, the [Microsoft Patterns and Practices SQLHelper](https://github.com/gojimmypi/snowflake-connector-net/blob/master/Snowflake.Data.SQLHelper/Snowflake.Data.SQLHelper.cs) that allows a simpler and more direct syntax such as this `DataSet` from a SQL command:

```cs
string sqlSQL = "SELECT * FROM mytable";
return SnowflakeSqlHelper.ExecuteDataset(connectionString, CommandType.Text, strSQL, sqlParams);
```

(let me know if there's an interest in a PR for [this](https://github.com/gojimmypi/snowflake-connector-net/tree/master/Snowflake.Data.SQLHelper) and optionally the original SQLHelper in [Microsoft.ApplicationBlocks.Data](https://github.com/gojimmypi/snowflake-connector-net/tree/master/Microsoft.ApplicationBlocks.Data))

My question: Should the connection of a `SnowflakeDbTransaction` be of type `SnowflakeDbConnection ` instead of `System.Data.Common.DbConnection` ?

Perhaps this is petty, but it might be a good idea for consistency? I'm happy to fix this and submit a PR for this.

### Example code
```cs
            SnowflakeDbTransaction transaction;
            SnowflakeDbConnection c = transaction.Connection;
```

### Error log
![image](https://user-images.githubusercontent.com/13059545/112663885-90851e80-8e16-11eb-9986-9286d616861d.png)

### Configuration
![image](https://user-images.githubusercontent.com/13059545/112664047-bf02f980-8e16-11eb-8030-966bac5a43ba.png)

*Server version:*  
N/A

*Client OS:* Windows 10, Visual Studio 2019 Enterprise 16.8.5

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
