### ISSUE TITLE
SNOW-330795: Unspecified parameter DbType throws NotImplementedException

### ISSUE THREAD

**Issue by yellowladder** [snowflakedb/snowflake-connector-net#289]
### Issue description
When creating an adding a parameter using CreateParameter() and .Add, if the DbType value is not specified, SFDataConverter throws a NotImplementedException. The tooltip indicates that DbType.String is the default, so I wouldn't expect to need to specify this.

### Example code
```cs
await using var conn = this.snowflakeDbFactory.CreateConnection();
conn.ConnectionString = this.snowflakeConnectionString;

await conn.OpenAsync();
var cmd = conn.CreateCommand();
cmd.CommandText = "SHOW TASKS IN IDENTIFIER(?);";

var namespaceParam = cmd.CreateParameter();
namespaceParam.ParameterName = "1";
namespaceParam.Value = $"{databaseName}.{schemaName}";
// namespaceParam.DbType = DbType.String;
cmd.Parameters.Add(namespaceParam);

var reader = await cmd.ExecuteReaderAsync();
```

### Error log
```
System.NotImplementedException: The method or operation is not implemented.
   at Snowflake.Data.Core.SFDataConverter.csharpTypeValToSfTypeVal(DbType srcType, Object srcVal)
   at Snowflake.Data.Client.SnowflakeDbCommand.convertToBindList(List`1 parameters)
   at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteInternalAsync(CancellationToken cancellationToken, Boolean describeOnly)
   at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
```

### Configuration
*Driver version:* Client 1.2.0

*Dotnet framework and version:* .NET 5.0

*Server version:* 5.9.1

*Client OS:* Windows 10, VS 2019

**Comment by sfc-gh-vreddy** [comment]
@SimbaGithub Can you comment on this

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
