### ISSUE TITLE
SNOW-349375: Connection.open() times out when deployed in AWS

### ISSUE THREAD

**Issue by saroopyabhashyam** [snowflakedb/snowflake-connector-net#301]
### Issue description
I'm using this connector to get data from snowflake in aws lambda. It works locally but throws request timed out when deployed to aws. No other details in exception.

### Example code
  using (SnowflakeDbConnection conn = new SnowflakeDbConnection())
                {
                    conn.ConnectionString = connectionString;
                    conn.Open();
                    DbCommand cmd = conn.CreateCommand();
                    cmd.CommandText = sqlString;
                    DbDataReader reader = await cmd.ExecuteReaderAsync();
                    var dataTable = new DataTable();
                    while (!reader.IsClosed)
                    {
                        dataTable.Load(reader);
                        string jsonString = JsonConvert.SerializeObject(dataTable);
                        List<TEntity> result = JsonConvert.DeserializeObject<List<TEntity>>(jsonString);
                        resultSet.AddRange(result);
                    }
                    conn.Close();
              

### Error log
Task cancelled exception.

### Configuration
using .NetCoreapp3.1

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
