### ISSUE TITLE
SNOW-351388: AngleSharp (useless?) dependency

### ISSUE THREAD

**Issue by clegendre** [snowflakedb/snowflake-connector-net#306]
https://github.com/snowflakedb/snowflake-connector-net/blob/1305e806f5ee4e70fc8c9f1f0d6ff4fbf346190c/Snowflake.Data/Snowflake.Data.csproj#L24

Why there is a dependency on AngleSharp 0.15.0? I've checked the code and there is no reference on it.
We are using AngleSharp in our solution, and we don't want to be forced to upgrade to this new version.

Could you please clean up your dependencies?
Thanks you.

**Comment by clegendre** [comment]
Up on this !

**Comment by clegendre** [comment]
Related PR: #368

**Comment by sfc-gh-dszmolka** [comment]
hello and thank you for raising this concerns. also apologies for the long period without response. at least the issue is resolved with more recent driver versions, from 2.0.8 and up this dependency doesn't seem to be included. closing this issue
