### ISSUE TITLE
SNOW-358718: Select(ed) columns don't match what is specified in the query

### ISSUE THREAD

**Issue by vllama** [snowflakedb/snowflake-connector-net#318]
### Issue description

When running a select against information schema, the column names in the DbDataReader do not match what is specified in the query.

It seems to interpret the column names for some reason and CamelCase them . see screenshot of what the reader shows the columns are in the debug.

Where is ProviderType coming from?

![image](https://user-images.githubusercontent.com/43180217/118687362-347ebb00-b805-11eb-9cd9-f1b0dbaf2c83.png)

### Example code
```cs
 var sql = @"SELECT 
COLUMNS.table_schema
, COLUMNS.table_name, COLUMNS.column_name, is_nullable,data_type, numeric_precision, numeric_scale
, case when tbls.table_name is not null then 'TABLE'   when vws.table_name is not null then 'VIEW' else 'UNKNOWN' end as table_type
FROM INFORMATION_SCHEMA.COLUMNS 
left outer join information_schema.tables tbls on tbls.table_name = columns.table_name and tbls.table_schema = columns.table_schema
left outer join information_schema.VIEWS  vws on vws.table_name = columns.table_name and vws.table_schema = columns.table_schema
ORDER BY COLUMNS.table_schema, COLUMNS.table_name,COLUMNS.ORDINAL_POSITION";

            using (var cmd2 = conn.CreateCommand()) {
                cmd2.CommandText = sql;
                cmd2.Transaction = tr;
                var rdr = cmd2.ExecuteReader();

                if (rdr.HasRows) {
                    while (rdr.Read())
                    {
                        //TODO:s add some logic so that we don't fail on a bad table/schema
                        try
                        {
                            string schema_name = rdr.GetString(rdr.GetOrdinal("table_schema")); <--- error here.
...
```

### Error log
```
Column index -1 is out of bound of valid index.

```

There is an example in READMD.md file showing you how to enable logging.

### Configuration
*Driver version: 2.0.0

*Dotnet framework and version:* E.g. .net framework 4.5.2 or .net standard 2.0
.net core 3.1

*Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
5.17.1
```

Windows 10

**Comment by stegus64** [comment]
Exactly where is the debugger screenshot coming from? I am trying to reproduce your problem, but I cannot find anything that looks like your screenshot.

What is really happening is that Snowflake is case sensitive and the column names are converted to upper case in the result set.

If you change your code to rdr.GetOrdinal("TABLE_SCHEMA") it should work as expected.

**Comment by vllama** [comment]
That was it.   I think there is some internal variable that matched my query by accident and I was confused by it.
