### ISSUE TITLE
SNOW-360449: add option to disable retry

### ISSUE THREAD

**Issue by shawnjones253** [snowflakedb/snowflake-connector-net#323]
### Issue description
We'd like the ability to use the connector without automatic retries. These retries hide underlying errors making it hard to calculate observed SLA. Furthermore, they can cause very long delays when a fast fail is preferable. When you add in the fact that threads are blocked during retry (https://github.com/snowflakedb/snowflake-connector-net/issues/213), this can create more problems that it can solve.

### Example code
Please give the client some option to disable the use of the `RetryHandler` here: https://github.com/snowflakedb/snowflake-connector-net/blob/7d68a419c6807f767762bc2c15aceafdee2460e8/Snowflake.Data/Core/HttpUtil.cs#L165

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
