### ISSUE TITLE
SNOW-362501: TIME column returned as System.DateTime instead of System.TimeSpan

### ISSUE THREAD

**Issue by dannystommen** [snowflakedb/snowflake-connector-net#327]
### Issue description
Our Snowflake table contains a column with `TIME` as data type. In c# class contained a `TimeSpan` equivelant. After switching from the ODBC driver to the .NET driver, this suddenly broke. After investigating, it turns out that the .NET driver returns time column as DateTime object.

### Example code
```cs
...
      using var command = connection.CreateCommand();
      command.CommandText = "SELECT time_column FROM my_table";
      using var reader = command.ExecuteReader();
      reader.Read();
      Console.WriteLine(reader[0].GetType()); // -> System.DateTime, expected System.TimeSpan
```

### Configuration
*Driver version:* 2.0.1

*Dotnet framework and version:* .net standard 2.0

*Server version:* 5.20.1
*Client OS:* CentOS & Windows 10

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
