### ISSUE TITLE
How to execute multiple statements in in a single API call?

### ISSUE THREAD

**Issue by MahesRam** [snowflakedb/snowflake-connector-net#33]
My SQL has multiple SQL statements. While using execute reader method I am getting error  {"Multiple SQL statements in a single API call are not supported; use one API call per statement instead."}

**Comment by samrogers226** [comment]
@howryu any update on this?

**Comment by NordinLars** [comment]
@howryu Our company is also interested in this being updated.

**Comment by relloyd** [comment]
+1 from me.

**Comment by howryu** [comment]
Update: server side of multi statement is in progress and JDBC will be the first driver supporting it. Then will come to .NET driver. 

@hkapre is our PM and he will have a better timeline or ETA

**Comment by smtakeda** [comment]
For new feature requests, please reach out the support. We can discuss here but cannot commit it. Thank you.

**Comment by dinesh-procore** [comment]
@howryu Our company is interested in this as well.

**Comment by michaeldunnegan** [comment]
If you're interested in making multiple insert statements, this may help 
https://docs.snowflake.net/manuals/sql-reference/sql/insert-multi-table.html

**Comment by WATYF** [comment]
> Update: server side support of multi statement is in progress and JDBC will be the first driver supporting it. Then will come to .NET driver.
> 
> @hkapre is our PM and he will have a better timeline or ETA

@howryu Is there any update on this. We need to run queries with variables using the .NET driver.

**Comment by michael135** [comment]
We are also interested in multiple SQL statements via python api.

**Comment by bplaats** [comment]
+1 here too,  especially in the native stored procedure api, I could really use it now.   

For python the concurrent futures package is helpful, I used it once

**Comment by benryan2010** [comment]
I'm trying to write a django backend for snowflake and multiple queries is required here since I need to get the last inserted ID for newly inserted records

**Comment by RichieRunner** [comment]
any progress update after 3 years? 😔

**Comment by suman077** [comment]
@howryu is there any update on ODBC driver multiple query support. I am trying to run multiple queries in excel using ODBC snowflake driver connection.

**Comment by pranavq212** [comment]
Any updates on this, for .net core 3.* code works on local debugging & updates it. But on after deploying to AWS lamda it gives error :

@"Message": "Multiple SQL statements in a single API call are not supported; use one API call per statement instead. , StackTrace:    at Snowflake.Data.Core.SFStatement.BuildResultSet(QueryExecResponse response, CancellationToken cancellationToken)\n   at Snowflake.Data.Core.SFStatement.Execute(Int32 timeout, String sql, Dictionary`2 bindings, Boolean describeOnly)\n   at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteInternal(Boolean describeOnly)\n   at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteNonQuery()"

**Comment by amine-mouffok** [comment]
Have you guys tried https://docs.snowflake.com/en/user-guide/python-connector-api.html#execute_string ?

**Comment by lukaszkoziara** [comment]
@amine-mouffok Yes, in our project we actively use `execute_string`, but that method has one disadvantage - lack of possibility to safely pass parameters to query.

**Comment by TiagoACS** [comment]
Hi,
Is there any update on this?
Execution of multiple SQL statements is supported by ODBC and JDBC drivers as well as in Snowflake SQL API. It would be very useful to have this feature in .Net driver too.

/Tiago Silva

**Comment by hans2520** [comment]
+1

**Comment by trofimchuk-t** [comment]
I've found a workaround which is works for me. You just need to wrap multiple statements with the `BEGIN` and `END` commands:
```
BEGIN
    <statement_1>;
    <statement_2>;
END;
```

With this operators I was able to use two `MERGE` commands to upsert parent/child data in one request.

**Comment by WRJE** [comment]
> I've found a workaround which is works for me. You just need to wrap multiple statements with the `BEGIN` and `END` commands:
> 
> ```
> BEGIN
>     <statement_1>;
>     <statement_2>;
> END;
> ```
> 
> With these operators I was able to use two `MERGE` commands to upsert parent/child data in one request.

You got my hopes up for a minute there. That may work with statements, but not with variables, which is what I need.

Any reason why this still hasn't been implemented almost four years later?

**Comment by WRJE** [comment]
> Can you please provide an example @WRJE ?

Any use of a var in a query, which I can do in the Snowflake console but cannot do via the .NET driver.

This example is from Snowflake's documentation:

set (min, max)=(40, 70);
select $min;

It runs fine in the console, but via the .NET driver it produces the "Multiple SQL Statements not supported" error. If I use BEGIN/END, it says "$MIN does not exist".

**Comment by TiagoACS** [comment]
> > Can you please provide an example @WRJE ?
> 
> Any use of a var in a query, which I can do in the Snowflake console but cannot do via the .NET driver.
> 
> This example is from Snowflake's documentation:
> 
> set (min, max)=(40, 70); select $min;
> 
> It runs fine in the console, but via the .NET driver it produces the "Multiple SQL Statements not supported" error. If I use BEGIN/END, it says "$MIN does not exist".

That's because you are using session variables. It would work with "regular" variables:
begin
  let min := 40;
  select :min;
  --return :min;
end;
https://docs.snowflake.com/en/developer-guide/snowflake-scripting/variables.html#declaring-a-variable

Or if you set the session variable before the scripting block:
set (min, max)=(40, 70);
begin
  set min = 10;
  select $min; -- value 10
end;

**Comment by WRJE** [comment]
> That's because you are using session variables. It would work with "regular" variables: begin let min := 40; select :min; --return :min; end; https://docs.snowflake.com/en/developer-guide/snowflake-scripting/variables.html#declaring-a-variable
> 
> Or if you set the session variable before the scripting block: set (min, max)=(40, 70); begin set min = 10; select $min; -- value 10 end;

OK, using the link you provided I was able to work up a sample of querying a value to use as a variable (which is what I needed this for):

BEGIN
    LET cust VARCHAR := (SELECT TOP 1 Customer FROM Customers ORDER BY Sales DESC);
    RETURN cust;
END;

So it looks like switching to "regular" variables (not sure the difference there either) allows me to at least setup a simple var and RETURN it. The problem is that I need these vars to be used in other SELECT statements. For example:

BEGIN
    LET cust VARCHAR := (SELECT TOP 1 Customer FROM Customers ORDER BY Sales DESC);
    SELECT * FROM Orders WHERE Customer = :cust;
END;

This runs without error in the .NET driver, but returns an empty anonymous block. No data. Even something as simple as 'SELECT :cust;" does the same. Can you use these vars in queries, or is that only for session variables?

**Comment by TiagoACS** [comment]
Yes, you can. 

begin
  let min := 40;
  create or replace table MY_TABLE(MY_COL number) as select :min;
end;

SELECT * FROM MY_TABLE;

**Comment by WRJE** [comment]
> Yes, you can.
> 
> begin let min := 40; create or replace table MY_TABLE(MY_COL number) as select :min; end;
> 
> SELECT * FROM MY_TABLE;

That isn't working for me. As-is, it produces the "multiple API calls" error because it sees the begin/end and SELECT as separate calls. If I put the SELECT inside the begin/end, it produces the same empty anonymous block, presumably because the SELECT in the CREATE statement is generating the same output as a stand-alone SELECT statement (which is an empty block).

**Comment by bcikili** [comment]
our company is also having issues and interested in any computation-wise solutions for this! hope to see some progress

**Comment by brettpostin** [comment]
I'm unable to get the BEGIN/END workaround to work with parameters.

The following results in a "SQL compilation error: error line 4 at position 42 invalid identifier 'GROUPCODE'":
```
var sql = $@"
BEGIN
    USE DATABASE {targetDatabase}; 
    CALL PIPELINES.ADD_CLIENTS_TO_ONBOARD(:groupCode, :clientCode, ',');
END";
```

Removing the BEGIN/END results in the original "Multiple SQL statements in a single API call are not supported; use one API call per statement instead." error:
```
var sql = $@"
    USE DATABASE {targetDatabase}; 
    CALL PIPELINES.ADD_CLIENTS_TO_ONBOARD(:groupCode, :clientCode, ',');
";
```

This line on it's own works fine:

```
var sql = $@"
    CALL PIPELINES.ADD_CLIENTS_TO_ONBOARD(:groupCode, :clientCode, ',');
";
```

Any ideas or suggestions?

**Comment by sfc-gh-hchaturvedi** [comment]
Multi Statement support for .NET has been addressed in the .NET release in November 2022 - For more details please refer to .NET release notes - https://community.snowflake.com/s/article/Dot-NET-Driver-Release-Notes

**Comment by sfc-gh-ext-simba-dl** [comment]
Add parameter "MULTI_STATEMENT_COUNT" to 3, which means the query contains 3 statements. set to 0 is no limit (but not recommended, because sql injection).

**Comment by dss010101** [comment]
does this work for python as well? seeing same frustrating issue with multi-statement queries and using set varaibles

**Comment by dss010101** [comment]
> 

were you able to figure this out..the SELECT part?

**Comment by paulverbeke** [comment]
multi statement (batch) support has been added but only without bind parameters ?
