### ISSUE TITLE
Unable to install 1.0.0 nuget package to vs2015

### ISSUE THREAD

**Issue by gogowater** [snowflakedb/snowflake-connector-net#34]
Hi, I am having trouble install this nuget package v1.0.0 to the project.   I updated all the dependencies prior the installation and it will only work with v.0.3.0.  I found an article from nuget page, perhaps that could help solving the problem.

Nuget issue: https://github.com/NuGet/Home/issues/4639

Logs:
Attempting to gather dependency information for package 'Snowflake.Data.1.0.0' with respect to project 'ProjectTest', targeting '.NETFramework,Version=v4.6'
Gathering dependency information took 14.09 sec
Attempting to resolve dependencies for package 'Snowflake.Data.1.0.0' with DependencyBehavior 'Lowest'
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'Snowflake.Data 0.3.0'
Resolving dependency information took 0 ms
Resolving actions to install package 'Snowflake.Data.1.0.0'
Resolved actions to install package 'Snowflake.Data.1.0.0'
Retrieving package 'Snowflake.Data 1.0.0' from 'nuget.org'.
Removed package 'Snowflake.Data.0.3.0' from 'packages.config'
Successfully uninstalled 'Snowflake.Data.0.3.0' from Insightly.Core.Service
Adding package 'Snowflake.Data.1.0.0' to folder 'C:\Projects\Core.2\packages'
Added package 'Snowflake.Data.1.0.0' to folder 'C:\Projects\Core.2\packages'
Install failed. Rolling back...
Package 'Snowflake.Data.1.0.0 : log4net [2.0.8, ), Newtonsoft.Json [11.0.2, )' does not exist in project 'ProjectTest'
Package 'Snowflake.Data.0.3.0' already exists in folder 'C:\Projects\Core.2\packages'
Added package 'Snowflake.Data.0.3.0' to 'packages.config'
Removing package 'Snowflake.Data.1.0.0 : log4net [2.0.8, ), Newtonsoft.Json [11.0.2, )' from folder 'C:\Projects\Core.2\packages'
Removed package 'Snowflake.Data.1.0.0 : log4net [2.0.8, ), Newtonsoft.Json [11.0.2, )' from folder 'C:\Projects\Core.2\packages'
Executing nuget actions took 2.32 min
Failed to add reference. The package 'Snowflake.Data' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
========== Finished ==========
Time Elapsed: 00:02:36.9216035

**Comment by howryu** [comment]
Fixed in #35 @gogowater We will do another patch release today for 1.0.1
