### ISSUE TITLE
SNOW-399360: Loss of precision when returning float columns.

### ISSUE THREAD

**Issue by Tersa** [snowflakedb/snowflake-connector-net#347]
### Issue description
Tell us what should happen and what happens instead
When a float column is returned the decimal is truncated to 2 decimal places, instead of the longer value that's being returned by the function.

### Configuration
*Driver version:* 1.2.4

*Dotnet framework and version:*  .net framework 4.5.2 

*Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```
5.28.0

*Client OS:* Windows 10

**Comment by sfc-gh-kterada** [comment]
@Tersa, can you please provide a code snippet that is able to reproduce this behavior?

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
