### ISSUE TITLE
SNOW-406892: Package dependency error after updating from 2.0.3 to 2.0.4 with Azure Functions

### ISSUE THREAD

**Issue by GergiH** [snowflakedb/snowflake-connector-net#352]
### Issue description
After we updated the NuGet package for our project from 2.0.3 to 2.0.4 we started to get an error (in the Error log part) when starting to debug the app, and I suspect it's because some of the package dependencies of this package got upgraded in this last version change.

### Error log
```
Azure Functions Core Tools
Core Tools Version:       3.0.3442 Commit hash: 6bfab24b2743f8421475d996402c398d2fe4a9e0  (64-bit)
Function Runtime Version: 3.0.15417.0

[2021-07-27T10:50:13.355Z] Found <path-to-solution>\<project name>.csproj. Using for user secrets file configuration.
[2021-07-27T10:50:20.229Z] A host error has occurred during startup operation '6283687f-b6c0-45b4-8194-0a441ccd0dc8'.
[2021-07-27T10:50:20.239Z] System.Private.CoreLib: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Value cannot be null. (Parameter 'provider')
```
There is an example in READMD.md file showing you how to enable logging.

### Configuration
*Driver version:* 2.0.4

*Dotnet framework and version:* Tried with .NET Core 3.1.16 and .NET 5, neither works

*Client OS:* Windows 10

**Comment by GergiH** [comment]
I just did a test with a plain Web API vs a newly scaffolded Azure Function through Visual Studio, and with the Web API it works fine, but with the Azure Functions we still get this same error.

**Comment by clegendre** [comment]
It also avoid us to upgrade to the latest package...

Seems to be related to the addition of these NuGet packages
```xml    
<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.1" />
<PackageReference Include="Microsoft.Extensions.Http" Version="5.0.0" />
```
I have opened a PR #369 that suggests removing these dependencies by changing how the HttpClient is built.

**Comment by oserdiuk** [comment]
@sfc-gh-kterada Thank you for the response! Do you have any idea how much time it might take?

**Comment by sfc-gh-kterada** [comment]
@oserdiuk PR #369 was approved ENG and merged. The fix is included in the latest GA connector (2.0.8), which is now released. Could you check to see if it addresses the issue raised here? Thank you so much for being so patient, everyone!

**Comment by oserdiuk** [comment]
@sfc-gh-kterada  thank you for the fix! I created a new Azure Function on .NET 5, and I was able to connect to Snowflake. Thank you!

**Comment by sfc-gh-kterada** [comment]
@oserdiuk Thank you for confirming the fix. Glad to hear that the issue raised has been resolved.
