### ISSUE TITLE
Add QUERY_TAG to SFSessionParameter enum please

### ISSUE THREAD

**Issue by sandscap-sc** [snowflakedb/snowflake-connector-net#362]
### Issue description
Please add QUERY_TAG to SFSessionParameter enum

### Example code
```cs
If possible, please enter some example code here to reproduce the issue.
```

### Error log
```
If you have an error log, please paste it here.
```
There is an example in READMD.md file showing you how to enable logging.

### Configuration
*Driver version:*

*Dotnet framework and version:* E.g. .net framework 4.5.2 or .net standard 2.0

*Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```

*Client OS:* E.g. Debian 8.1 (Jessie), Windows 10

**Comment by sfc-gh-hkapre** [comment]
@DarthRinzler Can you provide some detail on the use case you have in mind for this?

**Comment by DarthRinzler** [comment]
> @DarthRinzler Can you provide some detail on the use case you have in mind for this?

We would like to tag queries executed by our automation with meta-data details so that we can do then do analysis within snowflake to see which parts of our system were responsible for which queries, and what state they were in when the queries were executed etc

**Comment by sfc-gh-hkapre** [comment]
Thanks @DarthRinzler. We will evaluate this for Q2 and provide an update once it's confirmed.

**Comment by DarthRinzler** [comment]
Much appreciated @sfc-gh-hkapre

**Comment by astarche** [comment]
@DarthRinzler , you may be able to work around this with `ALTER SESSION`. I.e.,

```csharp
_connection.Open();

var command = _connection.CreateCommand();
command.CommandText = "ALTER SESSION SET QUERY_TAG = \"SOME_TAG\";";
command.ExecuteNonQuery();
```

**Comment by sfc-gh-dszmolka** [comment]
no updates unfortunately but will share if there will be available in the future. 
for query-level tracking, please take a look at the suggestion just above (using `ALTER SESSION`), you can even combine it with the [multi-query statement](https://github.com/snowflakedb/snowflake-connector-net#executing-a-batch-of-sql-statements-multi-statement-support) capability of the driver.

**Comment by sachin-tive** [comment]
@sfc-gh-dszmolka - how would using "ALTER SESSION" work on per query level if snowflake db connection is singleton? Basically, I want to collect info like user who executed the query, which customer this user belongs to etc.

**Comment by sfc-gh-dszmolka** [comment]
PR with the capability in review: https://github.com/snowflakedb/snowflake-connector-net/pull/916

**Comment by sfc-gh-dszmolka** [comment]
PR is now merged and will be part of the upcoming April 2024 release cycle, towards the end of the month

**Comment by sfc-gh-dszmolka** [comment]
quick update: release was postponed to after the Snowflake Summit 2024; which (the Summit) happens 3-6 June so probably the week after that.

**Comment by sfc-gh-dszmolka** [comment]
Will update this thread once more information is known about the next upcoming major release of the .NET driver which will carry this fix.

**Comment by sfc-gh-dszmolka** [comment]
functionality released with .NET driver version v4.0.0 in July 2024
