### ISSUE TITLE
ConnectionStringBuilder improperly quotes PRIVATE_KEY

### ISSUE THREAD

**Issue by ryan-kramer-ab** [snowflakedb/snowflake-connector-net#370]
### Issue description
Either the ConnectionStringBuilder is wrong, or else you need to unquote the private key here https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data/Core/Authenticator/KeyPairAuthenticator.cs#L91

### Example code
```
Dim csb = New Snowflake.Data.Client.SnowflakeDbConnectionStringBuilder()
csb("ACCOUNT") = "blah.foo.aws"
csb("PRIVATE_KEY") = "-----BEGIN ENCRYPTED PRIVATE KEY-----OOPS"
Assert.AreEqual("ACCOUNT=blah.foo.aws;PRIVATE_KEY=-----BEGIN ENCRYPTED PRIVATE KEY-----OOPS", csb.ConnectionString)
```
Result
```
Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException:
'Assert.AreEqual failed.
Expected:<ACCOUNT=blah.foo.aws;PRIVATE_KEY=-----BEGIN ENCRYPTED PRIVATE KEY-----OOPS>.
Actual:  <ACCOUNT=blah.foo.aws;PRIVATE_KEY="-----BEGIN ENCRYPTED PRIVATE KEY-----OOPS">. '
```

### Error log
When you attempt to use the quoted private key, you get this error
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Snowflake.Data
  StackTrace:
   at Snowflake.Data.Core.Authenticator.KeyPairAuthenticator.GenerateJwtToken() in
```

### Configuration
Using latest version from this repository.

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
