### ISSUE TITLE
Unable to connect in .NET Core 3.1 and 5, but working fine in .NET Framework 4.7.2

### ISSUE THREAD

**Issue by ID-GO** [snowflakedb/snowflake-connector-net#371]
### Issue description
Unable to connect in .NET Core 3.1 and 5, but working fine in .NET Framework 4.7.2 - Snowflake.Data 2.0.6

###  
```cs
  using (IDbConnection conn = new SnowflakeDbConnection())
            {
                conn.ConnectionString =  "scheme=https;ACCOUNT=Test;HOST=Test.us-east-1.snowflakecomputing.com;port=443; ROLE=PSR_USER_POC_ROLE;WAREHOUSE=DEMO_WH; USER=PSR_USER; PASSWORD=PSR_USER;DB=UTIL_DB;SCHEMA=PSR_USER_POC";
                conn.Open();

                conn.Close();
            }
```

### Error log
```
 Snowflake.Data.Client.SnowflakeDbException: 'Snowflake Internal Error: Unable to connect. One or more errors occurred. (Request reach its timeout.)'
            
            SnowflakeDbException: Request reach its timeout.
            
            AggregateException: One or more errors occurred. (Request reach its timeout.)

```
There is an example in READMD.md file showing you how to enable logging.

Unable to connect in .NET Core 3.1 and 5, but working fine in .NET Framework 4.7.2
 
Added : Snowflake.Data 2.0.6

**Comment by ID-GO** [comment]
![Version-removebg-preview](https://user-images.githubusercontent.com/10906289/132044455-297bea41-74d2-4492-98b4-82a124de2127.png)
![wORKING-removebg-preview](https://user-images.githubusercontent.com/10906289/132044459-c1e607d0-13b2-459e-b326-aa02de1a5b58.png)
![error-removebg-preview](https://user-images.githubusercontent.com/10906289/132044460-377d0071-5469-4ca3-9cd6-369b225300d7.png)
![Framework-removebg-preview](https://user-images.githubusercontent.com/10906289/132044461-92dd5268-5b4b-4431-befe-189b92448fa7.png)

**Comment by ID-GO** [comment]
Any Update on this.... I have attached the Error Screen Shot.
![PHOTO-2021-09-20-17-54-33](https://user-images.githubusercontent.com/10906289/134034080-4e0f6fd2-c2a0-436d-97fd-d9322fbe1bdb.jpg)
![PHOTO-2021-09-20-17-54-22](https://user-images.githubusercontent.com/10906289/134034085-a7c7f4b2-7969-4b4f-a3ed-034a68d298c3.jpg)
![PHOTO-2021-09-20-17-46-24](https://user-images.githubusercontent.com/10906289/134034087-b0a2b49c-5065-46c1-adda-ab1b0b0df107.jpg)

**Comment by damianbc** [comment]
Hello @sfc-gh-kterada. Is there any progress on this issue? Any forecast?

Thank you very much.

**Comment by jeromesubs** [comment]
I'm facing the same issue using .Net 6 ...
Is there any news, fixes or workarounds?

Thanks

**Comment by jeromesubs** [comment]
That seems to fix the issue:
https://stackoverflow.com/questions/72765189/net-6-c-sharp-getting-timeout-attempting-to-connect-to-snowflake-database

**Comment by sfc-gh-dszmolka** [comment]
hello and thank you for submitting this issue. apologies for the long period without answer. i think there's a little misconfiguration ongoing. per the README.md
```
Connection Property | Required | Comment
-- | -- | --
ACCOUNT | Yes | Your full account name might include additional segments that identify the region and cloud platform where your account is hosted
```

so judging from `HOST=Test.us-east-1.snowflakecomputing.com` , your account name is `Test.us-east-1` and not `Test`.

if you just use `ACCOUNT=Test`, the driver assumes it's in the default region `us-west-2` and therefore uses hostname as `Test.snowflakecomputing.com`. That's not your account name.

So please when specifying `ACCOUNT`,  always use 
* either the regionless notation `ACCOUNT=myorg-myaccountalias`
* OR the account locator, which might or might not include the region and cloud indication. E.g. for AWS US EAST is `ACCOUNT=myaccount.us-east-1`, and for example in Azure Central US it's `ACCOUNT=myaccount.central-us.azure`.
Please see the full list at the [Snowflake documentation for account identifiers](https://docs.snowflake.com/en/user-guide/admin-account-identifier#non-vps-account-locator-formats-by-cloud-platform-and-region) 

this doesn't seem like a client driver bug, marking it closed.
