### ISSUE TITLE
Snowflake.Data 2.0.3 dll is not strong-named assembly

### ISSUE THREAD

**Issue by archgnu** [snowflakedb/snowflake-connector-net#372]
We are using 2.0.3 version from NuGet, but is is not strong-named assembly, and our environment requires signed dlls. so we are currently blocked with this...

Is it possible for you to provide strong-named dll?

reference:
https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named

**Comment by archgnu** [comment]
When can we expect any update regarding this? Are you planning to work on this or could you provide some ETA? Thx

**Comment by sfc-gh-dszmolka** [comment]
going to track this on #102
