### ISSUE TITLE
Strong named assembly

### ISSUE THREAD

**Issue by haman** [snowflakedb/snowflake-connector-net#379]
Could not load file or assembly 'Snowflake.Data, Version=2.0.7.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

Please sign with strong name key "Snowflake.Data.dll"
Thank you

**Comment by MarkWRhodes900** [comment]
Hi all.  Is there any way to progress a fix on this issue?  It is blocking our ability to use the the snowflake connector at all.  Thank you.

**Comment by sfc-gh-kterada** [comment]
@haman @MarkWRhodes900 this behavior has been raised and it is being investigated. I will share updates as they become available. Thank you.

**Comment by Grauenwolf** [comment]
> For the most part, the majority of applications do not need strong-names. Strong-names are left over from previous eras of .NET where [sandboxing](https://en.wikipedia.org/wiki/Sandbox_(computer_security)) needed to differentiate between code that was trusted, versus code that was untrusted. However in recent years, sandboxing via AppDomains, especially to [isolate ASP.NET web applications](https://support.microsoft.com/en-us/help/2698981/asp-net-partial-trust-does-not-guarantee-application-isolation), is no longer guaranteed and is not recommended.

https://github.com/dotnet/runtime/blob/main/docs/project/strong-name-signing.md

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
