### ISSUE TITLE
I want to get searchQueryId that can be used for result_scan

### ISSUE THREAD

**Issue by abhirob85** [snowflakedb/snowflake-connector-net#385]
### Issue description
I want to get searchQueryId for a query which I am executing , That serchQueryId can be used to get cached result set from SnowFlake 

### Example code
want to execute below query after primary query 

select * from table(result_scan('019fc134-0603-504c-0002-c50130e1340b')) WHERE LASTEVENTCUSTODY='USPS';
passing parameter does not work .
If possible, please enter some example code here to reproduce the issue.
using (var conn = new SnowflakeDbConnection())
            {
                try
                {
                    conn.ConnectionString = _connectionString;
                    conn.Open();
                    string finalQuery = query;
                    if (param != null)
                    {
                        finalQuery = query.Format(param);
                    }
                    DataTable dt = new DataTable();
                    SnowflakeDbCommand snowflakeDbCommand = new SnowflakeDbCommand(conn)
                    {
                        CommandText = finalQuery
                    };
                    
                    if (commandTimeout != null)
                        snowflakeDbCommand.CommandTimeout = (int)commandTimeout;
                    SnowflakeDbDataAdapter da = new SnowflakeDbDataAdapter(snowflakeDbCommand);
                    //object searchQueryId = string.Empty;
                    //var queryParam = snowflakeDbCommand.CreateParameter();
                    //queryParam.ParameterName = "SearchQueryId";
                    //queryParam.DbType = System.Data.DbType.String;
                    //queryParam.Direction = ParameterDirection.Output;
                    ////queryParam. = ParameterDirection.InputOutput;
                    //queryParam.Value = searchQueryId;
                    //da.SelectCommand.Parameters.Add(queryParam);
                    da.Fill(dt);
                    var result = dt.ToList<T>();                   
                    conn.Close();
                    return result;
                }
                catch (Exception ex)
                {
                    conn.Close();
                    throw;
                }
            }

### Configuration

*Dotnet framework and version:* E.g. .net 5.0

**Comment by sfc-gh-kterada** [comment]
@abhirob85, the latest version of the .NET connector (v2.0.8) now available exposes a getQueryID() method via SnowflakeDbDataReader (see PR #381). Does that help you get what you need in your application to execute the RESULT_SCAN function?

**Comment by abhirob85** [comment]
Thanks
 let me have a look

**Comment by abhirob85** [comment]
@sfc-gh-kterada I wanted to access the queryId in SnowflakeCommand as per example shared in issue description. Solution does not work for me

**Comment by abhirob85** [comment]
@sfc-gh-kterada can you please review the pull request . That solution works for me .
https://github.com/snowflakedb/snowflake-connector-net/pull/399

**Comment by abhirob85** [comment]
it has been long time this ticket is open . if any one can give me update it would be very helpful .
