### ISSUE TITLE
严重 bug 重复ID

### ISSUE THREAD

**Issue by Stitch-XIN-CHEN** [snowflakedb/snowflake-connector-net#398]
我使用 Jemeter ,100个并发，就会出现 重复ID！！！！
（Sorry,My English is not good.   I use tool   for jemeter, concurrent testing, error occurred ： ID repeat！！！ ）

**Comment by ZhixinY** [comment]
Did you set autoincrement？

e.g.
_create table mytable (amount number autoincrement);_

**Comment by Stitch-XIN-CHEN** [comment]
Thank you response me QQ -maill, I not feedback in time to you, I'm sorry!
No,I don't,So I need snowflake ID, Now question with repeat id，I&nbsp;watch you code is lock exist, Maybe is DI instance create&nbsp;lead to repeat&nbsp;id，
I alread resolve it






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月23日(星期四) 上午9:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [snowflakedb/snowflake-connector-net] 严重 bug 重复ID (Issue #398)





 
Did you set autoincrement？
 
e.g.
 create table mytable (amount number autoincrement);
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
