### ISSUE TITLE
Unable to open connection from AWS Lambda

### ISSUE THREAD

**Issue by gaurravprakash** [snowflakedb/snowflake-connector-net#402]
### Issue description
What should happen - we should be able to open the connection(breaks at conn.Open();)
What happens - Exception is thrown after ~2 minutes

### Example code
```cs
using (IDbConnection conn = new SnowflakeDbConnection())
                {
                    conn.ConnectionString = "scheme=https;ACCOUNT=company_businessunit;HOST=company_businessunit.us-east-1.snowflakecomputing.com;WAREHOUSE=warehousename;USER=username;PASSWORD=password;authenticator=snowflake;";
                    context.Logger.LogLine("trying to open connection.");
                    conn.Open();
                    context.Logger.LogLine("connection open success.");
                    IDbCommand cmd = conn.CreateCommand();
                    cmd.CommandText = query;
                    IDataReader reader = cmd.ExecuteReader();
                    context.Logger.LogLine("Executing command.");
                    while (reader.Read())
                    {
                        context.Logger.LogLine("Reading and printing result.");
                        context.Logger.LogLine(reader.GetString(0));
                    }
                    conn.Close();
                }
```

### Error message 
```
Snowflake Internal Error: Unable to connect. One or more errors occurred. (Request reach its timeout.)
```
### Configuration
*Driver version: 2.0.8, 1.1.0, 1.1.4 

*Dotnet framework and version:* .net core 3.1

*Server version:* 5.44.2

*Client OS:* AWS Lambda x86_64 architecture.

Interestingly, this works just fine when executed on my Windows 10 laptop. Also, another library https://github.com/fixer-m/snowflake-db-net-client/ works just fine on both Windows 10 as well as AWS Lambda.

**Comment by harindaka** [comment]
@gaurravprakash did you resolve this? if so how?

**Comment by gaurravprakash** [comment]
> @gaurravprakash did you resolve this? if so how?

Hi @harindaka I'm using the other library I mentioned in my last comment.

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
