### ISSUE TITLE
Uploading files to SnowFlake 

### ISSUE THREAD

**Issue by malhotrar** [snowflakedb/snowflake-connector-net#405]
Are there any plans to enable uploads of files into SnowFlake from .NET? I was looking through issues, and do not see any work or issue to track this work. 

This feature would be incredibly useful for my organization, as we send and receive data from many clients for the purposes of analytics.

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this request. also apologies for the long period without response. this has been implemented (#415) and available for a while now, so marking this one as closed.
