### ISSUE TITLE
Request to accept pull request for hidden error messages

### ISSUE THREAD

**Issue by Coder3333** [snowflakedb/snowflake-connector-net#408]
I am having a horrible time determining the source of errors when using the .Net Driver.  This is because there is logic in the code that eats exceptions in a way that prevents the calling code from getting the full stack trace.  I created this pull request to correct the issue months ago, but it has not been touched.  What do I need to do to get these minimal changes reviewed, so they can be accepted into the main code branch?  Thank you.

https://github.com/snowflakedb/snowflake-connector-net/pull/387

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
