### ISSUE TITLE
Should I be allowed to pass in null for parameter values?

### ISSUE THREAD

**Issue by Coder3333** [snowflakedb/snowflake-connector-net#409]
### Issue description
When I create a SnowflakeDbParameter and assign the value to null, I get an exception at the point where I execute the command.  If I change the value to DBNull.Value, it works, but it would be nice if the Driver would automatically be able to handle a null, without me having to coerce it every time.

The exception is thrown from convertToBindList at this line:

                    if (parameter.Value.GetType().IsArray &&
                        // byte array and char array will not be treated as array binding
                        parameter.Value.GetType().GetElementType() != typeof(char) && 
                        parameter.Value.GetType().GetElementType() != typeof(byte))

**Comment by Grauenwolf** [comment]
This is a standard design for .NET. All of the ADO.NET database drivers I've worked with expect you to use `DBNull.Value` instead of `null` for parameters.

This design pattern dates back to the COM-based ADO era of the late 1990's.

**Comment by Grauenwolf** [comment]
One could argue `null` means "use the default value for this column/parameter" and `DBNull.Value` means "I actually want a null here".

But I don't know of any database drivers that actually support that, as opposed to simply omitting the parameter/column they want to leave as a default value.

**Comment by Coder3333** [comment]
@Grauenwolf , I can appreciate if a value of null is not expected to work, but the Snowflake driver should throw a more meaningful exception than a generic null reference exception with no explanation of the cause.  If null is not going to be coerced into DbNull.Value, then there should at least be code to look for null and throw an error that spells out the issue, along with the parameter name, before hitting this code that references .Value.  The Sql Server library is nice enough to developers to provide a meaningful exception in this scenario.

**Comment by Grauenwolf** [comment]
Can you paste in the SQL Server error message? That way the dev who picks this up will know what to copy.

**Comment by Coder3333** [comment]
> Can you paste in the SQL Server error message? That way the dev who picks this up will know what to copy.

System.Data.SqlClient.SqlException : The parameterized query '{the first 50 or so characters of the original query are included here}' expects the parameter '@{the parameter name goes here}', which was not supplied.

**Comment by Grauenwolf** [comment]
Uh, yea. Not exactly a great error message. Maybe just supporting nulls isn't such a bad idea afterall.

**Comment by Grauenwolf** [comment]
Looking at the code, I'm more convinced that you're right and `null` should be silently treated as if it were `DBNull.Value`.

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
