### ISSUE TITLE
string.format "%s" in SFSessionProperties.parseConnectionString frames invalid URI

### ISSUE THREAD

**Issue by Ashok19r91d** [snowflakedb/snowflake-connector-net#41]
Formatting string with "%s" in SFSessionProperties.parseConnectionString(string, SecureString) frames invalid uri

````
string hostName = String.Format("%s.snowflakecomputing.com", properties[SFSessionProperties.ACCOUNT]);
````
it should be
````
string hostName = String.Format("{0}.snowflakecomputing.com", properties[SFSessionProperties.ACCOUNT]);
````

**Comment by howryu** [comment]
Thanks for reporting. I will look into it.

**Comment by Ashok19r91d** [comment]
If you make changes as mentioned in my previous post, this will go smooth, also I hope you ignores Region qualifier, which is also takes a part in formation of HOST uri.
