### ISSUE TITLE
GetSchemaTable Error - Column 'IsLong' does not belong to table SchemaTable

### ISSUE THREAD

**Issue by pgr-rick-schulte** [snowflakedb/snowflake-connector-net#414]
### Issue description
Generating Metadata using DataTableReader.GetSchemaTable errors because connector does not include Column IsLong  
  used to check for Binary Data Types for creating DDL for Data extracts 

### Example code

https://docs.microsoft.com/en-us/dotnet/api/system.data.datatablereader.getschematable?view=net-6.0

         foreach (DataRow row in schemaTable.Rows)
            {              
                _DataType = row["DataType"].ToString();
                _ColSize = row["ColumnSize"].ToString();
                _NumericPrecision = row["NumericPrecision"].ToString();
                _NumericScale = row["NumericScale"].ToString();
                _AllowDBNull = ((row["AllowDBNull"].ToString() == "True") ? "NULL" : "NOT NULL");
                // snowflake .net doesnt have isLine
               _IsLong = ((row["IsLong"].ToString() == "True") ? "CLOB" : "NOT CLOB");

error : Creation Error Column 'IsLong' does not belong to table SchemaTable.

### Configuration
*Driver version:* 2.0.9.0 ( also did not work in 2.0.8.0 )

 net framework +4.7.2

*Server version:* 6.1.1

*Client OS: Win 2019 / Win 10

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
