### ISSUE TITLE
Role as part of the connection string is not being recognize.

### ISSUE THREAD

**Issue by eddychansnowflake** [snowflakedb/snowflake-connector-net#42]
It won't change the role from the default to ACCOUNTADMIN even though its defined in the connection string, nor is the database and maybe schema parameters are recognized.

            using (IDbConnection conn = new SnowflakeDbConnection())
            {
                conn.ConnectionString = "account=demo16;host=XXXXX.snowflakecomputing.com;user=eddy;password=XXXXXXX;db=edy;schema=public;role=accountadmin;warehouse=etl" ;
                conn.Open();

                IDbCommand cmd = conn.CreateCommand();
                cmd.CommandText = "select * from edy.public.eddy1;";
                IDataReader reader = cmd.ExecuteReader();

                while (reader.Read())
                {
                    Console.WriteLine(reader.GetString(0));
                }

                conn.Close();
            }

I had to add in these commands to properly switch the context:
                IDbCommand cmd = conn.CreateCommand();
                cmd.CommandText = "use role accountadmin";
                cmd.ExecuteNonQuery();

                conn.CreateCommand();
                cmd.CommandText = "use database edy";
                cmd.ExecuteNonQuery();

                conn.CreateCommand();
                cmd.CommandText = "use schema public";
                cmd.ExecuteNonQuery();

**Comment by howryu** [comment]
Fixed in #45

**Comment by eddychansnowflake** [comment]
Thanks for the quick turnaround, confirmed that this is fixed.
