### ISSUE TITLE
Pass Application Name while querying Snowflake.

### ISSUE THREAD

**Issue by VijrumbhanM** [snowflakedb/snowflake-connector-net#423]
Hi Team,

We are trying to pass our Application name along with the connection string so that it gets recorded on the snowflake.
but it is not recorded, instead it is just showing as .net application. 

Below is the sample connection string that we are using
**"USER=user1;PASSWORD=pwd1;HOST=hostname;PORT=port1; ROLE=role1;WAREHOUSE=warehouse1; DB=adventureworks;SCHEMA=public;ACCOUNT=account;APPLICATION=Appname"**

Adding Application=Appname to the connection in java application in working using jdbc driver, but the same is not working in C#.net app using snowflake.data driver

Framework used : .net framework 4.8

Can you help us in achieving this, how do we tell snow flake our app name.

thanks

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for submitting this issue, and also apologies for the long period without response. this seems to be available for a while now (#366 ) with recent driver versions so marking this one as closed
