### ISSUE TITLE
.NET Core 2.0 / 2.2 are EOL

### ISSUE THREAD

**Issue by Christian-Oleson** [snowflakedb/snowflake-connector-net#433]
### Issue description
Microsoft EOLed .NET Core 2.x at various points in time per the official docs found [here](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core).
For this reason, we should update the refs to be a supported .NET Core version. Core 3.1, 5.0, and 6.0 are all supported

### Example code
N/a

### Error log
N/a

### Configuration
N/a

**Comment by kpawar** [comment]
Any plans of supporting .net core 6.0 on linux ?
