### ISSUE TITLE
New Put feature does not allow absolute paths in Linux and MacOS

### ISSUE THREAD

**Issue by gnikeht** [snowflakedb/snowflake-connector-net#436]
### Issue description
Issue #415 was addressed in a recent push.  It works great, however, if you use an absolute path in either Linux or MacOS the first character '/' is stripped and given path is appended to the the home path.  

According to the Snowflake documentation if the file name is preceded by a: '/' it means to look for the file from root directory and there is no need to remove first character.

### Example
/var/tmp/mypath/file.json

gets converted to /Users/my-user/var/tmp/mypath/file.json

### Code in SFFileTransferAgent.cs
```
else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux) ||
                RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
            {
                location = location.Substring(1);
            }
```

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
