### ISSUE TITLE
SnowflakeDbConnectionStringBuilder doesn't have any properties

### ISSUE THREAD

**Issue by Grauenwolf** [snowflakedb/snowflake-connector-net#440]
The `SnowflakeDbConnectionStringBuilder ` class should have strongly typed properties that match the list of properties listed here:

https://github.com/snowflakedb/snowflake-connector-net#create-a-connection

**Comment by Pansynchro-Admin** [comment]
Just dropped a PR that should implement this, with strongly-typed properties and also a bunch of tooling-friendly goodness just in case you want to hook it up to a UI.

**Comment by Grauenwolf** [comment]
@Pansynchro-Admin I'm going to pull this into the [Tortuga.Data.Snowflake](https://github.com/TortugaResearch/Tortuga.Data.Snowflake) fork. 

I was able to remove the `#if` directives by hosting our own version of the [`AllowNullAttribute`](https://github.com/TortugaResearch/Tortuga.Data.Snowflake/blob/main/Snowflake.Data/Legacy/AllowNullAttribute.cs).  See [PR #9](https://github.com/TortugaResearch/Tortuga.Data.Snowflake/pull/9) for details.

**Comment by Pansynchro-Admin** [comment]
@Grauenwolf Cool project you have there.  Can you post a note here when that's merged and available in Nuget?

**Comment by Grauenwolf** [comment]
@Pansynchro-Admin Will do.

**Comment by Grauenwolf** [comment]
@Pansynchro-Admin Version 3.1.0 has been posted. https://www.nuget.org/packages/Tortuga.Data.Snowflake/3.1.0

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
