### ISSUE TITLE
SnowflakeDbException.ToString hides details

### ISSUE THREAD

**Issue by Coder3333** [snowflakedb/snowflake-connector-net#453]
SnowflakeDbException overrides the base implementation of ToString, which hides details, such as the stack trace.  I have refactored SnowflakeDbException to correct this, as well as making a few other corrections around Exception usage throughout the library.  My pull request is ready for review.

https://github.com/snowflakedb/snowflake-connector-net/pull/452

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
