### ISSUE TITLE
Framework 4.8 Targeting Framework 4.7.2 Won't Connect

### ISSUE THREAD

**Issue by ToadRufus** [snowflakedb/snowflake-connector-net#457]
### Issue description
I am attempting to connect to a snowflake data source in my app (.Net Framework 4.8) and have targeted the 4.7.2 framework in the Package.config file but the connection request fails with a "Request reach its timeout" message.

### Example code
```cs
If possible, please enter some example code here to reproduce the issue.
```

### Error log
```
If you have an error log, please paste it here.
```
There is an example in READMD.md file showing you how to enable logging.

### Configuration
*Driver version:* 2.0.10

*Dotnet framework and version:* .Net Framework 4.8

*Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```

*Client OS:* Windows 10

**Comment by ToniMa1** [comment]
i am currently running into the same issue @ToadRufus any update on this?

**Comment by ToadRufus** [comment]
> i am currently running into the same issue like @ToadRufus any update on this?
> 
> Snowflake.Data version: 2.0.21

No, I abandoned this and connected through ODBC.

**Comment by sfc-gh-dszmolka** [comment]
hi everyone, if you're still hitting this issue with the latest version of the .NET driver, can you please post details related to the reproduction, such as
* environment setup
* minimal viable code which when executed, leads to the issue described in this ticket

i'll then reopen the issue and we can continue troubleshooting.
