### ISSUE TITLE
`Warehouse` property in connection string isn't used when opening connection

### ISSUE THREAD

**Issue by manigandham** [snowflakedb/snowflake-connector-net#46]
It seems #21 was closed prematurely because the `warehouse` property in the connection string is not used in selecting the warehouse when establishing the session. 

This should be automatic if the property is provided by the connection string.

```
Error: No active warehouse selected in the current session.  
Select an active warehouse with the 'use warehouse' command.
 SqlState: 57P03, VendorCode: 606, QueryId: xxx
```

**Comment by howryu** [comment]
Which version of net driver are you using? Latest master should work. I added a test in https://github.com/snowflakedb/snowflake-connector-net/blob/52f4199d13bff225c9ab141e7d47a7ff305aa815/Snowflake.Data.Tests/SFConnectionIT.cs#L177 and it is working.

**Comment by manigandham** [comment]
Ok, can you publish the latest version? Nuget is still showing 1.0.1 from a month ago:
https://www.nuget.org/packages/Snowflake.Data/

The [.csproj](https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data/Snowflake.Data.csproj) file shows version 1.0.1 and the [.nuspec](https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data/Snowflake.Data.nuspec) shows and even older version 0.2.0

Once it's on Nuget, we can test with the latest release, thanks.

**Comment by howryu** [comment]
I will publish it this Thursday. The .nuspec is out of date and is not used. I will remove it.

**Comment by manigandham** [comment]
The new package has not been published, can we please get an update or automate the process? This affects business processes as we use this to interact with Snowflake.

**Comment by howryu** [comment]
I just released .net driver 1.0.2. Please let me know if it works for you or not.

**Comment by manigandham** [comment]
Works now, thanks.
