### ISSUE TITLE
String returned as escaped double quote instead of plain double quote

### ISSUE THREAD

**Issue by wkleong23** [snowflakedb/snowflake-connector-net#467]
### Issue description
If the column value contains double quote ", the driver will sometimes return escaped double quote (\\") instead of just quote itself. This only seems to happen in version 2.0.13, and was ok in 2.0.12. I'm suspecting it is due to the changes in the chunk parser?

If you run the following code, you'll notice that it was ok up to row 190, and start having issue in row 191.
```
190 Sample("86e3LDRttjBdPQ8CZL2G84UEAcmCzumwGiEUqQNafYu1PcaphaTY60Dg3PfNRsA3H4jukOrY6U4HamzedWtUXR4XKXAkLx2VciZJhjOrk4njPeTIJGFpbYrLThlxb8NZRhF9wG3PbkyAQKjLWSzWbSTsd5wd06JV89Sr5glGoaua2Y52Z6G3vYFY061031SElvPWmB6t3mOfXSCczT8ZpWeTNp3dRWG9aN6hN70iQ8VqZS75Qij43HwUBGGbWqUMELK5FXF3Eak5x7H3x1EHbmgFMfHsykpF8Q58Hi9xGs2O3sNaWuLqBxdkoa6JM56nxCl5lYxy40dyLNLxsF1BJYM70pD6VAbYaRFq7h5b5yIHBZuIMkmav6kRoTgUNv5HWxnLi9ABQtO2KB2IcUUB1zdyWeeiBNq8tSYO0rLShCnHS4KgC8uV9IpLBmONWwgucOxEoQnG6UlY6wd0XFLPq8qrBQKhXItJopMK0jXp0ACCPj4dfesG")
191 Sample(\"XyH0iozOEzkja5dOdmUJ4YbcrN0KbDJGCM9inTAiBVIgA9d7LRNm6bL0pGrzLfgGakreT6MbQxtsrkn7chs5txaRXornCG3rC5RslGZvrM3BBbcvaFKSld58jNZ5BKG4ITZ4PCcwadMlMr96uAdOUhis9Cj8yBF2FXs07NNjNAg18GrLhuCcFfltOfbOCS5XZH4ewQLC1KIIsv56roc0Jc6hzp1YHlVyDJElqvv3LagDsnh4CSsYfdcJG6eORaTqNMntpQfAujpAH1wKFJOHcjZOnoweq5GavN6bregeyCgTr6IpGGUL4jkHrS6Vcor9zLwoKy0gPb2KR2IpBqneFkblQAUGoZRpLe9TNIkxEhsZwjm8fz7FnfYuGVU7f2dhDvWGkdlQzwjeRbyBGRjm5GeaA1OltaoPR29tjYI9WHxelv03xYCD6GbATVsEHDveQdHaBWQQYOZOmdVGE9STrNpdVnUzPozo8w4MWJOqVfH3AC3TlVFc\")
```

### Example code
```cs
        await using var cmd = new SnowflakeDbCommand(connection);
        cmd.CommandText = "SELECT seq4(), CONCAT('Sample(\"', randstr(500, random()), '\")') " +
                          "FROM Table(Generator(rowcount => 1000))";

        using var da = new SnowflakeDbDataAdapter(cmd);
        using var ds = new DataSet();
        da.Fill(ds);

        foreach (DataRow row in ds.Tables[0].Rows)
        {
            Console.WriteLine("{0} {1}", row[0], row[1]);
        }
```

### Error log
```
If you have an error log, please paste it here.
```
There is an example in READMD.md file showing you how to enable logging.

### Configuration
*Driver version:* 2.0.13

*Dotnet framework and version:* .Net 6

*Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```

*Client OS:* E.g. Debian 8.1 (Jessie), Windows 10

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
