### ISSUE TITLE
PUT fails to detect compression and maps response to wrong columns

### ISSUE THREAD

**Issue by lovalvob** [snowflakedb/snowflake-connector-net#469]
### Issue description
Put command  has several problems:
*   Put and Get commands should be case insensitive
*   Put and Get commands fail in asynchronous execute with a unclear error (because they are not supported)
*   Put fails to properly determine existing compression, and then fails to properly put the file to the server
*   When a file is 'put', the server response is mapped to incorrect fields in the result.  This renders the result unusable.

### Configuration
*  Driver version: 2.14

*  Dotnet framework and version: .net 6

*  Client OS:  Windows 11

### Note
*  I've fixed these in a fork and will submit a pull request

**Comment by iDevelopForU** [comment]
.

**Comment by lovalvob** [comment]
This sat open for a long time, and the code fixes fell behind.  Rather than address the merge, I re-pulled and re-made the changes against the current master branch.  I will submit a pull request now

**Comment by sfc-gh-igarish** [comment]
PR has been merged. Please re-open if you think still it's an issue.
