### ISSUE TITLE
Connection Pooling class not accessible from outside?

### ISSUE THREAD

**Issue by iDevelopForU** [snowflakedb/snowflake-connector-net#472]
### Issue description
Trying to use the ConnectionPooling feature, however SnowflakeDbConnectionPool is an internal class, not accessible from outside

### Example code
```cs
SnowflakeDbConnectionPool.SetMaxPoolSize(n);
```

### Error log
None

### Configuration
*2.0.14*

*Dotnet framework and version:* .net core 6

*Server version:* 6.21.0

*Client OS:* Windows 10 Enterprise

**Comment by ehertlein** [comment]
Why is this issue being closed? Are we not supposed to be able to control the connection pooling?

**Comment by RobertChrist** [comment]
This was closed, because it was resolved in this commit: https://github.com/snowflakedb/snowflake-connector-net/commit/75b524b901ea9530dae89fff05113fe6712aff42.

Case should be re-closed

**Comment by ehertlein** [comment]
> This was closed, because it was resolved in this commit: https://github.com/snowflakedb/snowflake-connector-net/commit/75b524b901ea9530dae89fff05113fe6712aff42.

This was closed as completed on June 30th. The commit you linked didn't even exist until Sept 9th. I certainly agree that it could be closed now, but that clearly isn't the reason it was closed before.

**Comment by RobertChrist** [comment]
You're right of course!  I don't actively work on this repository, I just noticed the recent commit in the history, and thought it was worth pointing out in case you missed it!  I should have worded that better!

We can probably close this case now : )  Hurrah!

**Comment by Haopu1** [comment]
I still have this problem

**Configuration**
_2.0.15_

**Comment by wkleong23** [comment]
It's not in the latest version (2.0.16) yet. I'm also waiting for the new release to include this changes.

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
