### ISSUE TITLE
Package has compatibility issues with .NET 6

### ISSUE THREAD

**Issue by Pansynchro-Admin** [snowflakedb/snowflake-connector-net#485]
### Issue description
`Snowflake.Data` targets the obsolete `netstandard2.0` TFM and not anything newer.  This can drag old, incompatible assemblies into a project.

This could probably be fixed by simply publishing a new NuGet package that targets .NET 6.

### Example code
```cs
void Test()
{
   var arr = new int[]{1, 2, 3};
   var ae = arr.ToAsyncEnumerable();
}
```

In a new .NET 6 project, this works.  If you go into NuGet and add Snowflake.Data to the project, it breaks because Snowflake.Data dragged in a duplicate LINQ assembly through its dependency tree.

### Error log
Error	CS0121	The call is ambiguous between the following methods or properties: 'System.Linq.AsyncEnumerable.ToAsyncEnumerable<TSource>(System.Collections.Generic.IEnumerable<TSource>)' and 'System.Linq.AsyncEnumerable.ToAsyncEnumerable<TSource>(System.Collections.Generic.IEnumerable<TSource>)'	

### Configuration
*Driver version:* 2.0.14

*Dotnet framework and version:* .NET 6

*Client OS:* Windows 10

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
