### ISSUE TITLE
The semicolon ; is not supported as a value in a connection string 

### ISSUE THREAD

**Issue by Gdahuks** [snowflakedb/snowflake-connector-net#496]
### Issue description
When the database/roles/warehouses contain a semicolon in the connection string, and the connection is opened an exception is returned.

### Example code
```c#
connectionString = "warehouse=\"warehouse\";db=\"test;2\";role=\"ACCOUNTADMIN\";account=XYZ;host=XYZ.snowflakecomputing.com;server=XYZ.snowflakecomputing.com;user=XYZ;authenticator=snowflake;password=XYZ"
```

### Error log
Error code: 270008
Message: "Connection string is invalid: Invalid key value pair 2\"" 
($exception).StackTrace:
```
   at Snowflake.Data.Core.SFSessionProperties.parseConnectionString(String connectionString, SecureString password)
   at Snowflake.Data.Core.SFSession..ctor(String connectionString, SecureString password, IRestRequester restRequester)
   at Snowflake.Data.Client.SnowflakeDbConnection.SetSession()
   at Snowflake.Data.Client.SnowflakeDbConnection.Open()
```

### Configuration
*Driver version:* 1.2.2.0

*Dotnet framework and version:* .NET Framework 4.8

*Server version:* 6.26.0

*Client OS:*  Windows 11

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
