### ISSUE TITLE
Conn.open() Taking longer and doesn't responding back 

### ISSUE THREAD

**Issue by CPavanKishore** [snowflakedb/snowflake-connector-net#5]
in c# while im debugging at conn.open() it is taking lot of time and doesnt responding back its just loading and loading

**Comment by tandasima** [comment]
Same here. It is taking forever to load and finally fails with not useful exception nor logging.

**Comment by howryu** [comment]
@CPavanKishore @tandasima Thanks for reporting.

I have some instructions in the README on how to enabling logging in .Net Driver, which can give me better idea on what's going on.

**Comment by CPavanKishore** [comment]
It's worked when I added Snowflake.NetCore(https://www.nuget.org/packages/Snowflake.NetCore/) into my project

**Comment by howryu** [comment]
@CPavanKishore This is not a Snowflake project. I don't know what is that project and I don't understand why it worked. One guess it that the dependency of this Snowflake.NetCore project solves the problem. Can you tried just removing Snowflake.NetCore and add https://www.nuget.org/packages/Microsoft.NETCore.App/ to your dependency?

**Comment by CPavanKishore** [comment]
It's not working when I remove that package @howryu.  And Snowflake.data is not working in visual studio 2017

**Comment by howryu** [comment]
@CPavanKishore is your project using .NET Core and .NET Framework? And what is the version? Note that currently Snowflake.Data only compile against .NET Framework 
```
<TargetFrameworkVersion>v4.6</TargetFrameworkVersion>
```

Also can you demonstrate more on "does not work in Visual Studio 2017"? Are you trying to compile the source code? Or it does not work when you tried to add Snowflake.Data as a reference? Note that I developed the library in Visual Studio 2015, so never tried 2017.

**Comment by howryu** [comment]
Update: I tried visual studio 2017 and did not have a problem. Can you give me more details?

**Comment by CPavanKishore** [comment]
i'm trying to accessing that in .netcore 2.0,so did you added it from nuget or you created any library for that ...?

**Comment by CPavanKishore** [comment]
These are the steps which i did for snowflake connection 
=>Create a new project (framework v4.6) web application
=>selected as api project
=>installed nuget package of Snowflake.Data
=>added connection in valuescontroller 
when i try to run it was just loading not giving any response 

I even added the library as existing project and made it as reference,it is doing same as is 

Any advices regarding this please ....?

**Comment by CPavanKishore** [comment]
[95a9041e-54e2-4594-8ddb-935f0e132893network.log](https://github.com/snowflakedb/snowflake-connector-net/files/1695111/95a9041e-54e2-4594-8ddb-935f0e132893network.log)


This it the log file for the above config

**Comment by howryu** [comment]
@CPavanKishore I just deleted your comment since the log contains sensitive data. (i.e. credentials.)  Please change your credentials ASAP. Sorry I should remind you that masking the sensitive data in the log. And I did not find anything interesting in your log.

**Comment by CPavanKishore** [comment]
Thanks for that @howryu 

that is the log file created when i run the application,Still the same not responding 

Did i done it a right way,if yes what will be the issue....?

**Comment by howryu** [comment]
@CPavanKishore I think someone just reported the same problem as you did. So potentially a problem in the Snowflake end. Sorry for inconvenience. I will investigate asap. 
https://github.com/snowflakedb/snowflake-connector-net/issues/11

**Comment by CPavanKishore** [comment]
you guys about to release any new patch for this.....?

**Comment by howryu** [comment]
Sorry I don't have plan yet.

**Comment by howryu** [comment]
@CPavanKishore Can you try the driver again? I just released Snowflake.Data 0.3.0, which supports .net core 2.0, which might resolve your issue.

**Comment by CPavanKishore** [comment]
Yes its working now Thanks @howryu Btw while i'm trying to get the millions of data it throws me an error in the middle i think it might be of time out can you please check that

**Comment by howryu** [comment]
@CPavanKishore Have you checked the latest one? I fixed a bug in #9 and should be available in 0.3.0 release. Also, can I close this issue?

**Comment by CPavanKishore** [comment]
#9 i dont think this was closed,you can try by checking below query in the unit test 
"select seq4(), uniform(1, 10, 42) from table(generator(rowcount => 2000000)) v order by 1"
for getting 2mn of count,i belive that throughs you an error

**Comment by CPavanKishore** [comment]
![capture](https://user-images.githubusercontent.com/25026925/38659023-25ab87ee-3e45-11e8-99dd-b272ab4d2205.PNG)

**Comment by howryu** [comment]
@CPavanKishore  Can you paste the detail exception? The stacktrace. You queries run fine on my machine. I have adjusted that s3 download request to timeout after an hour, and http request timed out after 16 seconds.

**Comment by CPavanKishore** [comment]
`One or more errors occurred. (A task was canceled.)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Snowflake.Data.Core.RestRequestImpl.Post[T](SFRestRequest postRequest)
   at Snowflake.Data.Core.SFStatement.Execute(Int32 timeout, String sql, Dictionary`2 bindings, Boolean describeOnly)
   at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteInternal(Boolean describeOnly)
   at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at SnowFlake_Core_Test.Controllers.ValuesController.Get() in C:\Users\pkreddy\source\repos\SnowFlake_Core_Test\SnowFlake_Core_Test\Controllers\ValuesController.cs:line 31`

**Comment by howryu** [comment]
@CPavanKishore I will close this one and continue the discussion in #40
