### ISSUE TITLE
There is no .NET Core 6

### ISSUE THREAD

**Issue by erickim007** [snowflakedb/snowflake-connector-net#516]
Thank you for upgrading to .NET 6.
Just for documentation point of view, it may be better to remove 'core' from .NET Core 6 to read '.net 6'

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this issue, also apologies for the long period without response. good news that this seems to be already implemented in https://github.com/snowflakedb/snowflake-connector-net/pull/634 , so marking this one as closed.
