### ISSUE TITLE
Authentication token has expired. The user must authenticate again error

### ISSUE THREAD

**Issue by garethrepton** [snowflakedb/snowflake-connector-net#518]
### Issue description
When left for a period of time without using it, the snowflake driver seems to throw an "Authentication token has expired. The user must authenticate again" exception the next time you go to use it even on a freshly initialised connection. This goes away when restarting the application. I suspect the currently internal connection pool controls may fix this, but I'm not sure. Is there a way we can re-fetch an Authentication token with the driver currently so a fresh connection is actually a new connection?

### Example code
N/A

### Error log
```
If you have an error log, please paste it here.
System.Exception: - Error: Authentication token has expired. The user must authenticate again. SqlState: , VendorCode: 390114, QueryId: - Snowflake.Data.Client.SnowflakeDbException

### Configuration
Version: 2.0.16

Framework Version: Dotnet 6

**Comment by MasterKuat** [comment]
Hi, 
Same thing for me as I use the connector in Azure Function.
@garethrepton, as workaround you could use a randmon part in the connection string like : 
`conn = new SnowflakeDbConnection() { ConnectionString = SFconnectionString + $";Rnd={FindConfigContext.InstanceId};" };`

FindConfigContext.InstanceId is a GUID unique along 1 process. This garantee that a same process use the same pooled connection but not an another process.

Not well tested yet, but seems doing the job.

**Comment by pserafin** [comment]
I'm facing same issue  using:
* .Net6.0 client 
* Snowflake.Data 2.0.16

```
private async Task<List<T>> Execute<T>(params Action<IDbCommand>[] actions) where T : class
    {
        await _connection.OpenAsync();
        _connection.CreateCommand();

        try
        {
            await _connection.ExecuteReaderAsync();

            List<T> results = new();

            if (typeof(T).Name is not nameof(DBNull))
            {
                while (await _connection.ReadAsync())
                {
                    T result = _connection.ConvertToObject<T>();
                    results.Add(result);
                }
            }

            return results;
        }
        catch (DbException e)
        {
            _technicalLogService.AddLog(e);
            return new List<T>();
        }
        finally
        {
            await _connection.CloseAsync();
            Reset();
        }
    }
```
  So I don't see here any path where session might not being closed.

**Comment by ehertlein** [comment]
Unless I am misunderstanding your issues, these are all from the same root problem in that the connection pooling isn't implemented correctly. We had similar issue and downgraded to 2.0.13 before connection pooling was introduced.

You can see [here](https://github.com/snowflakedb/snowflake-connector-net/blob/eff3ec24b7be0df567316edf5ff207746251cf36/Snowflake.Data/Client/SnowflakeDbConnection.cs#L213) that your OpenAsync() is really just pulling from the pool and your [CloseAsync()](https://github.com/snowflakedb/snowflake-connector-net/blob/eff3ec24b7be0df567316edf5ff207746251cf36/Snowflake.Data/Client/SnowflakeDbConnection.cs#L121) is just releasing connections into the pool.

**Comment by sfc-gh-dszmolka** [comment]
thank you everyone for drawing our attention to this issue. it is currently being looked at and the fix is being prepared - thank you for bearing with us!
until it's available, indeed the issue can be avoided by downgrading to <=2.0.14.

**Comment by virgilp** [comment]
@sfc-gh-dszmolka PR merged & released in 2.0.17, can you confirm that issue is closed now?

**Comment by sfc-gh-dszmolka** [comment]
i can confirm the new driver release should fix this, sadly i don't have permissions to actually close this item.

**Comment by pserafin** [comment]
Yes, a coleque from mine team updated nuggets to latest and the issue no longer occurred (for 2 days now)

**Comment by pserafin** [comment]
Coleque from mine team updated nuggets to latest version and the issue no longer occurred (for 2 days now)

**Comment by garethrepton** [comment]
I haven't seen this error since updating to this version. Combined with others saying this is fixed for them, I think it's safe to close right now.
