### ISSUE TITLE
v2.0.16 has a dependency on Azure.Storage.Blobs v12.10.0 which has a Level 1 vulnerability

### ISSUE THREAD

**Issue by andrewcfrancis2** [snowflakedb/snowflake-connector-net#520]
### Issue description
v2.0.16 has a dependency on Azure.Storage.Blobs v12.10.0 which has a Level 1 vulnerability. See details here:

https://github.com/advisories/GHSA-64x4-9hc6-r2h6

Can that be updated to Azure.Storage.Blobs v12.13.0 or higher to resolve the issue?

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
