### ISSUE TITLE
Error: Session no longer exists.  New login required to access the service

### ISSUE THREAD

**Issue by pserafin** [snowflakedb/snowflake-connector-net#522]
### Issue description
I'm using .Net 6.0 cllient with Snowflake.Data 2.0.16 package

In general I'm using slightly modified below code (from this source: https://github.com/snowflakedb/snowflake-connector-net/issues/275)

```
// application startup registers this provider as a singleton
public class SnowflakeConnectionProvider : IDisposable
{
  private IDbConnection _conn;

  public SnowflakeConnectionProvider()
  {
    _conn = new SnowflakeDbConnection();
    _conn.ConnectionString = "connectionString";
    _conn.Open();
  }

  public IDbConnection conn { get => _conn; }

  public Dispose() => _conn.Close();
}
```

and the command execution as follow

```
public class Worker
{
  public Worker(SnowflakeConnectionProvider provider)
  {
    IDbConnection conn = provider.conn;
    
    IDbCommand cmd = conn.CreateCommand();
    cmd.CommandText = "select * from t";
    IDataReader reader = cmd.ExecuteReader();
                
    while(reader.Read())
    {
        Console.WriteLine(reader.GetString(0));
    }
  }
}

```

The code is deployed as azure function (ver. 4) and multiple simultaneous threads may in same time query Snowflake.
When I'm running code locally - there is no problem with it, but when azure function is calling up to 10 processes then I'm starting to log below errors
![image](https://user-images.githubusercontent.com/19813139/190495536-bc1262e6-d9df-4280-9374-76dd80f6de9a.png)

I've tried as well to change the code but then I was facing errors like :
```
Snowflake.Data.Client.SnowflakeDbException (0x80004005): Error: SQL execution canceled SqlState: 57014, VendorCode: 604, QueryId: 01a6fcdb-0301-6d9c-0000-3f151dd2c46a
Snowflake.Data.Client.SnowflakeDbException (0x80004005): Error: Session no longer exists.  New login required to access the service. SqlState: , VendorCode: 390111, QueryId: 
Exception while executing function: ServiceBusMessageConsumer ---> System.Exception: Can't execute command when connection has never been opened
```
I've tried to limit range of the connection scope (open per single snowflake query) and/or extend it -> inject with scoped/transient life time with same result.
Some "lucky" queries are able to finish with success when others are failing with one of mentioned errors.

I'm really lacking of ideas how can I approach this and would appreciate any help from community.
Maybe is worth mentioning that most of queries are inserting single row in same table. I have great knowledge on MSSQL but I'm totally green if it comes to Snowflake - although it looks similar, it seems that .Net client is in some beta stage (no offence). But maybe the issue is no the client? Mabye the issue is connected to user/table ? I'm not sure/

**Comment by virgilp** [comment]
You can disable the Snowflake connection pool using this static method: https://github.com/snowflakedb/snowflake-connector-net/blob/7717901fc6577976fe17e5166cdc32323b2344d9/Snowflake.Data/Client/SnowflakeDbConnectionPool.cs#L155

Less drastic method - when you start getting this error (or, once every 5 hours) clear the connection pool. 
Or wait until https://github.com/snowflakedb/snowflake-connector-net/pull/525 gets merged & released, then update the driver

**Comment by pserafin** [comment]
Coleque from mine team updated nuggets to latest version and the issue no longer occurred (for 2 days now)
