### ISSUE TITLE
ExecuteNonQuery return -1 If we call insert/update/delete proc

### ISSUE THREAD

**Issue by arunc700** [snowflakedb/snowflake-connector-net#532]
I am using this dll to use my snowflake database with the dotnet code.  I have created a snowflake proc which lanmguage is "SQL" and proc return type is number. Proc is given below.

    CREATE OR REPLACE PROCEDURE DeleteData("Id" VARCHAR(50))
    RETURNS number
    LANGUAGE SQL
    EXECUTE AS CALLER
       AS declare         
            --Delete table
            DELETE FROM   TestTable      WHERE    Id= :Id;
             return sqlrowcount;
       end if;      
    end;

Now I am calling this proc from dotnet code with the help of below code
      
       --script execute as "call DeleteData('guid');"
      SnowflakeDbCommand.ExecuteNonQuery();

It execute the proc but always returns -1 as row affected.

Reason is also mentioned in your ResultSetUtil.cs class for below method. We are calling proc with the help of "Call DeleteProc(id);". SFStatementType.CALL return true so I can never get affected row by Calling sql proc.

      internal static bool HasResultSet(this SFBaseResultSet resultSet)
        {
            SFResultSetMetaData metaData = resultSet.sfResultSetMetaData;
            SFStatementType statementType = metaData.statementType;

            switch (statementType)
            {
                case SFStatementType.SELECT:
                case SFStatementType.EXPLAIN:
                case SFStatementType.SHOW:
                case SFStatementType.DESCRIBE:
                case SFStatementType.LIST_FILES:
                case SFStatementType.GET_FILES:
                case SFStatementType.PUT_FILES:
                case SFStatementType.REMOVE_FILES:
                case SFStatementType.CALL:
                    return true;
                default:
                    return false;
            }
        }

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this issue, also apologies for the long period without response. i'm curious whether this behaviour is intended or a bug, so could you please try it with other Snowflake drivers or even [SnowSQL](https://docs.snowflake.com/en/user-guide/snowsql) (which uses the Python driver) and observe what is returned ? 
if it works differently with other drivers, let me know please and we can continue troubleshooting.
