### ISSUE TITLE
Why resultSet.HasResultSet() method use statement type as CALL 

### ISSUE THREAD

**Issue by arunc700** [snowflakedb/snowflake-connector-net#533]
https://github.com/snowflakedb/snowflake-connector-net/blob/01dde9b01200e8ec739db1592728bca96045e2fd/Snowflake.Data/Client/SnowflakeDbCommand.cs#L163

Why are you including StatementType.Call with ExecuteNonQuery method. I am facing a problem that If snowflake proc return affected row by insert/update and delete. If we use ExecuteNonQuery with CALL proc then we will never get the affected row.

Could you please guide?

**Comment by sfc-gh-dszmolka** [comment]
this is #532
