### ISSUE TITLE
NETFRAMEWORK preprocessor directive incorrectly applied to .Net Core 

### ISSUE THREAD

**Issue by klewelling** [snowflakedb/snowflake-connector-net#536]
### Issue description
The NETFRAMEWORK preprocessor directive should apply to Windows only, however it is being applied to .NET Core as well. 
For example https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data/Core/Authenticator/ExternalBrowserAuthenticator.cs and https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data/Core/RestParams.cs

### Example code
The following code from RestParams.cs when compiled using .Net Core SDK on MacOS will set the netRuntime to "NETFramework" rather than "NETCore" 
```cs
#if NETFRAMEWORK
                netRuntime = "NETFramework",
                netVersion = "4.7.2",
#else
                netRuntime = "NETCore",
                netVersion ="2.0",
#endif
```

The following code form ExternalBrowserAuthenticator.cs when compiled using .Net Core SDK on MacOS will exclude the multi-platform external browser code. This causes authentication=externalbrowser to fail on MacOS (and presumably Linux) with file not found errors. 
```cs

        private static void StartBrowser(string url)
        {
            // The following code is learnt from https://brockallen.com/2016/09/24/process-start-for-urls-on-net-core/
#if NETFRAMEWORK
            // .net standard would pass here
            Process.Start(url);
#else
            // hack because of this: https://github.com/dotnet/corefx/issues/10361
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                url = url.Replace("&", "^&");
                Process.Start(new ProcessStartInfo("cmd", $"/c start {url}") { CreateNoWindow = true });
            }
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
            {
                Process.Start("xdg-open", url);
            }
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
            {
                Process.Start("open", url);
            }
            else
            {
                throw new SnowflakeDbException(SFError.UNSUPPORTED_PLATFORM);
            }
#endif
        }
```

### Culprit 
According to https://learn.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-a-target-framework the NETFRAMEWORK preprocessor directive should only be available on Windows. However this PropertyGroup in https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data/Snowflake.Data.csproj defines NETFRAMEWORK for all frameworks that have "net" in the name. 

```
  <PropertyGroup Condition="$([System.Text.RegularExpressions.Regex]::IsMatch('$(TargetFramework)', '^net\d'))">
	<DefineConstants>NETFRAMEWORK</DefineConstants>
  </PropertyGroup>
```
I believe this PropertyGroup is incorrect and should not define NETFRAMEWORK when using .Net Core. When I remove this PropertyGroup the NETFRAMEWORK preprocessor directive is no longer defined when compiling with .Net Core 6 and I am able to successfully authenticate using an external browser.

### Configuration
*Driver version: 2.0.16*

*Dotnet framework and version: .Net Core 6.0*

*Server version: 6.32.3* 

*Client OS: MacOS 12.4*

**Comment by sfc-gh-igarish** [comment]
Please check latest release.
