### ISSUE TITLE
Snowflake throw Exception when I add role=PUBLIC in connectionString

### ISSUE THREAD

**Issue by touchdreamer** [snowflakedb/snowflake-connector-net#537]
### Issue description
I add role=PUBLIC in snowflake connectionString, but it can't work.

### Error log
Unhandled exception. Snowflake.Data.Client.SnowflakeDbException (0x80004005): Error: The requested warehouse does not exist or not authorized. SqlState: 08006, VendorCode: 390201, QueryId:
   at Snowflake.Data.Core.SFSession.ProcessLoginResponse(LoginResponse authnResponse)
   at Snowflake.Data.Core.Authenticator.BaseAuthenticator.Login()
   at Snowflake.Data.Core.Authenticator.BasicAuthenticator.Snowflake.Data.Core.Authenticator.IAuthenticator.Authenticate()
   at Snowflake.Data.Core.SFSession.Open()
   at Snowflake.Data.Client.SnowflakeDbConnection.Open()

### Configuration
*Driver version:*

*Dotnet framework and version: net framework 4.7.2

*Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```

*Client OS:* E.g. Debian 8.1 (Jessie), Windows 10

**Comment by touchdreamer** [comment]
My connection string: account=microsoft_partner.east-us-2.azure;user=WENCHAOHU;db=TEST_DB;warehouse=ADF_QUERY_TEST;password=************;role=PUBLIC

**Comment by sfc-gh-dszmolka** [comment]
findings: the `role` works as expected in the connection string, however if the particular `role` used in the connection string does **not** have `USAGE` privilege on the particular `warehouse` used in the connection string, then it's expected  to fail with `The requested warehouse does not exist or not authorized` error, coming from the Snowflake backend and not the driver. 

so this part is expected to happen. what might not be expected, is if we necessarily need to throw an unhandled exception on this one - still discussing internally.

**Comment by sfc-gh-dszmolka** [comment]
thank you for the patience on this. after some discussion, `SnowflakeDbException` is standard SF exception thrown if connection fails because of any reason. "Unhandled exception" only means that the user didn't catch the exception.
So this behaviour is expected and the reason is also expected (see above). Marking this issue as closed but if you feel you saw a bug , please feel free to update this issue with the details in the comment.
