### ISSUE TITLE
Update the readme part mentionining supported plattforms

### ISSUE THREAD

**Issue by mariusingjer** [snowflakedb/snowflake-connector-net#539]
The readme states: "The Snowflake .NET connector supports only Windows."

Either: elaborate, what exactly are we talking about here.

Or: remove the above statement.

Cross plattform support is a very important feature, which in our case results in selecting other languages than dotnet (in this particular case), so the above statement is creating extra noise and evaluation work. I am suspecting that the documentation is stale and that this works cross plattform today?

**Comment by sfc-gh-dszmolka** [comment]
hello and thank you for raising this issue, also apologies for the long period without response. i see this is fixed with https://github.com/snowflakedb/snowflake-connector-net/pull/657, so marking this one as closed
