### ISSUE TITLE
SnowflakeDbParameter behavior is incompatible with Entity Framework

### ISSUE THREAD

**Issue by jjmason** [snowflakedb/snowflake-connector-net#54]
### Issue description

We have built a simple Entity Framework provider for Snowflake.  While doing so we discovered that Entity Framework infrastructure code reads and writes properties found on the `SnowflakeDbParameter` class (specifically `IsNullable`,  `Size`, `SourceColumn` and `SourceColumnNullMapping`), which are implemented as throwing  `NotImplementedExceptions`.  
 
We've addressed this in a fork by causing these properties to return default values and to reject non-default values passed to their setters, and have submitted PR #55 as a proposed fix.

We believe this is a good compromise between throwing `NotImplementedException` for all values, and allowing arbitrary values that the rest of the library ignores.

### Configuration
*Driver version:* Snowflake.Data/1.0.2

*Dotnet framework and version:*  netstandard2.0

*Server version:* 2.55.1

*Client OS:*  Windows 10

**Comment by howryu** [comment]
Thanks for your contribution. It is merged in #59

**Comment by buvinghausen** [comment]
@jjmason I was digging around to see if there were any Entity Framework providers for Snowflake on .NET Core and this was the top hit.  Would you be willing to open source the provider perchance so we could get an assembly out to NuGet?
