### ISSUE TITLE
CLIENT_SESSION_KEEP_ALIVE=true causes 401 response

### ISSUE THREAD

**Issue by jimhoonan** [snowflakedb/snowflake-connector-net#557]
### Issue description
When I include client_session_keep_alive=true in my connection string, I receive a 401 response when calling OpenAsync.
If I include client_session_keep_alive=false in my connection string the connection is successful

This is occurring in driver version 2.0.19
.net 6.0

**Comment by alitas** [comment]
The PR #553 aims to fix this.

**Comment by alitas** [comment]
> Yes, I saw that. Do you know when it will be released?

No idea. I'm waiting for a response from the maintainers too.

**Comment by deepak-vanco** [comment]
release this fix please....very getting ton 401 issues

**Comment by sfc-gh-igarish** [comment]
Please try latest version.
