### ISSUE TITLE
JsonReaderException on Cancel()

### ISSUE THREAD

**Issue by Castlejoe** [snowflakedb/snowflake-connector-net#56]
Hi,

When snowflake is very busy, you risk to cancel (timeout kicked in) an async command before it actually was run. In this case, the cancel post returns a json that looks like this:

```javascript
{
    "data": {
        "internalError": false,
        "errorCode": "000605",
        "age": 0,
        "sqlState": "01000",
        "queryId": null
    },
    "message": "Identified SQL statement is not currently executing.",
    "code": "000605",
    "success": false
}
```

This is then tried to be deserialized into `NullDataResponse` - which fails since `data` is expected to be string:

 `"errorType": "JsonReaderException",
"errorMessage": "Unexpected character encountered while parsing value: {. Path 'data', line 2, position 12.",
"stackTrace": [
"at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)",
"at Newtonsoft.Json.JsonTextReader.ReadAsString()",
"at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)",
"at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)",
"at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)",
"at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)",
"at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)",
"at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)",
"at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)",
"at Snowflake.Data.Core.RestRequestImpl.PostAsync[T](SFRestRequest postRequest, CancellationToken cancellationToken)",
"at Snowflake.Data.Core.RestRequestImpl.<>c__DisplayClass11_0'1.<<Post>b__0>d.MoveNext()"
`

**Comment by howryu** [comment]
Thanks for your reporting. I am not an expert in c# async api, but I understand the problem. It might take me a while to figure it out.

**Comment by Castlejoe** [comment]
The point is just that in class NullDataResponse you have the "data" field defined as string, but in this case you get an object from snowflake. So newtonsoft can't deserialize the json object into a string.

**Comment by howryu** [comment]
@Castlejoe I see your point. Right now it failed with not being able to deserialize the json response, right? So I think the correct way is doing nothing since query has not started execution yet.

**Comment by manigandham** [comment]
@howryu 

I think query cancellations should get their own response type since there seems to be relevant information returned by the server, but until then changing https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data/Core/RestResponse.cs#L27 from `string` to `object` will fix it.

**Comment by manigandham** [comment]
@howryu Sounds good, thanks.
