### ISSUE TITLE
Transaction ' was aborted, SQL execution canceled. SqlState:  VendorCode: 615,

### ISSUE THREAD

**Issue by deepak-vanco** [snowflakedb/snowflake-connector-net#560]
I am using the DbTransaction and Inserting Mutiple table, it works some time and some time throwing exceptions

	SnowflakeDbTransaction dbTransaction =null;
			using (_snowFlakeRepository)
			{
				 dbTransaction =  _snowFlakeRepository.BeginDbTransaction();
				await AddTable1Data();
				await AddTable2Data();
				await AddTable3Data();
				dbTransaction.Commit();
			}
		}
		catch (Exception ex)
		{
			dbTransaction?.Rollback();

Snowflake.Data.Client.SnowflakeDbException:
   at Snowflake.Data.Core.SFStatement.ExecuteHelper (Snowflake.Data, Version=2.0.17.0, Culture=neutral, PublicKeyToken=null)
   at Snowflake.Data.Core.SFStatement.Execute (Snowflake.Data, Version=2.0.17.0, Culture=neutral, PublicKeyToken=null)
   at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteNonQuery (Snowflake.Data, Version=2.0.17.0, Culture=neutral, PublicKeyToken=null)

![image](https://user-images.githubusercontent.com/62299332/205707011-9234f4e5-99e3-4e9e-9362-def62236017d.png)

**Comment by sfc-gh-igarish** [comment]
Thanks for reporting issue. We will look into it.

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for your patience on this one. we checked sessionid `423921864974442` and found that there are multiple concurrent threads, where each thread: (1) starts transaction, (2) makes inserts and (3) commits transaction.

but they all run in the same thread, so only the first `BEGIN` which hits Snowflake is taken into consideration, and as soon as the first thread `COMMIT`s the transaction, it's done - the rest of the pending operations will and should get an exception. 

if you wish to run the three threads in parallel, suggest running them in separate sessions.

so for now, this behaviour looks like expected and therefore I'm closing the issue. if you still feel you're seeing a driver bug, could you please comment:
* full runnable application code (not just snippet, and all function definitions included) which when run, exhibits the symptoms you're seeing
* maybe the debug logs as well

thank you in advance !
