### ISSUE TITLE
No active warehouse selected error despite warehouse selected in connection string.

### ISSUE THREAD

**Issue by anzu-3278** [snowflakedb/snowflake-connector-net#562]
### Issue description

I'm trying to run a TPCH benchmark on Snowflake using this library.
One of the queries (Q11) consistently fails with the following error:

```
Snowflake.Data.Client.SnowflakeDbException (0x80004005): Error: No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.
 SqlState: 57P03, VendorCode: 606, QueryId: 01a8ce8d-0000-dc49-0002-950a0007f152
   at Snowflake.Data.Core.SFStatement.BuildResultSet(QueryExecResponse response, CancellationToken cancellationToken)
   at Snowflake.Data.Core.SFStatement.<ExecuteAsync>d__35.MoveNext()
```

This is despite me setting the warehouse explicitly in the connection string like so:

"scheme=https;ACCOUNT={account};HOST={host};port=443;ROLE=sysadmin;WAREHOUSE={warehouse};USER={username};PASSWORD={password};DB={database};SCHEMA={schema}"

and other queries that use the same connection string consistently working as normal.

This is not the first query being run (so the warehouse is already active at this point) and multiple repeats of the query will all fail.

Query SQL:

```sql
SELECT
  PS_PARTKEY,
  sum(PS_SUPPLYCOST * PS_AVAILQTY) AS value
FROM
  PARTSUPP,
  SUPPLIER,
  NATION
WHERE
  PS_SUPPKEY = S_SUPPKEY
  AND S_NATIONKEY = N_NATIONKEY
  AND N_NAME = 'GERMANY' -- [NATION]
GROUP BY
  PS_PARTKEY
HAVING
  sum(PS_SUPPLYCOST * PS_AVAILQTY) > (
    SELECT
      sum(PS_SUPPLYCOST * PS_AVAILQTY) * (0.0001 / 0.1)
    FROM
      PARTSUPP,
      SUPPLIER,
      NATION
    WHERE
      PS_SUPPKEY = S_SUPPKEY
      AND S_NATIONKEY = N_NATIONKEY
      AND N_NAME = 'GERMANY'
  )
ORDER BY
  value DESC
```

Investigation on the Snowflake endpoint shows that the Warehouse parameter was never propagated:

![snowflake](https://user-images.githubusercontent.com/66275036/206229890-73049b3c-6532-41c0-9f2c-1cf6fba43fd4.png)

### Configuration
*Driver version:* 2.0.10.0

*Dotnet framework and version:* .net framework 4.7.2

*Server version:* E.g. 6.40.1

*Client OS:* Windows Server 2016

**Comment by myshon** [comment]
I suppose something is wrong with connection string. There is unit tests that verifies WAREHOUSE parameter. See: https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data.Tests/SFConnectionIT.cs#L476
