### ISSUE TITLE
Parameterizing USE WAREHOUSE statement

### ISSUE THREAD

**Issue by anzu-3278** [snowflakedb/snowflake-connector-net#563]
### Issue description

Is there a way to parameterize a USE WAREHOUSE statement?
I have taken a look at the examples in the readme and tests but they did not work for me.
I have a program where users would be able to input the warehouse name for their own Snowflake resources and I would like to avoid the possibility of SQL injection.

### Example code
```cs
cmd.CommandText = "USE WAREHOUSE (?)";
var par = cmd.CreateParameter();
par.Value = "DEFAULT";
par.DbType = DbType.String;
par.ParameterName = "warehouse";
cmd.Parameters.Add(par);
cmd.ExecuteNonQuery();
```

### Error log
```
Error Message: Error: SQL compilation error:
syntax error line 1 at position 14 unexpected '('. SqlState: 42000, VendorCode: 1003, QueryId: 01a8cfeb-0000-dc90-0002-950a0008203e
```

### Configuration
*Driver version:* 2.0.10.0

*Dotnet framework and version:* .net framework 4.7.2

*Server version:* 6.40.1

*Client OS:* Windows 10

**Comment by DDtMM** [comment]
You can use the [IDENTIFIER ](https://docs.snowflake.com/en/sql-reference/identifier-literal.html)function and change the command text to `USE WAREHOUSE IDENTIFIER(?)`;
