### ISSUE TITLE
Issues upgrading from 1.0.10 to 2.0.19 on a v4 functions app running on .net6

### ISSUE THREAD

**Issue by DDtMM** [snowflakedb/snowflake-connector-net#568]
This is more of a FYI than an issue.  We resolved our issues by downgrading to 2.0.8.  We did this because another team in my organization did the same thing when they had different issues.

## Issue 1: Randomly missing rows
The code below ran for at least a day before a problem started happening.  A query that returned on average 500 rows will randomly be missing results.  Sometimes up to almost 33%.  There were about 8 incidences and the skipped rows seemed a bit random and weighted towards the end of the query.  Also it seemed to happen when utilization was high.

It felt like a missing await somewhere.  Like somehow the counter in the result set is getting incremented multiple times before a row can get added.   I ran through your code and I couldn't find a smoking gun.  

One other thing,  For some reason somebody before me called `.Result` on the method that executed this code.  I replaced the instance of `.Result` with `await`, but before it was running for a day another issue came up and the decision was made to downgrade.
```
await using SnowflakeDbDataReader reader = (SnowflakeDbDataReader)await cmd.ExecuteReaderAsync();
JArray rows = new();

// Process all elements in the current result set
while (await reader.ReadAsync())
{
    JObject row = new();
    for (int j = 0; j < reader.FieldCount; ++j)
    {
        row.Add(reader.GetName(j), reader.GetValue(j).ToString());
    }
    rows.Add(row);
}
```

## Issue 2: Error: Session no longer exists. New login required to access the service.

This seems related to #522 as we are getting the same error message and we're running on Azure functions v4 as well.  What happened was the same function was getting called in rapid succession.  After 10-20 calls, each successive call would produce the Session no longer exists error.  
```
SnowflakeDbException:"Error: Session no longer exists. New login required to access the service. SqlState: , VendorCode: 390111,
 at Snowflake.Data.Core.SFStatement.ExecuteHelper[T,U](Int32 timeout, String sql, Dictionary`2 bindings, Boolean describeOnly)
 at Snowflake.Data.Core.SFStatement.Execute(Int32 timeout, String sql, Dictionary`2 bindings, Boolean describeOnly)
 at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteNonQuery()
 at XYZ.Services.DataService.RunSnowflakeSqlCommands(ILogger log, ConnectorDetails connectorDetails) line 232
```

Sometimes the next failure would be the same failure, and sometimes the next failure would occur a little later in the script when another query was run.  To be clear this are different execution instances of the same function.
```
SnowflakeDbException:  Error: SQL execution canceled, SqlState: 57014, VendorCode: 604
 at Snowflake.Data.Core.SFStatement.BuildResultSet(QueryExecResponse response, CancellationToken cancellationToken)
 at Snowflake.Data.Core.SFStatement.ExecuteAsync(Int32 timeout, String sql, Dictionary`2 bindings, Boolean describeOnly, CancellationToken cancellationToken)
 at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
 at XYZ.Services.DataService.RunSnowflakeSqlCommands(ILogger log, ConnectorDetails connectorDetails) line 246
```

Thank you, I hope this information can be of use later.

### Configuration
*Driver version:* 2.0.19
*Dotnet framework and version:* .net6
*Server version:* 6.40.1
*OS:* Windows Azure Function instance v4.

**Comment by shawner18** [comment]
Having the same issue #2 above, after changing from 2.0.8 to 2.0.24. 2.0.23 has the same issue as well.

**Comment by sfc-gh-pbulawa** [comment]
Hi,

Issue 2 is already fixed in driver v.2.0.25 - [PR #666](https://github.com/snowflakedb/snowflake-connector-net/pull/666).

I was unable to replicate the issue 1 - there is a possibility that the issue has already been fixed as it has been reported more than 6 months ago. Are you able to reproduce the issue with the newest version of the driver?

**Comment by DDtMM** [comment]
I am not able to reproduce the issue any longer.
