### ISSUE TITLE
Timeout Error on AWS Lambda in .Net 6 while connecting Snowflake

### ISSUE THREAD

**Issue by TheDonBenso** [snowflakedb/snowflake-connector-net#572]
### Issue description

Hi, I am using an aws lambda to run a snowflake query which will fetch some Ids and I am experiencing a timeout error. 
The lambda is runing from a different region, under a different subscription, but on my personal PC, I am able to connect and get results even though it does take about 10 seconds or more to connect. 

Is there a way to configure this connection to not cause a timeout issue? 

### Example code
```cs
            try
            {
                using (IDbConnection conn = new SnowflakeDbConnection())
                {
                    conn.ConnectionString = "ACCOUNT=demoaccount;HOST=demoaccount.us-east-1.snowflakecomputing.com;USER=demouser;PORT=443;PASSWORD=demopassword;WAREHOUSE=demowh;ROLE=READ_ONLY;db=demo_db;schema=demo_db_schema";
                    conn.Open();
                    Console.WriteLine("Connection to Snowflake successful!");
                    using (IDbCommand cmd = conn.CreateCommand())
                    {
                        int i = 1;
                        cmd.CommandText = "SELECT * FROM CustomTable";   // sql operation fetching 

                        cmd.ExecuteNonQuery();
                        //data from an existing table
                        IDataReader reader = cmd.ExecuteReader();
                        Console.WriteLine($"Index \t || \t  column 1 Id \t \t \t || \t  column 2 \t \t  || \t \t column 3");
                        Console.WriteLine("______________________________________________________________________");
                        while (reader.Read())
                        {
                            Console.WriteLine($"{i} \t || {reader.GetString(0)}  \t || \t  {reader.GetString(1)}  \t || \t  {reader.GetString(2)}");
                            i++;
                        }
                        conn.Close();
                    }
                }
            }
            catch (DbException exc)
            {
                Console.WriteLine($"Error Message: {exc.Message} at {DateTime.Now} \n {exc.InnerException}");
            }


```

### Error log
```
If you have an error log:

at Snowflake.Data.Core.SFStatement.TrimSql(String originalSql)
at Snowflake.Data.Core.SFStatement.Execute(Int32 timeout, String sql, Dictionary`2 bindings, Boolean describeOnly)
at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteNonQuery()

```

The issue starts from this point      cmd.ExecuteNonQuery();

*Dotnet framework and version:*
 .net 6 C#
 Snowflake.Data 2.0.19

**Comment by mbwilding** [comment]
It's using windows specific libraries, and lambda is linux.

**Comment by mbwilding** [comment]
Add this to your connection string.

`insecuremode=true`

**Comment by roberocity** [comment]
I experience a similar issue, but the issue occurs at `conn.Open().` In my case, the server never sends a response to the request. The Lambda eventually times out, having never completed the open request.

**Comment by mbwilding** [comment]
> I experience a similar issue, but the issue occurs at `conn.Open().` In my case, the server never sends a response to the request. The Lambda eventually times out, having never completed the open request.

Did you try adding insecuremode=true to the connection string? Just disables certificate revocation checks, but that fixes connecting usually.

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for submitting the issue.
```c#
                        cmd.ExecuteNonQuery();
                        //data from an existing table
                        IDataReader reader = cmd.ExecuteReader();
```

this attempts to execute the query twice.  first incorrectly because `ExecuteNonQuery()` is not meant to execute queries (hence the name..), and then again, this time correctly by calling `ExecuteReader()`.

can you please try removing `ExecuteNonQuery` from the code and then again verify if the timeout still occurs ?
