### ISSUE TITLE
Invalid connection state when connection is in pool

### ISSUE THREAD

**Issue by PKYHL** [snowflakedb/snowflake-connector-net#580]
### Issue description
When calling open on a connection where the connection string contains an invalid user id or password the connection fails but if I create a new connection with the same invalid connection string and call open it does not fail and the connection state is Open

### Example code
            var myConnectionStringWithInvaldUser = GetConnectionStringWithInvalidUserId();
            try
            {
                var snowflakeConnection = new SnowflakeDbConnection();
                snowflakeConnection.ConnectionString = myConnectionStringWithInvaldUser;
                snowflakeConnection.Open();
            }
            catch
            {
                //this will fail because of the invalid credentials
            }
            try
            {

                var snowflakeConnection = new SnowflakeDbConnection();
                snowflakeConnection.ConnectionString = myConnectionStringWithInvaldUser;
                snowflakeConnection.Open();
            }
            catch
            {
                //this will not fail and the snowflakeConnection.State equals ConnectionState.Open
            }

### Configuration
Snowflake 2.0.19
Dotnet framework and version: .net framework 4.8
OS: Windows 10

**Comment by AndrewRybka** [comment]
I'm experiencing the same behavior. The HOST and ACCOUNT connection properties may be incorrect too, but the second call to the Open method is still successful.

**Comment by jboelter** [comment]
Hitting the same bug. If Open fails it throws an exception (invalid Uri in this case). The second time through that same connection is reused even though it is a failed state. Calling Close() on it doesn't remove it from the pool. Executing a command will then appear to hang.

At the moment, it's not obvious if there's a workaround other than turning off pooling. Calling Close() on a connection returns it to the connection pool in [PostClose](https://github.com/snowflakedb/snowflake-connector-net/blob/8f5c0c6fff1dbd1e4b737c2c146a7ef5eb0c049d/Snowflake.Data/Client/SnowflakeDbConnection.cs#L123)

It might be possible to call `ClearAllPools` after any error on an `Open` **after** Dispose() or Close() is called.

```csharp
var dbConnection = SnowflakeDbConnection(_connectionString);
try {
    dbConnection.Open();
}
catch (SnowflakeDbException ex) {
    dbConnection.Close(); // doesn't work this just returns it to the connection pool
    throw ex;
}
var open = dbConnection.IsOpen();
// sometime later
cmd.ExecuteNonQuery()

```

**Comment by sfc-gh-dszmolka** [comment]
thank you for submitting this issue and apologies for the long period without response. we'll take a look

**Comment by sfc-gh-dszmolka** [comment]
we were not able to reproduce this in-house, but starting from driver version 2.1.1, tests were added (https://github.com/snowflakedb/snowflake-connector-net/pull/717) to avoid such situations. 

Please try with version 2.1.1 or above and if the issue still persist with the newer driver versions as well, let us know please. A reproduction would be even super appreciated. Thank you in advance !
