### ISSUE TITLE
Could not read private key with value passed in connection string

### ISSUE THREAD

**Issue by rdhasse** [snowflakedb/snowflake-connector-net#587]
### Issue description
After upgrading from version 2.0.13 to 2.0.20, the same C# code we use to pass a private key via the connection string now fails.

### Example code

We build the connection string with the below C# code, which works fine with version 2.0.13.

```cs
var connectionString = $"account={account};host={snowflakeBaseURL};warehouse={c.ServerName};role={role};db={c.DatabaseName};schema={schema};user={c.UserName};authenticator=snowflake_jwt;private_key={certificate};{certPasswordField}";
```

### Error log
```
Exception:
Snowflake.Data.Client.SnowflakeDbException: 'Error: Could not read private key with value passed in connection string. \n Error : incorrect private key value or private key format: use "\n" for newlines and double the equals sign. SqlState: , VendorCode: 270052, QueryId: '

InnerException:
IOException: base64 data appears to be truncated
```

### Configuration
Driver version: 2.0.20

Issue occurs with: net472, net5.0, net6.0

Server version: 7.2.0

Client OS: Windows 10 Enterprise

**Comment by rdhasse** [comment]
Update:  After reverting to driver version 2.0.13, I observed this same issue with net6.0.  However, with this driver version net472 and net5.0 do not have this issue.

**Comment by rdhasse** [comment]
Update: I incremented versions from 2.0.13 one by one until this issue happened.  I found that this issue was introduced in version 2.0.18.

**Comment by sfc-gh-spanaite** [comment]
Thanks for reporting it @rdhasse, I am able to reproduce the issue and it seems to be introduced due to the BCR change. We've reported it internally and we should have an update soon. Please use .NET up to 2.0.17 for now as a workaround.

**Comment by rdhasse** [comment]
Hello,

Thanks for the details.  After following those details, it seems we no longer have this issue with driver version 2.0.22.

Thanks,

Randall

**Comment by plaisted** [comment]
@sfc-gh-spanaite the documentation is not up to date for this, thankfully found this issue

```
The private key to use for key-pair authentication. Must be used in combination with AUTHENTICATOR=snowflake_jwt.If the private key value includes any equal signs (=), make sure to replace each equal sign with two signs (==) to ensure that the connection string is parsed correctly.
```
