### ISSUE TITLE
Proxy password is shown in the Snowflake log file

### ISSUE THREAD

**Issue by mgbo23** [snowflakedb/snowflake-connector-net#589]
### Issue description
Proxy password is shown in the Snowflake log file.

### Example code
connectionstring:
"account=[[account]];user=[[user]];password=[[password]];db=[[db]];schema=[[schema]];warehouse=[[warehouse]];role=[[role]];useProxy=true;proxyHost=[[proxyHost]];proxyPort=[[proxyPort]];proxyUser=[[proxyUser]];proxyPassword=[[proxyPwd]]"

snowflake log:
[2023-01-30 14:52:20,611] [1] [DEBUG] [Snowflake.Data.Core.HttpUtil] Http client for True;[[proxyHost]];[[proxyPort]];[[proxyUser]];[[proxyPwd]];;False;False not registered. Adding.

*Driver version:*
2.0.19.0

*Dotnet framework and version:* 
.NET Framework 4.7.2

*Server version:* 
7.3.1

*Client OS:* 
Windows NT 6.2.9200.0

**Comment by sfc-gh-igarish** [comment]
Thanks for reporting issue. We are looking into it.

**Comment by sfc-gh-dszmolka** [comment]
fixed with #662 , will be part of the next release, expected towards the end of June

**Comment by sfc-gh-igarish** [comment]
fix is released in 2.0.25
