### ISSUE TITLE
Question on how CLIENT_SESSION_KEEP_ALIVE works

### ISSUE THREAD

**Issue by davidhcar** [snowflakedb/snowflake-connector-net#590]
### Issue description
When CLIENT_SESSION_KEEP_ALIVE = true, the connection session kept open until the execution of the query for long running queries, that will run more than 4 hours. Once the query executed and returns result back to .Net process, we close the connection, and that session gets terminated, Is that correct understanding about this flag CLIENT_SESSION_KEEP_ALIVE ?

**Comment by colgreen-payroc** [comment]
@davidhcar  CLIENT_SESSION_KEEP_ALIVE  causes a background thread to call a /heartbeat endpoint to keep the session alive on the server. Withotu that call the sessions can timeout, as by default they have a 4 hour inactivity timeout on the sessions.

This is not about HTTP connections, but the session state maintained on the Snowflake server side.

The .NET connector nuget has a connection pool that expires the connections after 1 hour of not being used, therefore the four hour session timeout on the server should not be reached in normal circumstances (however, also see #606 which can increase the connection pool timeout to two hours when the clocks go back).

A pooled connection is either used, and the session expiry timer at the server is reset; or it is not used and is removed from teh pool after 1 hour.

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this question! also apologies for the long period without answer from Snowflake. i see now that colgreen-payroc already kindly answered it, so marking this one as closed. if there's any further concerns, please don't hesitate to comment.

**Comment by lnashier** [comment]
> CLIENT_SESSION_KEEP_ALIVE causes a background thread to call a /heartbeat endpoint to keep the session alive on the server. Without that call the sessions can timeout, as by default they have a 4 hour inactivity timeout on the server.

Does setting CLIENT_SESSION_KEEP_ALIVE to true keep compute resources active and cost money?

**Comment by sfc-gh-dszmolka** [comment]
as this quersion seems to be posted randomly in multiple Snowflake driver repositories, and i happened to bump into it on https://github.com/snowflakedb/gosnowflake/issues/1065 first, it was answered first.

It is highly encouraged to use the community forum instead for such discussion, instead of driver repositories.

**Comment by lnashier** [comment]
Thank you @sfc-gh-hchaturvedi for the response.

Also, my apologies for posting the question here and in other repos instead of community forums as I was not quite sure where to ask. Thanks for sharing the links for future reference.
