### ISSUE TITLE
.NET Framework 4.7.2 connection timeout unless WinHttpHandler.WindowsProxyUsePolicy = UseWinInetProxy

### ISSUE THREAD

**Issue by mgbo23** [snowflakedb/snowflake-connector-net#596]
### Issue description
My .NET Framework 4.7.2 console application connects to Snowflake using version 2.0.17 of the Snowflake .NET connector.

For Snowflake .NET Connector versions 2.0.18 through 2.0.20, my .NET Framework 4.7.2 console application receives a timeout error when connecting to Snowflake.

When I modify Snowflake.Data.Core.HttpUtil.setupCustomHttpHandler() create the WinHttpHandler object with WindowsProxyUsePolicy = WindowsProxyUsePolicy.UseWinInetProxy, my application connects without issue.

Before and after logs are included below.

### Example code
IDbConnection connection = new SnowflakeConnection();

connection.ConnectionString = account=[[account]];user=[[user]];password=[[password]];db=[[db]];schema=[[schema]];warehouse=[[warehouse]];role=[[role]];useProxy=true;proxyHost=[[proxyHost]];proxyPort=[[proxyPort]];proxyUser=[[proxyUser]];proxyPassword=[[proxyPwd]]";

connection.Open()

### Error log
**LOG WITH TIMEOUT ERROR:**

[SnowflakeLogWithTimeoutError.log](https://github.com/snowflakedb/snowflake-connector-net/files/10583230/SnowflakeLogWithTimeoutError.log)

**LOG WITH SUCCESSFUL CONNECTION - AFTER WinHttpHandler.WindowsProxyUsePolicy set to UseWinInetProxy**

[SnowflakeLogSuccessfulConnection.log](https://github.com/snowflakedb/snowflake-connector-net/files/10583235/SnowflakeLogSuccessfulConnection.log)

### Configuration
2.0.18, 2.0.19, 2.0.20

*Dotnet framework and version:* E.g. .net framework 4.5.2 or .net standard 2.0

.NET Framework 4.7.2

*Server version:* E.g. 1.90.1
7.3.2

*Client OS:* E.g. Debian 8.1 (Jessie), Windows 10

Microsoft Windows NT 6.2.9200.0

**Comment by sfc-gh-dszmolka** [comment]
hello and thank you for submitting this issue, also apologies for the long period without answer !

since you mentioned this issue is only with 2.0.18 and up, i would like to confirm whether it is caused by something introduced in 2.0.18 (like #615 ) or was it there before too ?

also, are you using the same proxy host / user / password in the connection settings, like you use in the browser/PAC config ?

**Comment by sfc-gh-dszmolka** [comment]
marking this one as closed due to inactivity, but please feel free to share the requested information on a comment if continued troubleshooting is needed.
