### ISSUE TITLE
Running Threads Limited to 2

### ISSUE THREAD

**Issue by rlewit** [snowflakedb/snowflake-connector-net#60]
### Issue description
When spawning 4 threads to Snowflake using a simple C# code in a small warehouse only 2 are running and none are queued.  The other 2 that are waiting run when the first 2 are done.   However if I spawn 4 programs, each running a simple query then everything appears correct with 2 running queries and 2 queued queries.

### Example code
```cs
c# project attached - You will need to connect to your own Snowflake account
[MultiThread Snowflake Tester.zip](https://github.com/snowflakedb/snowflake-connector-net/files/2349282/MultiThread.Snowflake.Tester.zip)

```

### Error log
```
NA
```
There is an example in READMD.md file showing you how to enable logging.

### Configuration
*Driver version:*
Snowflake.Data 1.0.3
*Dotnet framework and version:* E.g. .net framework 4.5.2 or .net standard 2.0
4.6.1
*Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```

*Client OS:* E.g. Debian 8.1 (Jessie), Windows 10

**Comment by ChTimTsubasa** [comment]
This is an know issue for .NET framework. The workaround for now is to have your application set ServicePointManager.DefaultConnectionLimit to be a value larger than 2.

**Comment by tdg5** [comment]
This issue should be closed since the specific issue is no longer a problem since https://github.com/snowflakedb/snowflake-connector-net/commit/5b7f805a#diff-12a62746f0d74cb001ec7b24c400ea1eR40
and the advice given is no longer relevant since that same line of code will override any user configured value

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
