### ISSUE TITLE
SnowflakeDbConnectionPool timeout has unintended behaviour during daylight savings transitions.

### ISSUE THREAD

**Issue by colgreen-payroc** [snowflakedb/snowflake-connector-net#606]
### Issue description

SnowflakeDbConnectionPool implements a time limit of 1 hour (TIMEOUT = 3600); the code for this is using the local timezone time, like so:

    DateTimeOffset.Now.ToUnixTimeSeconds()

This will cause two unintended behaviours for server's that have a local timezone that has daylight saving time changes...

1) When the local time moves forward 1 hour in (e.g. in the spring), all of the pooled connections will be deemed to be 1 hour older than they actually are, and all of the poled connections will be instantly expired at midnight local time.

2) When the local time goes back 1 hour (e.g. in the autumn), all of the pooled connections will be deemed to be 1 hour younger than they actually are, so the 1 hour timeout becomes 2 hours.

See;
SnowflakeDbConnectionPool.cs

Anywhere where DateTimeOffset.Now is used instead of DateTimeOffset.UtcNow.

**Comment by sfc-gh-igarish** [comment]
Thanks for reporting issue. We will look into it.

**Comment by sfc-gh-dszmolka** [comment]
this was fixed with #714 , and released with driver version [v2.1.0](https://github.com/snowflakedb/snowflake-connector-net/releases/tag/v2.1.0)
