### ISSUE TITLE
Basic .NET connectivity

### ISSUE THREAD

**Issue by rshenton** [snowflakedb/snowflake-connector-net#62]
### Issue description
ConnectionString should work with valid credentials, but doesn't: "Incorrect username or password was specified."
We were able to connect to Worksheets with the same credentials .

### Example code
scheme=https;port=443;user=THE_USER;password=THE_PASSWORD;account=OUR_STUFF.east-us-2.azure

### Error log
```

```
There is an example in READMD.md file showing you how to enable logging.

### Configuration
Snowflake.Data(1.0.4)

netcoreapp2.0

Windows Server 2012R2 in Azure

**Comment by howryu** [comment]
Can you try two other scenario?
1. Change the account name to <OUR_STUF> (without east-us-2.azure)
2. Check is password has special characters like `=`, `;`

**Comment by howryu** [comment]
Can you give me the log for the following setting: account <OUR_STUFF>, no east-us-2.azure and specify the HOST to be <OUR_STUFF>.east-us-2.azure.snowflakecomputing.com ?

**Comment by rshenton** [comment]
Log with account: <OUR_STUFF> and host: <OUR_STUFF>.east-us-2.azure.snowflakecomputing.com

[snowflake_dotnet.log](https://github.com/snowflakedb/snowflake-connector-net/files/2389869/snowflake_dotnet.log)

**Comment by howryu** [comment]
Seems HOST parameter got truncated as `<OUR_STUFF>.east-us-2.azure`, no `snowflakecomputing.com` in HOST value. I will try to reproduce it.

**Comment by rshenton** [comment]
Problem resolved. Thanks!
account: <OUR_STUFF> and host: <OUR_STUFF>.east-us-2.azure.snowflakecomputing.com
