### ISSUE TITLE
Compiler error after abgrading above 2.0.10

### ISSUE THREAD

**Issue by moravas** [snowflakedb/snowflake-connector-net#623]
Hi,

I tried to upgrade Snowflake.Data in my project above 2.0.10, e.g.: 2.0.11 and I get the following error messages:
`.cs(93,22): error CS0433: The type 'IAsyncEnumerable<T>' exists in both 'System.Interactive.Async, Version=3.2.0.0, Culture=neutral, PublicKeyToken=' and 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=' [.csproj]`

Until I'm not going above 2.0.10, it seems to work. This is my csporj file:
`
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="3.7.5.8" />
    <PackageReference Include="AWSSDK.Lambda" Version="3.7.8.7" />
    <PackageReference Include="Amazon.Lambda.SQSEvents" Version="1.2.0" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.7.5" />
    <PackageReference Include="AWSSDK.SimpleEmail" Version="3.7.0.109" />
    <PackageReference Include="AWSSDK.SQS" Version="3.7.2.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.JSON" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="5.0.0" />
    <PackageReference Include="Snowflake.Data" Version="2.0.10" />
    <PackageReference Include="System.Linq.Async" Version="6.0.1" />
    <PackageReference Include="System.Net.NameResolution" Version="4.3.0" />
  </ItemGroup>
</Project>
`

Can anybody help me, what did I wrong?

**Comment by myshon** [comment]
It seems that you don't need additional package System.Interactive.Async because it has been moved to System.Runtime since net6.
