### ISSUE TITLE
Using NULL valued Parameter - NotSupportedException

### ISSUE THREAD

**Issue by Ashok19r91d** [snowflakedb/snowflake-connector-net#63]
Using NULL valued Parameter throws NotSupportedException! I was trying to execute a Query `SELECT * FROM Table1 WHERE Column1 = COALESCE(:1, Column1);` as design this query expected return few data (all matched) when I supply value for `:1` and entire list when I submit `NULL` value for parameter `:1`; But I run with `NotSupportedException` on executing.

#61 seems to be similar to this.

**Comment by howryu** [comment]
@ChTimTsubasa This is the next important fix. Basically, we did not support binding null values.

**Comment by ChTimTsubasa** [comment]
@Ashok19r91d This is fixed and would be in for 1.0.10. Keep an eye on that version.

**Comment by Ashok19r91d** [comment]
Thanks team, due to lack of support to basic features, I was moved towards NodeJS driver for a time being... but now with improved features, I hope this the time to resume dev with DotNet driver.
