### ISSUE TITLE
net6.0, Ambiguous reference: System.Collections.Generic.IAsyncEnumerable

### ISSUE THREAD

**Issue by wdolek** [snowflakedb/snowflake-connector-net#633]
1. What version of .NET driver are you using?

  Snowflake.Data 2.0.22
   
2. What operating system and processor architecture are you using?

  Windows 10 (development), containerized Linux (runtime)
   
3. What version of .NET framework are you using?

  net6.0
   
4. What did you do?

  I want to use `IAsyncEnumerable<>` in my program but getting compiler error.

5. What did you expect to see?

  No compiler error 🤷 

---

I'm getting compiler error when trying to declare method like this in my program:

```csharp
public async IAsyncEnumerable<string> Fetch()
{
    throw new NotImplementedException();
}
```

```
Ambiguous reference: System.Collections.Generic.IAsyncEnumerable<out string> System.Collections.Generic.IAsyncEnumerable<out string> match
```
```
LeCode.cs(42, 42): [CS0433] The type 'IAsyncEnumerable<T>' exists in both 'System.Interactive.Async, Version=3.2.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' and 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

This is apparently caused by dependency chain:

- [`Google.Cloud.Storage.V1@2.5.0`](https://www.nuget.org/packages/Google.Cloud.Storage.V1/2.5.0)
- [`Google.Api.Gax.Rest@2.10.0`](https://www.nuget.org/packages/Google.Api.Gax.Rest/2.10.0)
- [`Google.Api.Gax@2.10.0`](https://www.nuget.org/packages/Google.Api.Gax/2.10.0)
- [`System.Interactive.Async@3.2.0`](https://www.nuget.org/packages/System.Interactive.Async/3.2.0)

Dependency on `Google.Cloud.Storage.V1` has been added in `Snowflake.Data@2.0.11`, ~year ago.

Related issue: #623.

---

Would it be possible to (and/or):

- update dependency on `Google.Cloud.Storage.V1`
- extract cloud specific code into separate library (e.g. `Snowflake.Data.Azure`, `Snowflake.Data.Aws`, `Snowflake.Data.Gcp`, ... I'm not sure whether all three are needed at same time)

I just stumbled on this issue while maintaining one of our older projects. I can't really tell what impact bumping up dependency will have, not to mention impact on other older framework versions. Unfortunately I won't be able to submit PR nor investigate further myself.

**Comment by plaisted** [comment]
Adding an explicit reference to version 4.4.0 seems to resolve the issue (`<PackageReference Include="Google.Cloud.Storage.V1" Version="4.4.0" />`) although not great since we aren't even using Google Cloud.

**Comment by sfc-gh-dszmolka** [comment]
thank you for raising this issue, we'll take a look

**Comment by sfc-gh-dszmolka** [comment]
not at this point, but if anything will be available I'll post it here

**Comment by sfc-gh-dszmolka** [comment]
thank you all for the patience here, fix is merged in #712 and will be part of the next upcoming release in July

**Comment by sfc-gh-dszmolka** [comment]
PR is released as part of the latest Snowflake .NET driver version 2.1.0. Closing this issue.

**Comment by julealgon** [comment]
I just lost around 2h of investigation time because of this insane dependency with Google.Cloud which in turn ends up depending on `System.Interactive.Async` that on older versions creates a conflict with `System.Linq.Async`.

Why on earth does this library depend on a Google.Cloud package in the first place?

**Comment by sfc-gh-dszmolka** [comment]
sorry to hear the tightly coupled dependencies caused a headache to you. currently this library depends on all 3 cloud providers even if you're not using it on a particular CP. 

 that one is handled in #517  / #612
