### ISSUE TITLE
Documentation says I need 2.0.4 to use proxy settings

### ISSUE THREAD

**Issue by hsavran** [snowflakedb/snowflake-connector-net#639]
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of .NET driver are you using?
2.0.22 latest as today
   
2. What operating system and processor architecture are you using?
Windows
   
3. What version of .NET framework are you using?
6.0
   
4. What did you do?
I am trying to connect by using proxy server

5. What did you expect to see?

able to connect

6. Problem
7. Your documentation says I need 2.0.4 or later version to use proxy settings. Latest version of this package is 2.0.22 and I can't find 2.0.4. Is this a typo problem in documentation or proxy server connect is not available yet.

**Comment by sfc-gh-dszmolka** [comment]
hi, the README.md says
> This parameter was introduced in v2.0.4.

which means you need to use _at least_ 2.0.4 version of the connector or higher. 2.0.22 is higher so should be good.

For an example, please see the text below "In v2.0.4 and later releases, you can configure the driver to connect through a proxy server.[..]" in README.md.
