### ISSUE TITLE
Excessive retries

### ISSUE THREAD

**Issue by colgreen-payroc** [snowflakedb/snowflake-connector-net#648]
This recent commit add rettry logic to RestRequester...

https://github.com/snowflakedb/snowflake-connector-net/commit/25498ddf4566d6af7d9688f22390abccf653de4d#diff-28552eb7d57bcb8b7f43eb5706654e031aaac0cf623630bbdfb8f7c9b61a93cf

However, there is already a retry loop in `HttpUtil.SendAsync()`. The new retry loop in RestRequester causeses calls the the inner try loop, and both have exponential back-off, thus causing very long overall wait for retries.

Separately, the retry loop in `HttpUtil.SendAsync()` has this code:

```
                    catch (Exception e)
                    {
                        if (cancellationToken.IsCancellationRequested)
                        {
                            logger.Debug("SF rest request timeout or explicit cancel called.");
                            cancellationToken.ThrowIfCancellationRequested();
                        }
                        else if (childCts != null && childCts.Token.IsCancellationRequested)
                        {
                            logger.Warn("Http request timeout. Retry the request");
                            totalRetryTime += (int)httpTimeout.TotalSeconds;
                        }
                        else
                        {
                            //TODO: Should probably check to see if the error is recoverable or transient.
                            logger.Warn("Error occurred during request, retrying...", e);
                        }
                    }
```

The final else block there causes an infinite retry loop for all exceptions other than cancellation token related exceptions. E.g. a HTTP request fails to connect then this loop is infinite. I suggest at least honouring the `disableRetries` boolean setting, like so:

```
                        else
                        {
                            //TODO: Should probably check to see if the error is recoverable or transient.
                            if(disableRetry)
                            {
                                throw;
                            }

                            logger.Warn("Error occurred during request, retrying...", e);
                        }
```

**Comment by sfc-gh-nwhite** [comment]
@colgreen-payroc Do you have a simple reproduction scenario and perhaps a log showing the behavior?  I'm going to work on reproducing it (by blocking access to a stage URL for result sets), but if you have a concrete repro and/or logs, that may help.

**Comment by sfc-gh-dszmolka** [comment]
since the initial issue submission, various enhancements and bugfixes were released. Please let us know if you still experience the issue with the recent versions of the Snowflake .NET driver and we can continue troubleshooting.
Thank you !
