### ISSUE TITLE
Snowflake connects successfully with faulty proxy connection parameters

### ISSUE THREAD

**Issue by howardwang0620** [snowflakedb/snowflake-connector-net#649]
### Issue description
Setting the `PROXYHOST` and `NONPROXYHOSTS` parameters to the same single-character value will directly connect to a Snowflake instance and bypass the proxy server, eg: `...USEPROXY=true;PROXYHOST=a;NONPROXYHOSTS=a;PROXYPORT=3128` connects successfully. 

If `PROXYHOST` and `NONPROXYHOSTS` are set to different or non-single-character values, eg: `...USEPROXY=true;PROXYHOST=ab;NONPROXYHOSTS=ab;PROXYPORT=3128` then the connection will try to go through the proxy server and then properly hangs and waits until timeout is reached.

_Driver version_: 2.0.22
_OS_: Mac Intel 13.3.1
_.NET framework_: 6.0.406

**Comment by sfc-gh-dszmolka** [comment]
thank you for submitting this issue, we're going to take a look
