### ISSUE TITLE
A command may be executed within an unexpected transaction

### ISSUE THREAD

**Issue by asiwjp** [snowflakedb/snowflake-connector-net#652]
If Close or Dispose is called for a Connection with an uncomplete transaction and this Connection is reused from the ConnectionPool, SQL commands will be executed in the old transaction scope.

1. What version of .NET driver are you using?
   2.0.23
   
2. What operating system and processor architecture are you using?
   Windows
   
3. What version of .NET framework are you using?
   4.7.2 and .NET6
   
4. What did you do?

    case 1:
      first user:
      - connection.BeginTransaction()
      - Rollback() failed, after connection.Close

      second user:
      - connection.Open() // In the first user transaction

      sample:
        [case1.txt](https://github.com/snowflakedb/snowflake-connector-net/files/11458019/case1.txt)

    case 2:

      first user:
      - execute BEGIN, after close
    
      second user:
      - open connection // In the first user transaction

      test code:
        [case2.txt](https://github.com/snowflakedb/snowflake-connector-net/files/11457985/case2.txt)

5. What did you expect to see?

    Connection obtained from ConnectionPool should always be in a state where no transaction has been started.

6. Can you set logging to DEBUG and collect the logs?

    if necessary.

**Comment by asiwjp** [comment]
#651

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this issue and the contribution in the PR is much appreciated ! we gonna take a look.

**Comment by sfc-gh-dszmolka** [comment]
a short update on this one: we confirmed this is indeed a problem even with the latest driver version. two possible workarounds until it's fixed
* disable connection pooling 😞 
OR
* make sure (in the application code) that all transactions finish with either a commit or a rollback

**Comment by asiwjp** [comment]
Thanks for the suggestion. I will consider it.😣
Hopefully one day the drivers themselves will fix it.

PS.
I thought there was a lack of consideration in the connection pool to reset the state of the connection.
Maybe your team should re-review it.

**Comment by asiwjp** [comment]
Thanks for the suggestion. I will consider it.😣
Hopefully one day the drivers themselves will fix it.

PS.
I thought there was a lack of consideration in the connection pool to reset the state of the connection.
Maybe your team should re-review it.

**Comment by sfc-gh-dszmolka** [comment]
so we _are_ working on the fix, the above suggestion is just a workaround for the period until the driver itself is fixed. i'll keep this Issue posted with the progress.

**Comment by sfc-gh-dszmolka** [comment]
#691

**Comment by sfc-gh-dszmolka** [comment]
PR is merged and will be part of the next release, expected towards end of July

**Comment by sfc-gh-dszmolka** [comment]
PR is released as part of the latest Snowflake .NET driver version 2.1.0. Closing this issue.
