### ISSUE TITLE
Array binding for IN Clause

### ISSUE THREAD

**Issue by dazinator** [snowflakedb/snowflake-connector-net#676]
## What is the current behavior?

After reading about array binding: https://github.com/snowflakedb/snowflake-connector-net#bind-array-variables
I thought I'd try and use array binding to paramterise an IN clause:

I get an exception - "Bind variable ? not set"

```

  using (var cmd = conn.CreateCommand())
            {
                List<string> myValues = new List<string>() { "KZ", "KR" };
                cmd.CommandText = "SELECT FOO FROM BAR WHERE FOO IN (?)";

                var p1 = cmd.CreateParameter();
                p1.ParameterName = "1";
                p1.DbType = DbType.String;
                p1.Value = myValues .ToArray();
                cmd.Parameters.Add(p1);

                using (var reader = cmd.ExecuteReader())
                {
                    while (reader.Read())

```

## What is the desired behavior?

Perhaps this could be supported?

## How would this improve `snowflake-connector-net`?

Make it easier to paramaterise queries with In clauses.

**Comment by sfc-gh-dszmolka** [comment]
hi - i think we can use https://github.com/snowflakedb/snowflake-connector-net/issues/169 to track this requirement for VARIANT (and ARRAY) binding, but if this is something entirely different please let me know
