### ISSUE TITLE
Uploading files to internal stage with '*' wild card in path(filename). Exception, invalid characters in path. 

### ISSUE THREAD

**Issue by timfnz** [snowflakedb/snowflake-connector-net#682]
1. What version of .NET driver are you using?
2.0.24
   
2. What operating system and processor architecture are you using?
Windows 11, 64 bit
   
3. What version of .NET framework are you using?
.net framework  4.7.1
   
4. What did you do?

    var filepath = Path.Combine(tableDefinition.OutputFolder, $"outputfile*");

                using (var dbConection = new SnowflakeDbConnection(tableDefinition.ConnectionString))
                {
                    //dbConection.ConnectionTimeout = 0;      
                    dbConection.Open();
                    using (var command = new SnowflakeDbCommand(dbConection,$"put file://{filepath}* @{tableDefinition.Stage} auto_compress=false;"))
                    {
                        command.CommandTimeout = 0;
                        command.ExecuteNonQuery();
                    }
                    dbConection.Close();
                };

5. What did you expect to see?
The code works with the Odbc connector.
The exception is happening in SFFileTransferAgent.expandFileNames(string location), code:
 if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
      {
          location = Path.GetFullPath(location);
      }
perhaps it should do this after it splits the filename off.

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for submitting this issue; indeed looks a bit unexpected especially that ODBC driver can handle it properly (confirmed). we'll take a look.

**Comment by sfc-gh-dszmolka** [comment]
#722

**Comment by sfc-gh-dszmolka** [comment]
change is merged and will be part of the next upcoming driver release, expected towards end of August.

**Comment by sfc-gh-dszmolka** [comment]
fix released with 2.1.1 version of the driver.
