### ISSUE TITLE
Upgrade precommit secret-scanner

### ISSUE THREAD

**Issue by sfc-gh-pmotacki** [snowflakedb/snowflake-connector-net#700]
## What is the current behavior?
We use old version of secret scanner lib - 1.3

## What is the desired behavior?
Using of newest version of secret-scanner

## How would this improve `snowflake-connector-net`?
We will be up-to-date with controlling of secrets in code before commit

**Comment by sfc-gh-dszmolka** [comment]
fixed with https://github.com/snowflakedb/snowflake-connector-net/pull/701
