### ISSUE TITLE
Snowflake . net Framefowrk - I am getting error 390100 - Incorrect username or password was specified

### ISSUE THREAD

**Issue by RAKshirsagar** [snowflakedb/snowflake-connector-net#76]
Snowflake.Data 1.0.4

Here is the connection string - 
conn.ConnectionString = "scheme=https;host=prod.us-east-1.**.snowflakecomputing.com;user=***;password=**;account=prod.us-east-1.**;";

conn.Open();
IDbCommand cmd = conn.CreateCommand();
cmd.CommandText = "select * from table";
IDataReader reader = cmd.ExecuteReader();

I am getting Incorrect username or password was specified error.

**Comment by rshenton** [comment]
I had a similar problem with the documentation being a bit wonky. The documentation suggests that everything before '.snowflakecomputing.com' is part of the account, but this is not always true. The appropriate pattern for us is:

host=account_name_here.east-us-2.azure.snowflakecomputing.com;
account=account_name_here;

**Comment by josefarinna** [comment]
I'm having the same issue, but I think that the issue could be caused because our username is an email address and seems that the connector doesnt support the @.

**Comment by Ferprimart** [comment]
Hi all,

I'm facing same problems... Not able to use the nuget package, as a workaround by the moment Im using the ODBC connector.

**Comment by howryu** [comment]
@rshenton @josefarinna  Do you use Okta or SSO for authentication? If yes, then this is expected since SSO is not supported for now.

**Comment by Ferprimart** [comment]
Hi @howryu we are using the connection like that:

`using (IDbConnection conn = new SnowflakeDbConnection())
            {
                conn.ConnectionString = "ACCOUNT=XXXXXX.east-us-2.azure;USER=fff@yyy.com;PASSWORD=ggg";

                conn.Open();

                conn.Close();
            }`

And we are getting the error of "Incorrect username or password was specified", we are not using SSO neighter Okta. We are using the same credentials for accessing to the web interface and it's working fine.


Thanks.

**Comment by ikudjoi** [comment]
I had similar problems with the connection string. A cs like this worked for me:
"ACCOUNT=XXXXXX;HOST=XXXXXX.east-us-2.azure.snowflakecomputing.com;USER=fff@yyy.com;PASSWORD=ggg";

So the region information in this context does not belong to the account but to explicitly defined host.

**Comment by Ferprimart** [comment]
@ikudjoi It worked!!! Thanks so much for your comment 👍

**Comment by howryu** [comment]
Thanks everyone for the response. I will update the doc to explicitly indicate that account name should not include region or cloud provider info.
