### ISSUE TITLE
SNOW-903956: Add CloseAsync() that calls CloseAsync(CancellationToken)

### ISSUE THREAD

**Issue by aschwenker-insight** [snowflakedb/snowflake-connector-net#762]
## What is the current behavior?

The Snowflake Driver (`SnowflakDbConnection`) has a `Close()` and a `CloseAsync(CancellationToken)` method.  These methods have similar but not the same implementation.  `SnowflakeDbConnection` extends `DbConnection`, which has a `virtual CloseAsync()` method.  `DbConnection`'s `CloseAsync()` method simply calls `Close()`.

If a user has a handle to `SnowflakeDbConnection` as a `DbConnection`, they only have access to `CloseAsync()` and not `CloseAsync(CancellationToken)`.

## What is the desired behavior?

`SnowflakeDbConnection` should override `CloseAsync()` and have it call `CloseAsync(CancellationToken.None)`.

## How would this improve `snowflake-connector-net`?

Users could have a handle to `DbConnection` instead of `SnowflakeDbConnection`, which improves portability and SOLID in their code.

## References, Other Background

This is fixed in PR #538

**Comment by sfc-gh-dszmolka** [comment]
hello and thank you for your contribution, also opening this Issue to track why the PR is necessary! we'll take a look.

**Comment by sfc-gh-pbulawa** [comment]
Thank you for the contribution. Your PR has been merged.

**Comment by sfc-gh-dszmolka** [comment]
fix is now out with release [2.1.2](https://github.com/snowflakedb/snowflake-connector-net/tree/v2.1.2)
