### ISSUE TITLE
SNOW-905751: Snowflake.Data connection failed in linux, succeeded in windows

### ISSUE THREAD

**Issue by dreamGirl1996** [snowflakedb/snowflake-connector-net#767]
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of .NET driver are you using?
2.0.0 or 2.1.1

   
3. What operating system and processor architecture are you using?
linux

   
5. What version of .NET framework are you using?
net6.0
   
6. What did you do?
When I run following code in windows, it connection opened. While run in linux, it throws:
Unhandled exception. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Snowflake.Data.Core.RestRequester.Post[T](IRestRequest request)
   at Snowflake.Data.Core.Authenticator.BaseAuthenticator.Login()
   at Snowflake.Data.Core.Authenticator.BasicAuthenticator.Snowflake.Data.Core.Authenticator.IAuthenticator.Authenticate()
   at Snowflake.Data.Core.SFSession.Open()
   at Snowflake.Data.Client.SnowflakeDbConnection.Open() -- .NET driver 2.0.0

Error Message: Error: Snowflake Internal Error: Unable to connect. One or more errors occurred. (A task was canceled.) SqlState: 08006, VendorCode: 270001, QueryId: -- .NET driver 2.1.1

using (IDbConnection conn = new SnowflakeDbConnection())
{
    conn.ConnectionString = "password=xxx;account=xxx;user=xxx;db=xxx;warehouse=xxx;role=xxx;host=xxx;region=xxx";

    conn.Open();
}

7. What did you expect to see?

   Connection succeeds in linux, thanks

8. Can you set logging to DEBUG and collect the logs?

   https://community.snowflake.com/s/article/How-to-generate-log-file-on-Snowflake-connectors
   
   There is an example in READMD.md file showing you how to enable logging.
9. What is your Snowflake account identifier, if any? (Optional)

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for submitting this issue. I tried to reproduce it but couldn't yet. Here's the steps I've taken in an attempt to reproduce it.

### Set up environment

```
$ docker run --rm -ti mcr.microsoft.com/dotnet/sdk:6.0 /bin/bash

root@03192d178f3c:/test# dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.21 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.21 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

root@03192d178f3c:/test# grep ^PRETTY /etc/*release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

root@03192d178f3c:/test# dotnet new console
[..gets initialized..]

root@03192d178f3c:/test# dotnet add package Snowflake.Data --version 2.1.1
[..Snowflake .NET Driver 2.1.1 gets installed..]
```

### Repro program
```dotnet
# cat Program.cs 
using System;
using System.Data;
using System.Data.Common;
using Snowflake.Data.Client;
namespace SnowflakeTestProgram 
{
    class Program
    {
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        static void Main(string[] args)
        {
            try
            {
                using (IDbConnection conn = new SnowflakeDbConnection())
                {
                    conn.ConnectionString = "account=myaccount; user=admin; password=mypassword; DB=TEST_DB; SCHEMA=PUBLIC";
                    conn.Open();
                    Console.WriteLine("Connection successful!");
                    using (IDbCommand cmd = conn.CreateCommand())
                    {
                        cmd.CommandText = "select current_user()"; 
                        IDataReader reader = cmd.ExecuteReader();
                        while (reader.Read())
                        {
                            Console.WriteLine(reader.GetString(0));
                        }
                        conn.Close();
                    }
                }
            }
            catch (DbException exc)
            {
                Console.WriteLine("Error Message: {0}", exc.Message);
            }
        }
    }
}
```

### Run the repro program
```
root@03192d178f3c:/test# dotnet run Program.cs 
/test/Program.cs(9,81): warning CS8602: Dereference of a possibly null reference. [/test/test.csproj]
Connection successful!
ADMIN
```

Successfully connects to Snowflake and executes a query.

So can confirm Snowflake .NET Driver version 2.1.1 does work under Linux. But perhaps your situation is different from the above setup.

For next step, could you please send
* the exact steps of setting up the environment / details of the OS, runtime, etc. seen above
* the full runnable code you're using, which is a minimal viable representation of the issue reproduction

I would like to use a repro as closely resembling your situation as possible. Thank you in advance !

**Comment by sfc-gh-dszmolka** [comment]
there's been no response on this for a while now, so marking it closed. If you require further help, please answer the questions accordingly and/or provide reproduction/logs, and I'll reopen the issue.
