### ISSUE TITLE
Test SFDbDataReaderIT.testGetDateTime fails on time zones ahead of UTC

### ISSUE THREAD

**Issue by ikudjoi** [snowflakedb/snowflake-connector-net#79]
### Issue description
First change your time zone to e.g. Europe/Helsinki, EEST, +3:00.
When running the mentioned test the assert
```cs
Assert.AreEqual(0, DateTime.Compare(today, reader.GetDateTime(0)));
```
fails, the Compare method returns 1 when the test is executed on a time zone that is ahead of UTC. Test should be runnable on any time zone.

The reason for this seems to be that the test tries to insert DateTime.Today to a date field. The time is compared to Unix Epoch UTC time and e.g. on my time zone EEST +3 the calculated time difference is three hours short of a full 24 hours. On western hemisphere this is not a problem because the calculation results in extra hours that will be floored away. Yesterday's date is written to the table instead of the date of currenct date. My suggestion would be to use DateTime.UtcNow.Date instead of DateTime.Today in the test.

### Error log
```
Starting test execution, please wait...
Failed   testGetDateTime
Error Message:
   Expected: 0
  But was:  1

Stack Trace:
   at Snowflake.Data.Tests.SFDbDataReaderIT.testGetDateTime() in C:\work\snowflake-connector-net\Snowflake.Data.Tests\SFDbDataReaderIT.cs:line 181
```

### Configuration
*Driver version:*
1.0.4

*Dotnet framework and version:*
.net standard 2.0

*Server version:*
3.0.5

*Client OS:*
Windows 10

**Comment by howryu** [comment]
Thanks for the fix. Merged in #80
