### ISSUE TITLE
Can you guys please add GetSchemaTable() into the library 

### ISSUE THREAD

**Issue by CPavanKishore** [snowflakedb/snowflake-connector-net#8]
while i try to get the GetSchemaTable() schema of the table it shows method isn't there can you please try to add that

**Comment by CPavanKishore** [comment]
Going into break mode if I would have requested to get 40k or more records any alternative for this....?

**Comment by howryu** [comment]
I will add this to backlog.

**Comment by CPavanKishore** [comment]
does this added in the release v3.0 ......?

**Comment by howryu** [comment]
No, this is not done yet.

**Comment by abelykh0** [comment]
Please consider my implementation https://github.com/snowflakedb/snowflake-connector-net/pull/57

**Comment by howryu** [comment]
Merged in #58
