### ISSUE TITLE
SNOW-950923: SnowflakeDbCommand.GetQueryId() returns null on PUT cmd

### ISSUE THREAD

**Issue by sfc-gh-agoldberg** [snowflakedb/snowflake-connector-net#802]
When I Execute a PUT command and then use GetQueryId on the command object which executed - it returns null.
I haven't seen this with any other command.

Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of .NET driver are you using?
2.1.2
   
3. What operating system and processor architecture are you using?
Tested on Mac (M2) and PC (Win11/x64)
   
4. What version of .NET framework are you using?
   netcore 7.0.12
   
5. What did you do?

SnowflakeDbCommand command = new SnowflakeDbCommand(_connection, "PUT file://path/to/file.csv @stage_name");
System.Data.Common.DbDataReader reader = command.ExecuteReader() ;
string queryId = command.GetQueryId(); // this returns null

6. What did you expect to see?
I expect a valid query Id

7. Can you set logging to DEBUG and collect the logs?
let me know if this is needed - can try later.

9. What is your Snowflake account identifier, if any? (Optional)

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this issue  - also appreciate the code snippet ! reproduced the same issue with the latest (2.1.2 at the time of writing) version of the driver; also observed that `GET` command is similarly affected, not only `PUT`.

We'll take a look.

**Comment by sfc-gh-mhofman** [comment]
It will be available on the command level as well

**Comment by sfc-gh-dszmolka** [comment]
PR is https://github.com/snowflakedb/snowflake-connector-net/pull/825

**Comment by sfc-gh-mhofman** [comment]
@sfc-gh-dszmolka Code is ready however it introduces a BCR and will get released along with other bigger breaking changes in Q1.

**Comment by sfc-gh-dszmolka** [comment]
hey @sfc-gh-mhofman thanks for the heads-up, this is great news! Do we have any estimation when this could be; together with the regular driver release cycle in February or some other time?

**Comment by sfc-gh-mhofman** [comment]
@sfc-gh-dszmolka worse case March release cc @sfc-gh-knozderko

**Comment by sfc-gh-mhofman** [comment]
@sfc-gh-dszmolka planned for the Feb release

**Comment by sfc-gh-dszmolka** [comment]
PR is now merged and will be part of the next release which is imminent.

**Comment by sfc-gh-dszmolka** [comment]
fix released with version 3.0.0, closing Issue
