### ISSUE TITLE
SNOW-970857: Parameter DbType should track explicit assignment rather than hard default to AnsiString

### ISSUE THREAD

**Issue by mgravell** [snowflakedb/snowflake-connector-net#813]
Currently `DbType` is a basic auto-implemented property: https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data/Client/SnowflakeDbParameter.cs#L37

This causes problems because it defaults to `AnsiString` (value zero) ([because](https://learn.microsoft.com//dotnet/api/system.data.dbtype))

To complicate things: multiple providers have types where setting the `DbType` is *actively discouraged*, because they will use additional types internally when assigned. This means that provider-agnostic tools (think "Dapper") actively choose *not* to set this property in those cases, which [causes problems](https://github.com/DapperLib/Dapper/issues/1725).

The way most providers do this is to track explicit assignment; if it has never *actively* been assigned a value, then the `get` value is inferred from the `.Value` (or other mechanisms).

Examples:

- https://github.com/npgsql/npgsql/blob/main/src/Npgsql/NpgsqlParameter.cs#L314
- https://github.com/dotnet/SqlClient/blob/d30d9d107eca0f11b735a550aa187e57167858c9/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlParameter.cs#L462

I suggest this provider should do something similar, to avoid the problem where if `DbType` is not set, things are sent as `AnsiString`

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this issue and especially for the detailed description of how this would be useful ! we'll take a look at this enhancement request.

**Comment by amis92** [comment]
@sfc-gh-dszmolka please prioritize this, we're forced to use no longer supported versions (1.x) due to this. I'd classify this as a bug, as a matter of fact.

**Comment by sfc-gh-dszmolka** [comment]
Sure - let us sync internally and the driver team can decide what's the best to move forward with this issue. Thank you for bearing with us !

**Comment by sfc-gh-dszmolka** [comment]
PR in review https://github.com/snowflakedb/snowflake-connector-net/pull/889

**Comment by sfc-gh-dszmolka** [comment]
PR merged and fix will be part of the 2024 April release, towards the end of month
