### ISSUE TITLE
Add basic DbProviderFactory implementation to the project

### ISSUE THREAD

**Issue by ikudjoi** [snowflakedb/snowflake-connector-net#83]
### Issue description
To add support for Snowflake to Fluent Migrator project (https://github.com/fluentmigrator/fluentmigrator) the connector must implement _System.Data.Common.DbProviderFactory_, whose purpose is

> Represents a set of methods for creating instances of a provider's implementation of the data source classes.

In my experience very basic implementation is sufficient in the first place to allow using Fluent Migrator for Snowflake database migrations.

**Comment by howryu** [comment]
Merged in #89
