### ISSUE TITLE
SNOW-993872: System.NullReferenceException when executing Command when CommandText is not set

### ISSUE THREAD

**Issue by felixtsem5** [snowflakedb/snowflake-connector-net#838]
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of .NET driver are you using?

2.1.4
   
2. What operating system and processor architecture are you using?

Any
   
3. What version of .NET framework are you using?
   E.g. .net framework 4.5.2 or .net standard 2.0

.NET 6   

4. What did you do?

   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.

Exception below is thrown when trying to run an ExecuteNonQuery()/ExecuteScalar() on a SnowflakeDbCommand object with no CommandText.
System.NullReferenceException: 'Object reference not set to an instance of an object.'

5. What did you expect to see?

   What should have happened and what happened instead?

Just state that CommandText is not there or empty.

6. Can you set logging to DEBUG and collect the logs?

   https://community.snowflake.com/s/article/How-to-generate-log-file-on-Snowflake-connectors
   
   There is an example in READMD.md file showing you how to enable logging.

No, but I bet not checking the existence of the actual SQL in the TrimSql() method is why.
https://github.com/snowflakedb/snowflake-connector-net/blob/aaa32fd189247447559257de67cc1eb1facc29dc/Snowflake.Data/Core/SFStatement.cs#L652

Here's the partial stack trace:

   at Snowflake.Data.Core.SFStatement.TrimSql(String originalSql)
   at Snowflake.Data.Core.SFStatement.Execute(Int32 timeout, String sql, Dictionary`2 bindings, Boolean describeOnly)
   at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteNonQuery()
[... My code after this]

7. What is your Snowflake account identifier, if any? (Optional)

**Comment by sfc-gh-dszmolka** [comment]
hi - thank you for submitting this issue. we'll take a look.

**Comment by sfc-gh-dszmolka** [comment]
PR is made and is under review at https://github.com/snowflakedb/snowflake-connector-net/pull/861

**Comment by sfc-gh-dszmolka** [comment]
fix released with version 3.0.0, closing Issue
