### ISSUE TITLE
SNOW-1010656: Portable.BouncyCastle Version 1.8.10 is outdated

### ISSUE THREAD

**Issue by MasterKuat** [snowflakedb/snowflake-connector-net#850]
Hi,

Please update dependancy with Portable.BouncyCastle Version 1.9

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for drawing our attention to this - we'll take a look

**Comment by sfc-gh-dszmolka** [comment]
addressed in https://github.com/snowflakedb/snowflake-connector-net/pull/857

**Comment by sfc-gh-dszmolka** [comment]
fix released with version 3.0.0, closing Issue
