### ISSUE TITLE
SNOW-1018279: After Version 2.1.5 Snowflake.Data makes a new Network Egress call which can be blocked in networking

### ISSUE THREAD

**Issue by sgroznyvarde** [snowflakedb/snowflake-connector-net#855]
1. What version of .NET driver are you using?
2.1.5 and 2.2.0
   
2. What operating system and processor architecture are you using?
AWS Lambda running .NET 6.0 
   
3. What version of .NET framework are you using?
 .NET 6.0 
   
4. What did you do?
We have a lambda in a VPC that makes a Snowflake DB connection. After upgrading from 2.1.3 to 2.2.0 we started getting timeouts opening the Snowflake connection. No code changes were made outside of the update, and our logs showed specifically that a `connection.open()` line was the last action take by the lambda before a timeout. This only occurred in the code deployed to the lambda but not from my local machine, which continued to work as expected.

5. What did you expect to see?
Ideally we expected that the lambda Snowflake connectivity would continue to work instead of timing out. After some investigation we found that our VPC security group needed an extra egress port added on an additional port(we opened up everything, and have not narrowed down the actual port being used). We had 443 already open, but after the update to 2.1.5 and 2.2.0 we needed another port open. This lambda makes a simple Snowflake query formats the data and returns it so no other processes would have required this extra port.

We have mitigated the error by opening egress traffic to all ports. Please let us know what port we need traffic opened to so we can secure our lambda a bit more

Also note, we tried every version from 2.13, 2.1.4, 2.15, and 2.2.0. Our connectivity started breaking on version 2.1.5

![image](https://github.com/snowflakedb/snowflake-connector-net/assets/131011853/a1cd15e7-f1fb-4ab5-83d4-febfc2e72ede)

**Comment by sfc-gh-dszmolka** [comment]
> Also note, we tried every version from 2.13, 2.1.4, 2.15, and 2.2.0. Our connectivity started breaking on version 2.1.5

On this one: we fixed an important security hole with 2.1.5 (was there between 2.0.25 - 2.1.4) where on the affected versions the driver _would not_ contact the CRL hosts for certificate verification. This was unexpected behaviour and result of a bug. 
More details in the security advisory we published in this same repo: https://github.com/snowflakedb/snowflake-connector-net/security/advisories/GHSA-hwcc-4cv8-cf3h

Starting from 2.1.5 the driver again behaves as expected -> contacts the CRL hosts on port 80. This is likely the explanation to the behaviour you're seeing.
