### ISSUE TITLE
SNOW-1203768: Does setting CLIENT_SESSION_KEEP_ALIVE to true keep compute resources active and cost money?

### ISSUE THREAD

**Issue by lnashier** [snowflakedb/snowflake-connector-net#882]
### Issue description
It is unclear whether setting CLIENT_SESSION_KEEP_ALIVE to true keep compute resources active and cost money?

**Comment by sfc-gh-dszmolka** [comment]
thank you, marking this as closed (was answered in one of the duplicates on https://github.com/snowflakedb/gosnowflake/issues/1065)
