### ISSUE TITLE
SNOW-1230345: Issue 605 still not working for role, warehouse, other tokens in the connection string that may contain spaces

### ISSUE THREAD

**Issue by andrehartmann1968** [snowflakedb/snowflake-connector-net#888]
https://github.com/snowflakedb/snowflake-connector-net/issues/605

You may have fixed this for the database, but other tokens like the role and the warehouse also support spaces in their names. Even with the current version 3.0.0 this does not work. I still cannot upgrade the usage of the package beyond 2.0.17 because of this phenomenon. Could you please re-open this and fix it once and for good?

**Comment by sfc-gh-dszmolka** [comment]
PR under review https://github.com/snowflakedb/snowflake-connector-net/pull/891

**Comment by sfc-gh-dszmolka** [comment]
PR merged and fix will be released with the next version of the driver, towards end of March

**Comment by andrehartmann1968** [comment]
> PR merged and fix will be released with the next version of the driver, towards end of March

Sounds spiffing, great job!

**Comment by sfc-gh-dszmolka** [comment]
issue should be fixed now as the PR has been released with .NET driver 3.1.0. please feel free to test it out and let us know if you still see issues.
