### ISSUE TITLE
SNOW-1265394: Unable to resolve dependency 'Mono.Unix'. Source(s) used: 'nuget.org', 'Axiom', 'Microsoft Visual Studio Offline Packages'.				

### ISSUE THREAD

**Issue by greenmodulus** [snowflakedb/snowflake-connector-net#895]
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of .NET driver are you using?

   
2. What operating system and processor architecture are you using?
Windows 11 x64
   
3. What version of .NET framework are you using?
.net framework 4.7.2
   
4. What did you do?

Opened nuget package manager.  Searched for Snowflake.data.  Clicked install.  Got the above error.

5. What did you expect to see?

Snowflake.data should have installed.

6. Can you set logging to DEBUG and collect the logs?

7. What is your Snowflake account identifier, if any? (Optional)

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this Issue with us! Apparently `Mono.Unix` (which has been added as a dependency with Snowflake .NET driver 3.0.0) is [considered prerelease](https://www.nuget.org/packages/Mono.Unix/) so by default does not get installed.

You can try the following:
1. Enable installing prerelease packages too in NuGet, per [this Microsoft article](https://learn.microsoft.com/en-us/nuget/create-packages/prerelease-packages#installing-and-updating-pre-release-packages)
OR
2. in your project, open NuGet package manager console (in VisualStudio it's Tools > Nuget Package Manager > Package Manager console), then after Powershell is loaded, issue this command to install `Mono.Unix`:
`NuGet\Install-Package Mono.Unix -Version 7.1.0-final.1.21458.1`
afterwards, retry installing `Snowflake.Data` (v3.0.0) which now should be successful
OR
3. if for some reason you don't want to use either of the above approaches, install the older `Snowflake.Data` v2.2.0 which does not yet depend on `Mono.Unix`

Hope this helps but let us know if you need any further help.

**Comment by MKentV** [comment]
I also used the direct installation via the Nuget command line and it resolved the error for me. Thanks!
