### ISSUE TITLE
Time travel data is not available for table X

### ISSUE THREAD

**Issue by denyss-digiterre** [snowflakedb/snowflake-connector-net#92]
Hi! I am trying to get the auto-generated ```IDENTITY``` key which is a basic piece of typical ```INSERT``` scenarios.

```sql
CREATE TABLE IF NOT EXISTS MyTable(
    Id INT IDENTITY(1, 1) NOT NULL,
    DoesNotMatter INT NULL);

INSERT INTO MyTable (999);
SELECT MAX(Id) FROM MyTable AT (STATEMENT => LAST_QUERY_ID());
```
Error:
```
'Time travel data is not available for table MyTable.'
```
The above works through the Snowflake query HTML page.

I suspect that the driver injects an extra statement/query between ```INSERT``` and ```SELECT``` or maybe affects session otherwise? And also the driver does not support running more than two commands/queries per command execution. As the result there is nothing usable that would give ```@@IDENTITY``` functionality crucial for ```INSERT```. Please let me know if it's a bug or I am doing something wrong.

And of course documentation around the error above is very-very-very-very-*very* lacking. Google search gives just one exact match. It would be great to list more reasons than **1** as it seems that time travel is one of more advertised features of the product. Thank you and looking forward to some direction/solution.

**Comment by howryu** [comment]
@denyss-digiterre .net driver will not inject queries. The only thing might be related is when you change session's database/schema, driver will issue queries like `use database XX` or `use schema xx` You can double check if any queries run by checking query history through UI or sql command (https://docs.snowflake.net/manuals/sql-reference/functions/query_history.html)

**Comment by howryu** [comment]
Also can you share the sample code to reproduce the issue?

**Comment by manigandham** [comment]
@denyss-digiterre The `INSERT` statement looks off, and that doesn't work when running separately in the console when I tried. 

This works though:
```
CREATE TABLE IF NOT EXISTS MyTable(Id INT IDENTITY(1, 1) NOT NULL, DoesNotMatter INT NULL);
INSERT INTO MyTable (DoesNotMatter) VALUES(999);
SELECT MAX(Id) FROM MyTable AT (STATEMENT => LAST_QUERY_ID());
```

Can you confirm?

**Comment by howryu** [comment]
@denyss-digiterre Any more update? If not, I will close the issue.
