### ISSUE TITLE
SNOW-1463600: Snowflake.Net is an option in the list of SSIS/SSAS connections and working

### ISSUE THREAD

**Issue by christiansanc** [snowflakedb/snowflake-connector-net#963]
Hello everyone,
We have managed to get the SSAS DLL (OLAP Cubes and working correctly), we would be interested in contributing our improvements for its operation, for this you can tell us where we can do it because we do not see any option of “Contributions”. 
We have seen that this topic is of interest as an example:
https://github.com/snowflakedb/snowflake-connector-net/issues/102

**Comment by sfc-gh-dszmolka** [comment]
hello there - depending on the level of collaboration you're planning, there might be multiple approaches.
1. we accept PRs in this repository - just raise it, and we'll reviewing them periodically
2. if the collaboration goes beyond 1-2 PRs or would require more profound changes; the best approach perhaps would be to reach out to your Snowflake account team who can then help you to collaborate directly with the product management and all other teams involved

Hope this helps but let me know please if you have some other questions or had something entirely different in mind

**Comment by sfc-gh-dszmolka** [comment]
closing this questions as it has been answered now, but if you have further questions in this topic please do comment and I'll reopen if necessary

**Comment by christiansanc** [comment]
Good morning, we have reviewed and the simple modifications we are going to collaborate from here by opening Pull request and the more complex ones with the snowflake partnets, we have tried to create Pull request but it does not allow us because we are not collaborators, what steps should we follow? All the best

**Comment by sfc-gh-dszmolka** [comment]
multiple PRs from external contributors are submitted against this repo (https://github.com/snowflakedb/snowflake-connector-net/pulls, look for submitter name other than sfc-gh) and none of them are Collaborators, so something is perhaps missing in your procedure.  Are you trying to directly commit into `main` branch perhaps?
Can you please try forking the driver then create a PR from there ?

**Comment by christiansanc** [comment]
I can´t
![Captura de pantalla 2024-06-18 121630](https://github.com/snowflakedb/snowflake-connector-net/assets/171688375/553f4bb9-cb4a-48f3-9a3e-50e75bd316fa)

**Comment by pgr-rick-schulte** [comment]
Hi [christiansanc](https://github.com/christiansanc) I'm extremely interested in how you got it working with SSAS and SISS(?) I attempted in the past I've Gac'd it and added to the machine.config. it sees the provider but error sin the GUI. Now it's strongly named it should make it easier,  - what did you do ?
