### ISSUE TITLE
SNOW-1502317: Nonrecoverable HttpRequestExceptions are retried in HttpUtil.cs

### ISSUE THREAD

**Issue by dmarkle** [snowflakedb/snowflake-connector-net#981]
On about line 408-410 of HttpUtil.cs, you have a comment with a TODO to check to see if the error is recoverable or transient.  Yes, you definitely should do that.  

We encountered a 'http request failed and max retry 7 reached" error.  I cloned the Snowflake.Data repo and stepped through it.  HttpRequestException / Inner Exception AuthenticationException was actually thrown, which is nonrecoverable, but you don't check for it.  

In our case, we were getting this;
The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown

Presumably this is down to the fact that we're using Netskope and the cert being used by the Netskope tunnel is missing the revocation list property.  We're working on fixing this on our end, of course, but this is a non-recoverable error where it would have been nice to see the actual error instead of "stop retry as maxHttpRetries {maxRetryCount} reached".

**Comment by sfc-gh-dszmolka** [comment]
hi, thanks for raising this - fully agree, some requests should not be retried; there's little chance that the invalid credentials or the intercepted SSL cert will be fixed before automatic retry.  We'll take a look. Also appreciate the fix suggestion !

**Comment by sfc-gh-dszmolka** [comment]
PR under review https://github.com/snowflakedb/snowflake-connector-net/pull/1013

**Comment by sfc-gh-dszmolka** [comment]
change is merged, and will be part of the next upcoming release - will share once more is known of its expected timeline

**Comment by sfc-gh-dszmolka** [comment]
released with Snowflake .NET driver v4.2.0 in October 2024 release cycle
