### ISSUE TITLE
403 when fetching chunks from S3

### ISSUE THREAD

**Issue by brendenblack** [snowflakedb/snowflake-connector-net#99]
### Issue description
When querying Snowflake, I was hitting the timeout period with an error message saying the task was cancelled. 

After some investigation, it happens when Snowflake stores the results in S3. The driver was receiving a 403 when trying to fetch the chunks, and using a retry backoff repeatedly until the timeout value was met. 

It turns out that our Snowflake instance is not returning a "_qrmk_" value, and so 
[RestRequestImpl](https://github.com/snowflakedb/snowflake-connector-net/blob/v1.0.5/Snowflake.Data/Core/RestRequestImpl.cs#L110) sends the headers:
```
{
  x-amz-server-side-encryption-customer-algorithm: AES256
  x-amz-server-side-encryption-customer-key: 
} 
```

The customer key being blank is causing the 403. When the provided URL is tried using no headers (a get request from incognito mode or Postman) the result is returned. I added a check that avoids setting the headers when _qrmk_ is null and run tests using the driver and had success, e.g.:
```
if (!string.IsNullOrWhiteSpace(getRequest.qrmk)
{
  message.Headers.Add(SSE_C_ALGORITHM, SSE_C_AES);
  message.Headers.Add(SSE_C_KEY, getRequest.qrmk);
}
```

I am sure that there is a configuration problem somewhere in our instance of Snowflake, but I am not a Snowflake or AWS administrator in our organization, and I can't find the documentation that explains this problem (would love to be shown a link!)

That said, I feel that the driver should be able to handle a condition like this (empty _qrmk_ value), either by allowing it to skip adding the headers, or at least a more descriptive error message.

### Configuration
*Driver version:* 1.0.5
*Dotnet framework and version:*  .NET standard 2.0
*Server version:* 3.7.4
*Client OS:* Windows 10

**Comment by howryu** [comment]
@brendenblack Thanks for your reporting. Can you share which deployment are you running against? Also, can you tell me the query id that is missing qrmk? It would be best if you can enable logging. Our README.md has a section on how to enable logging in .net driver. You don't need to wait till timeout. I just want to see the first query response from server.

**Comment by brendenblack** [comment]
Hi @howryu , I'm not sure how to see which deployment I'm running against. I do have logs but I'm hesitant to post them with all of the details included in them. Here are a few sanitized snippets that hopefully give you what you need to see:

```
DEBUG 16-39-2018 20:39:24 Snowflake.Data.Core.RestRequestImpl [5] - Post response: {
  "data" : {
    "parameters" : [{"name":"TIMEZONE","value":"America/Los_Angeles"},{"name":"TIMESTAMP_OUTPUT_FORMAT","value":"DY, DD MON YYYY HH24:MI:SS TZHTZM"},{"name":"TIMESTAMP_NTZ_OUTPUT_FORMAT","value":""},{"name":"TIMESTAMP_LTZ_OUTPUT_FORMAT","value":""},{"name":"TIMESTAMP_TZ_OUTPUT_FORMAT","value":""},{"name":"DATE_OUTPUT_FORMAT","value":"YYYY-MM-DD"},{"name":"TIME_OUTPUT_FORMAT","value":"HH24:MI:SS"},{"name":"CLIENT_DISABLE_INCIDENTS","value":false},{"name":"CLIENT_HONOR_CLIENT_TZ_FOR_TIMESTAMP_NTZ","value":true},{"name":"CLIENT_RESULT_PREFETCH_SLOTS","value":2},{"name":"CLIENT_RESULT_PREFETCH_THREADS","value":1},{"name":"CLIENT_USE_V1_QUERY_API","value":true},{"name":"CLIENT_SESSION_KEEP_ALIVE","value":false},{"name":"CLIENT_SESSION_KEEP_ALIVE_HEARTBEAT_FREQUENCY","value":3600},{"name":"CLIENT_TELEMETRY_ENABLED","value":true},{"name":"BINARY_OUTPUT_FORMAT","value":"HEX"},{"name":"AUTOCOMMIT","value":true},{"name":"CLIENT_PREFETCH_THREADS","value":4},{"name":"CLIENT_MEMORY_LIMIT","value":1536},{"name":"CLIENT_RESULT_CHUNK_SIZE","value":160},{"name":"CLIENT_RESULT_COLUMN_CASE_INSENSITIVE","value":false},{"name":"CLIENT_METADATA_REQUEST_USE_CONNECTION_CTX","value":false},{"name":"CLIENT_TIMESTAMP_TYPE_MAPPING","value":"TIMESTAMP_LTZ"},{"name":"CLIENT_SESSION_CLONE","value":false},{"name":"CLIENT_STAGE_ARRAY_BINDING_THRESHOLD","value":65280},{"name":"CLIENT_CONSENT_CACHE_ID_TOKEN","value":false} ],
    "rowtype" : [{"name":"ITEMCODE","database":"MYDB","schema":"GDRIVE","table":"ITEM_DATA","scale":null,"byteLength":4096,"type":"text","nullable":true,"precision":null,"length":1024} ],
    "rowset" : [ ],
    "chunks" : [ {
      "url" : "<S3 url>",
      "rowCount" : 3324,
      "uncompressedSize" : 113028,
      "compressedSize" : 16811
    } ],
    "total" : 3324,
    "returned" : 3324,
    "queryId" : "22faa847-2113-4c02-afe5-45b45f7a672d",
    "databaseProvider" : null,
    "finalDatabaseName" : "MYDB",
    "finalSchemaName" : null,
    "finalWarehouseName" : "MYWAREHOUSE",
    "finalRoleName" : "ANALYST",
    "numberOfBinds" : 0,
    "arrayBindSupported" : false,
    "statementTypeId" : 4096,
    "version" : 1,
    "sendResultTime" : 1545021565078
  },
  "message" : null,
  "code" : null,
  "success" : true
}
DEBUG 16-39-2018 20:39:24 Snowflake.Data.Core.RestRequestImpl [8] - S3 Download request message Method: GET, RequestUri: '<S3 url>', Version: 2.0, Content: <null>, Headers:
{
  x-amz-server-side-encryption-customer-algorithm: AES256
  x-amz-server-side-encryption-customer-key: <this has not been scrubbed, it is empty>
} 
INFO  16-39-2018 20:39:24 Snowflake.Data.Core.SFResultSet [13] - Get next chunk from chunk downloader 
DEBUG 16-39-2018 20:39:24 Snowflake.Data.Core.HttpUtil+RetryHandler [5] - Failed Response: StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
{
  x-amz-request-id: 7E75F5CD3EDF5422
  x-amz-id-2: H2YGybiXrBfpE5I1ejCjtpfbAT7ZoSBkuF9mg1hm1HcHM2dP801cPHG2i+PDCOFHgf1kPFPua6M=
  Transfer-Encoding: chunked
  Date: Mon, 17 Dec 2018 04:39:25 GMT
  Server: AmazonS3
  Content-Type: application/xml
}  
```

**Comment by howryu** [comment]
@brendenblack That's good payload. Can you tell me the host url you tried to connect...

**Comment by brendenblack** [comment]
It the account you're after when you asked about "which deployment" and the host URL? https://kixeye.snowflakecomputing.com/

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
